DaemonEngine/Daemon

.travis.yml

Fixes #5 
I switched to CI env to ubuntu trusty (14.04), the old ubuntu failed to supply a recent enough cmake and libopusfile-dev.

fix travis build.

---

src/engine/qcommon/qcommon.h

bump protocol since dpk/pk3 support introduced pak list incompatibilities

bump protocol since dpk/pk3 support introduced pak list incompatibilities

---

README.md

Not very important, but it makes README looking better on Github homepage.

fix markdown markup in readme

---

src/common/Util.h

I want to use this to log warnings for some conditions which may occur every frame, without causing massive spam.

Add utility class for performing an action only if at least N milliseconds have passed since the last time.

---

src/common/FileSystem.cpp

Uh, was a real bug, thanks Travis & LLVM (GCC you still have things to learn)!
Le'ts wait on Travis to see if it does not have more stuff to tell us.

fix xdgDataHome retrieving

---

src/engine/client/cl_cgame.cpp
src/engine/client/cl_console.cpp
src/engine/client/cl_input.cpp
src/engine/client/cl_keys.cpp
src/engine/client/keys.h
src/engine/qcommon/q_shared.h
src/engine/qcommon/q_unicode.cpp

The first 3 commits in #43 already were only cleanup so might as well merge them first.

Keys cleanup

---

src/engine/framework/Resource.h
src/shared/VMMain.cpp

This bug I found a few days ago looks like it could be the cause of [Unvanquished #1035](https://github.com/Unvanquished/Unvanquished/issues/1035).

Fix iterator bug

---

CMakeLists.txt
cmake/DaemonFlags.cmake
libs/tinyformat/tinyformat.h
src.cmake
src/common/Assert.h
src/common/String.h
src/common/Util.h
src/engine/client/cl_console.cpp
src/engine/client/cl_input.cpp
src/engine/client/cl_keys.cpp
src/engine/null/null_client.cpp
src/engine/qcommon/common.cpp
src/engine/qcommon/qcommon.h
src/engine/sys/sdl_input.cpp
src/engine/sys/sys_events.h

This is another one of the commits from #43 that is mostly independent of the functional changes.

Refactor event loop

---

src.cmake
src/common/KeyIdentification.cpp
src/common/KeyIdentification.h
src/engine/client/cg_msgdef.h
src/engine/client/cl_cgame.cpp
src/engine/client/cl_keys.cpp
src/engine/client/key_binding.cpp
src/engine/client/key_identification.cpp
src/engine/client/key_identification.h
src/engine/null/NullKeyboard.cpp
src/engine/qcommon/common.cpp
src/engine/sys/sdl_input.cpp

In one of the commits I'm separating out some code that will be useful in the cgame from code that needs to be engine-only. Not sure if "common" is the right directory for some stuff that is used in both client and cgame, but I put it there since "shared" seems to be used for code that is used in cgame/sgame only and never built in the engine.

More key stuff

---

src/engine/renderer/tr_image.cpp

in this case, the `dds/<path without ext>.dds` alternative found must be
used as the best format even if engine usually prefers another one.

support “dds/<path without ext>.dds” texture alternatives like Darkplaces or Doom3

---

src/common/IPC/Common.h
src/common/KeyIdentification.h
src/common/Serialize.h
src/common/System.h
src/common/Util.h
src/engine/client/cg_api.h
src/engine/client/cg_msgdef.h
src/engine/client/cl_cgame.cpp
src/engine/client/cl_keys.cpp
src/engine/client/client.h
src/engine/client/key_binding.cpp
src/engine/client/key_identification.cpp
src/engine/client/key_identification.h
src/engine/client/keycodes.h
src/engine/client/keys.h
src/engine/null/NullKeyboard.cpp
src/engine/sys/sdl_input.cpp
src/shared/client/cg_api.cpp

This updates the cgame ABI to use the new keyboard key representations.
See https://github.com/Unvanquished/Unvanquished/pull/1065 for the cgame side.

New keyboard cgame ABI

---

src/common/cm/cm_load.cpp
src/common/cm/cm_local.h
src/common/cm/cm_test.cpp
src/common/cm/cm_trace.cpp
src/engine/framework/BaseCommands.cpp

Also an unhandled exception in the "math" command.

Fix crash from #94.

---

src/common/cm/cm_load.cpp
src/common/cm/cm_local.h
src/common/cm/cm_test.cpp
src/common/cm/cm_trace.cpp
src/engine/framework/BaseCommands.cpp

merge master into for-0.51.0

---

src/engine/renderer/gl_shader.h
src/engine/renderer/tr_shade.cpp

@gimhael is it ready for merge?
bug reporter @maek confirmed it works
I confirm it works and fixes the issues without noticing any regression

nolightmap stuff, fix #118

---

README.md

I picked these based on what we have for CI.
Fixes #114.

Specify minimum C++ compiler versions.

---

src/engine/client/cl_console.cpp
src/engine/framework/CvarSystem.cpp
src/engine/qcommon/files.cpp
src/engine/qcommon/translation.cpp
src/engine/server/sv_client.cpp
src/engine/server/sv_snapshot.cpp
src/engine/sys/con_curses.cpp

See Unvanquished/Unvanquished#909

Replace ^7 colorcode usage with ^* where it was used as ending null-color

---

src/common/FileSystem.cpp
src/engine/client/cl_cgame.cpp
src/engine/client/cl_input.cpp
src/engine/client/cl_main.cpp
src/engine/client/cl_parse.cpp
src/engine/client/hunk_allocator.cpp
src/engine/null/null_client.cpp
src/engine/qcommon/common.cpp
src/engine/qcommon/qcommon.h
src/engine/server/sv_init.cpp
src/engine/server/sv_main.cpp

VM restarts 2

---

README.md

- add submodule instructions
- get rid of footnotes
- rework markdown markup
- add some badges
- more…

readme: improve instructions, <3 mega

---

.travis.yml

fix travis on macos (brew update)

fix travis on macos (brew update)

---

src.cmake
src/engine/client/key_binding.cpp
src/engine/client/keys.h
src/engine/null/NullKeyboard.cpp
src/engine/sys/sdl_input.cpp

There are other parts to this which will need to go into the for-0.52 branch, the Unvanquished repository, and the unvanquished_src.dpkdir repository.

Function to get or set console keys

---

src/engine/renderer/tr_shade.cpp

tr_shade: feed heatHaze and liquid shader with flatImage if normalmap is missing

tr_shade: feed heatHaze and liquid shader with flatImage if normalmap is missing

---

src/engine/qcommon/files.cpp

While I was toying with `fs_basepath` and `fs_extrapaks` I needed those minor improvement to really know what I was doing.

vfs: improve some pak-loading related messages

---

src/engine/renderer/tr_image.cpp
src/engine/renderer/tr_local.h
src/engine/renderer/tr_shader.cpp

This is very minor but may help to understand how game UI interacts with the renderer.
There is another place in the code which already has a “GUI elements” comment,
not shown by this commit.

bikeshedding: unify some comments to help search for 'GUI elements'

---

src/common/IPC/Primitives.cpp

IPC: attempt to fix Unvanquished/Unvanquished#650 (IPC: Failed to send message)
patch by @Amanieu

IPC: attempt to fix Unvanquished/Unvanquished#650 (IPC: Failed to send message)

---

src/engine/renderer/glsl_source/computeLight_fp.glsl
src/engine/renderer/glsl_source/lightMapping_fp.glsl
src/engine/renderer/glsl_source/vertexLighting_DBS_entity_fp.glsl
src/engine/renderer/glsl_source/vertexLighting_DBS_world_fp.glsl

makes things more obvious to read

polishing: better names in glsl code

---

src/common/Debugger.cpp
src/common/FileSystem.cpp
src/common/IPC/CommandBuffer.cpp
src/common/IPC/Primitives.cpp
src/common/IPC/Primitives.h
src/common/Serialize.h
src/common/String.cpp
src/common/cm/cm_test.cpp
src/engine/client/cl_main.cpp
src/engine/client/dl_main.cpp
src/engine/framework/BaseCommands.cpp
src/engine/framework/CvarSystem.cpp
src/engine/framework/VirtualMachine.cpp
src/engine/framework/VirtualMachine.h
src/engine/qcommon/md5.cpp
src/engine/qcommon/net_ip.cpp
src/engine/qcommon/parse.cpp
src/engine/qcommon/q_unicode.cpp
src/engine/renderer/tr_local.h
src/engine/renderer/tr_noise.cpp

Some fixes from PVS Studio static analyzer.
Product page: https://www.viva64.com/en/pvs-studio/
How to use for free: https://www.viva64.com/en/b/0600/

Static analyzer (PVS Studio) fixes

---

src/engine/server/sv_init.cpp

This fixes Unvanquished/Unvanquished#1122

Add layout to serverinfo

---

src/engine/renderer/gl_shader.cpp
src/engine/renderer/gl_shader.h
src/engine/renderer/glsl_source/forwardLighting_fp.glsl
src/engine/renderer/glsl_source/lightMapping_fp.glsl
src/engine/renderer/glsl_source/liquid_fp.glsl
src/engine/renderer/glsl_source/reflection_CB_fp.glsl
src/engine/renderer/glsl_source/reliefMapping_fp.glsl
src/engine/renderer/tr_init.cpp
src/engine/renderer/tr_local.h
src/engine/renderer/tr_shade.cpp
src/engine/renderer/tr_shader.cpp

renderer: cvar flags and name update

renderer: cvar flags and name update

---

src/engine/renderer/tr_image_crn.cpp

Show detailed explanation of CRN image load errors for client.
Related to https://github.com/DaemonEngine/Daemon/issues/220

Show detailed CRN image load warnings

---

libs/findlocale/findlocale.c
libs/minizip/ioapi.c
libs/nacl/native_client/src/shared/imc/win/nacl_imc.cc
libs/pdcurses/win32a/pdcscrn.c
libs/tinygettext/po_parser.cpp

Some fixes from PVS Studio static analyzer.
Product page: https://www.viva64.com/en/pvs-studio/
How to use for free: https://www.viva64.com/en/b/0600/

PVS Studio fixes for used libs

---

src/engine/renderer/tr_init.cpp
src/engine/renderer/tr_local.h
src/engine/sys/sdl_glimp.cpp

it looks like the code was ready but was missing a cvar to enable it

renderer: disclose r_noBorder

---

src/engine/qcommon/q_shared.h

cleanup: dodge does not exist anymore, document buttons defined in game code

cleanup: dodge does not exist anymore, document buttons defined in game code

---

src/engine/sys/sdl_glimp.cpp

refactor extension loading code
also make sure extension loading is always logged (and the same way)

renderer: refactor extension loading code

---

src/engine/renderer/tr_shader.cpp

- fixes #376 issue introduced in 76cf787f21bb483ede76c4f614fb89aa71581f96
- makes #358 working as expected
- see also #377 for hardening the fix for #376

tr_shader: test against cvar value instead of pointer, fix #376, ref #358, #377

---

src/engine/renderer/gl_shader.cpp
src/engine/renderer/tr_init.cpp

Also fix the existing errors which arise on my machine.

Enable OpenGL error checking

---

src/engine/server/sv_main.cpp

needed for Unvanquished/Unvanquished#1234

ignore sv_timeout for bots

---

.travis.yml
cmake/DaemonCBSE.cmake

It hasn't worked for a few months.

Travis CI: Disable Mac build

---

CMakeLists.txt
external_deps/build.sh
src/engine/renderer/tr_local.h

See https://github.com/Unvanquished/release-scripts/pull/3

Fixes to aid Linux static build

---

src/engine/renderer/tr_bsp.cpp

Fix crash with invalid light grid data size

---

cmake/DaemonFlags.cmake
external_deps/build.sh

Enable ASLR on Mac

---

src/engine/renderer/tr_init.cpp

- make `r_fastsky` cvar an archive one.

make r_fastsky cvar an archive one

---

src/engine/renderer/tr_model_iqm.cpp

To fix https://github.com/Unvanquished/Unvanquished/issues/1393.

Renderer: never cull 1st-person IQM models

---

src/common/Defs.h

See also: https://github.com/Unvanquished/Unvanquished/pull/1392

[0.52] things to merge at the very last moment

---

src/engine/server/sv_client.cpp

`downloadSize` is `int`, but `FS::offset_t` is `int64_t`.
So pak of size > `INT_MAX` is silently truncated to `int` one and may contain bad data.
`MSG_WriteLong` accepts `int`, so can't just change `downloadSize` to `int64`. Also client contract uses `int`.

[server] Ensure pak size fit MAX_INT instead of silent truncate

---

README.md

readme: recastnavigation is not a submodule
Also unify the wording with Unvanquished readme

readme: recastnavigation is not a submodule

---

src/engine/renderer/tr_shade.cpp

just a small rewrite of a test I just stumbled on.

tr_shade: small rewrite of a test I just stumbled on

---

src/common/Defs.h
src/engine/server/ServerApplication.cpp
src/engine/server/sv_client.cpp

Fixes https://github.com/Unvanquished/Unvanquished/issues/1445

Fix download with backup URL

---

src/engine/renderer/glsl_source/vertexSkinning_vp.glsl
src/engine/renderer/tr_backend.cpp
src/engine/renderer/tr_cmds.cpp
src/engine/renderer/tr_init.cpp
src/engine/renderer/tr_local.h
src/engine/renderer/tr_vbo.cpp

Fixes #490. TODO: Test on the Nvidia driver to make sure it still works.

Vertex skinning compatible with old GLSL

---

src/engine/sys/sdl_glimp.cpp

Allow r_swapInterval greater than 1, fix #495.
Also fallback to generic sync on adaptive sync unavailability.

sys/sdl_glimp: allow r_swapInterval greater than 1, fix #495

---

src/common/Cvar.h
src/engine/renderer/tr_init.cpp
src/engine/renderer/tr_local.h
src/engine/sys/sdl_glimp.cpp

Add Cvar Reset method

---

cmake/FindWasmtime.cmake
external_deps/build.sh

I only tested on Linux for now.

Add dependencies necessary for WASM

---

src/engine/client/cl_cgame.cpp
src/engine/client/cl_main.cpp
src/engine/client/client.h

see https://github.com/Unvanquished/Unvanquished/pull/1276.

Rework team damage handling

---

src/common/Compiler.h
src/common/System.cpp
src/common/Util.h
src/engine/client/cl_avi.cpp
src/engine/client/cl_main.cpp
src/engine/qcommon/logging.h
src/engine/qcommon/msg.cpp
src/engine/qcommon/net_types.h
src/engine/qcommon/q_shared.cpp
src/engine/qcommon/q_shared.h
src/engine/qcommon/qcommon.h
src/engine/renderer/tr_bsp.cpp
src/engine/renderer/tr_font.cpp
src/engine/renderer/tr_local.h
src/engine/renderer/tr_model_iqm.cpp
src/engine/renderer/tr_shade.cpp
src/engine/server/server.h
src/engine/server/sv_main.cpp
src/engine/server/sv_snapshot.cpp
src/engine/sys/con_curses.cpp

(This needs https://github.com/Unvanquished/Unvanquished/pull/1468 to be merged in unvanquished for both to compile)

Drop old things

---

src/common/Command.cpp
src/common/Log.cpp
src/engine/qcommon/files.cpp
src/engine/sys/sdl_input.cpp

Small fixes

---

src/common/IPC/Primitives.cpp
src/engine/client/cl_main.cpp

Fix the bad error message reported by @bmorel

Error message for VM timeout

---

src/common/FileSystem.cpp
src/common/FileSystem.h
src/engine/client/cg_api.h
src/engine/framework/CommonVMServices.cpp
src/shared/CommonProxies.cpp

All commits except the first ("Fix crash with FSLoadPakMsg") are used by https://github.com/Unvanquished/Unvanquished/pull/1621 (a lot of the affected code here is compiled into the gamelogic, or both engine and gamelogic)

Filesystem bug fixes and enhancements

---

src/common/System.cpp
src/engine/qcommon/q_shared.h
src/engine/renderer/tr_model_iqm.cpp

old stuff I had, except that I usually just remove the Asan/UBsan offending code. Took the option name from a #572 comment.
There's also some C-style cast removal there, to try to reduce the number of those warnings.

Address sanitizer compat

---

cmake/DaemonFlags.cmake
src/common/System.cpp

_No description provided._
---
_Edit by illwieckz._
Needed by:
- https://github.com/Unvanquished/Unvanquished/pull/1715
See also:
- https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/pull/95

Enable C++14 for RmlUi

---

src/engine/framework/Network.cpp
src/engine/framework/Network.h
src/engine/qcommon/net_ip.cpp
src/engine/qcommon/qcommon.h
src/engine/server/server.h
src/engine/server/sv_ccmds.cpp
src/engine/server/sv_init.cpp
src/engine/server/sv_main.cpp

Use a thread for DNS resolution of master server

---

README.md

See https://github.com/Unvanquished/Unvanquished/pull/1776, requested @illwieckz

Replace freenode with Libera Chat in the README

---

src/common/FileSystem.cpp

FileSystem: ignore files listed in `DELETED` in delta pak dependencies
The code is expected to be only reliable for ignoring deleted files in dependencies. For example if the unvanquished_0.52.2.dpk pak lists the scripts/colors.shader file in DELETED file and has unvanquished_0.52.dpk in DEPS, the scripts/colors.shader file from unvanquished_0.52.dpk will be ignored.
But if the scripts/colors.shader file is still shipped in unvanquished_0.52.2.dpk and listed in DELETED from unvanquished_0.52.2.dpk you cannot expect the file to be ignored, it is expected the user delete it for real in the parent pak.
It only ignores deleted files from dependency paks sharing the same base name. For example if the unvanquished_0.52.2.dpk pak lists the scripts/colors.shader file in DELETED file, this file …

FileSystem: ignore files listed in DELETED from delta pak dependencies

---

src/engine/renderer/tr_init.cpp
src/engine/renderer/tr_local.h

I found this while working on https://github.com/DaemonEngine/Daemon/pull/595 :slightly_smiling_face:

Remove unused `r_simpleMipmaps` cvar

---

src/engine/qcommon/common.cpp

This prevents the first-person weapon model from flickering
and also avoids persistent "Connection Interrupted" screens.
Make possible to really unlock FPS with maxfps -1.
This rewrite a bit:
- https://github.com/DaemonEngine/Daemon/pull/595
---
Fix #595
Fix Unvanquished/Unvanquished#1734

Lower maximum FPS to 333 to avoid various issues (rewrite)

---

src/engine/client/ClientApplication.cpp
src/engine/framework/Application.cpp
src/engine/framework/Application.h
src/engine/framework/System.cpp
src/engine/server/ServerApplication.cpp

Also forward `-connect`, fix:
- #607

Also forward -connect, fix #607

---

cmake/DaemonFlags.cmake

Fixes https://github.com/Unvanquished/Unvanquished/issues/1792

Fix DLL unloading on Linux

---

src/engine/framework/BaseCommands.cpp

Add time units like `s` (second), `m` (minute), `h` (hour), so someone can do:
```
delay 10s say "10 second has passed!"
```
Also improve a bit the builtin help.

add some time units to `delay` command

---

src.cmake
src/engine/client/cg_api.h
src/engine/client/cg_msgdef.h
src/engine/client/cl_cgame.cpp
src/engine/renderer/gl_shader.cpp
src/engine/renderer/gl_shader.h
src/engine/renderer/glsl_source/generic2D_fp.glsl
src/engine/renderer/glsl_source/generic_fp.glsl
src/engine/renderer/shaders.cpp
src/engine/renderer/tr_backend.cpp
src/engine/renderer/tr_cmds.cpp
src/engine/renderer/tr_init.cpp
src/engine/renderer/tr_local.h
src/engine/renderer/tr_public.h
src/engine/renderer/tr_shade.cpp
src/shared/client/cg_api.cpp

This implements transformations required to support RmlUI's transform
code. This implements the cgame plumbing and the renderer code.

transforms: Implement Push/PopMatrix.

---

src/engine/renderer/glsl_source/generic_fp.glsl

Tested on M1 Mac and Windows+Nvidia.

Fix shader compile error on Mac

---

src/engine/server/sv_main.cpp

https://github.com/Unvanquished/Unvanquished/issues/2009

Fix bad admin message log suppression

---

src/common/FileSystem.cpp

Fix DELETED parser loading wrong file

---

src/engine/renderer/glsl_source/computeLight_fp.glsl

Revert shader refactoring

---

src/engine/renderer/tr_shade.cpp

tr_shader: some missing switch cases for collapsed PBR stages

---

src/engine/renderer/tr_shade.cpp

Do not multiply standalone lightmap by `rgbGen` or `alphaGen` unless they're set as `const`.
In `lightMapping_fp.glsl` we do:
```glsl
diffuse *= var_Color;
```
This is needed to be able to blend two multitextured collapsed stage like when doing terrain blending (blending rock and sand).
But we should not do it with standalone lightmap stages, otherwise it would break q3map2 light styles, likely because in such situation we do not blend a lightmap on a diffusemap but we blend a white texture passed as a lightmap on the lightmap passed as a diffusemap and then we would not multiply a diffuse but a lightmap.
To avoid the lightmap-as-a-diffuse being multiplied by some values intended for diffuse maps, we can simply set the color to white as `diffuse * 1.0  == diffuse`.
But we should still …

tr_shader: do not multiply standalone lightmap by rgbGen unless it's const, fix #677

---

src/engine/renderer/tr_bsp.cpp
src/engine/renderer/tr_local.h
src/engine/renderer/tr_shade.cpp

It is broken, is a nest of bugs, and the maintenance cost is too high for
the very minor unverified benefits purposed for unrecommended things.
Fixes:
- https://github.com/DaemonEngine/Daemon/issues/689
* https://github.com/DaemonEngine/Daemon/issues/327
* https://github.com/DaemonEngine/Daemon/issues/687
* https://github.com/DaemonEngine/Daemon/issues/688
Burn fatLightmap with fire, fix #689, #327, #687, #688.

tr_bsp: drop fatLightmap support, fix #689, #327, #687, #688

---

src/engine/renderer/tr_shade.cpp

It looks like the day I wrote those lines I have done too much bash.
Also indent some other lines.

tr_shade: correct line ending

---

azure-pipelines.yml
src/engine/framework/VirtualMachine.cpp

"This is a scheduled macOS-10.15 brownout. The macOS-10.15 environment is deprecated and will be removed on September 30th, 2022."

CI: bump Mac image

---

external_deps/build.sh
src/engine/framework/CommandSystem.cpp
src/engine/framework/CommandSystem.h
src/engine/framework/CvarSystem.cpp
src/engine/framework/LogSystem.cpp
src/engine/framework/System.cpp

Cvar namespace completion + detritus

---

src/engine/client/cg_api.h

See https://github.com/Unvanquished/Unvanquished/pull/2267 for the unvanquished corresponding commit. This should be merged afterwards.

Remove all trap_CM_* defines

---

src/engine/framework/CvarSystem.cpp

I think this was fairly agreed upon on IRC/Matrix. Let's do it!

Don't set cvar as archived on /cvarname command

---

cmake/DaemonFlags.cmake
src/engine/renderer/tr_model_iqm.cpp

tr_model_iqm: compile with -O1 on armhf

---

src/engine/renderer/gl_shader.cpp
src/engine/renderer/tr_backend.cpp
src/engine/renderer/tr_fbo.cpp
src/engine/renderer/tr_image.cpp
src/engine/renderer/tr_main.cpp
src/engine/renderer/tr_public.h
src/engine/renderer/tr_shade.cpp
src/engine/renderer/tr_vbo.cpp

- do not load tiled renderer images if tiled renderer is disabled
- disable tiled renderer if float image are unavailable
fix #745

tr_image: disable tiled renderer if float image are unavailable, fix #745

---

src/common/Log.cpp
src/engine/client/cl_cgame.cpp
src/engine/client/cl_main.cpp
src/engine/framework/VirtualMachine.cpp
src/engine/qcommon/common.cpp
src/engine/qcommon/net_chan.cpp
src/engine/qcommon/sys.h
src/engine/server/sv_ccmds.cpp
src/engine/server/sv_init.cpp
src/engine/server/sv_main.cpp
src/engine/server/sv_sgame.cpp
src/engine/sys/sdl_input.cpp

Shut down to stop time overflow

---

src/engine/qcommon/q_shared.h

This needs https://github.com/Unvanquished/Unvanquished/pull/2327 to avoid breaking unvanquished.
Fixes https://github.com/DaemonEngine/Daemon/issues/719.

Raise entity limit

---

src/engine/renderer/tr_image.cpp

Prevent R_Rotate buffer overrun

---

src/common/cm/cm_patch.cpp
src/common/cm/cm_patch.h

Support for https://github.com/Unvanquished/Unvanquished/pull/2402

Expose cm_patch.cpp functions for navgen

---

src/common/Compiler.h

Used for https://github.com/Unvanquished/Unvanquished/pull/2253

Add CountTrailingZeroes() implemented by intrinsics

---

src/common/cm/cm_public.h
src/common/cm/cm_trace.cpp

Make CM_BoxTrace mins and maxs const.
All CM_BoxTrace is doing is to call CM_Trace that already has mins and maxs const.

cm_trace: make CM_BoxTrace mins and maxs const

---

src/engine/renderer/tr_main.cpp

Alternative version of one of the commits in #813.

Fix "bad portal" handling (permanently broke renderer)

---

src/engine/renderer/tr_backend.cpp

Fixes https://github.com/Unvanquished/Unvanquished/issues/603.

Fix extra skeleton hands in mirror

---

src/common/Compiler.h
src/engine/client/cl_main.cpp
src/engine/renderer/tr_init.cpp
src/engine/server/sv_init.cpp

Introduce `ResetStruct` function, reusable and customizable per compiler.

 Compiler: introduce `ResetStruct` function, reusable and customizable per compiler

---

src/engine/renderer/tr_shade.cpp

Avoid dereferencing pointers multiple time.
Also simplify switch case wording.

tr_shade: avoid dereferencing pointers multiple times

---

external_deps/build.sh

Patches stolen from:
Those ones do not update libraries, they improve the script.
Some of those changes look a bit like bikeshedding, but others make the script more robust and some may fixes bugs.

external_deps: improvements

---

external_deps/build.sh

Patches stolen from:
This is just about rewording some help message.

external_deps: some help rewording

---

src/shared/client/cg_api.cpp

Note that this code lives in the gamelogic, so we can use it immediately without needing a new engine version.

Keep a cache of usercmd_t's in cgame

---

external_deps/build.sh

- more error detection
- set some variables early
- whitespace

external_deps: some rewrites

---

external_deps/build.sh

external_deps: package windows archives without symlinks

external_deps: package windows archives without symlinks

---

src/common/Cvar.h
src/engine/renderer/gl_shader.h

Free the vector of GLShader

---

CMakeLists.txt

#904 doesn't work... maybe I had already manually fixed it when I tried it then forgot

Fix SDL2.dll copying for MSVC

---

src/common/System.cpp

Windows: exit process now, I mean NOW

---

src/engine/client/cl_main.cpp
src/engine/client/client.h

Some cleanup in client's server listing code, in preparation to rewrite the server list API to fix #284, #654, etc.

Server listing cleanup

---

CMakeLists.txt
libs/tinyformat/TinyformatTest.cpp
libs/tinyformat/tinyformat.h
src.cmake
src/common/String.h

Fixes https://github.com/Unvanquished/Unvanquished/issues/2696.

Implement numbered arguments for format strings

---

src.cmake
src/common/Color.cpp
src/common/Color.h
src/common/ColorTest.cpp
src/engine/client/cl_console.cpp

Fixes #839.
Also add unit tests for other StripColors variants.

Remove in-place variant of StripColors

---

src/engine/renderer/tr_backend.cpp

I've copied a bit of code from Tess_DrawElements without comprehension.
Fixes #924.

Fix debug drawing (used for navedit)

---

src/engine/renderer/tr_shader.cpp

Attempt to fix #865:
- https://github.com/DaemonEngine/Daemon/issues/865
I'm not sure about what I am doing.

Attempt to fix warning of pointer points outside of underlying object

---

src/engine/client/cl_avi.cpp
src/engine/client/cl_cgame.cpp
src/engine/client/cl_console.cpp
src/engine/client/cl_download.cpp
src/engine/client/cl_main.cpp
src/engine/client/cl_parse.cpp
src/engine/client/hunk_allocator.cpp
src/engine/framework/CvarSystem.cpp
src/engine/framework/VirtualMachine.cpp
src/engine/null/null_client.cpp
src/engine/qcommon/common.cpp
src/engine/qcommon/msg.cpp
src/engine/qcommon/net_chan.cpp
src/engine/qcommon/net_ip.cpp
src/engine/qcommon/q_shared.cpp
src/engine/renderer/tr_animation.cpp
src/engine/renderer/tr_bsp.cpp
src/engine/renderer/tr_cmds.cpp
src/engine/renderer/tr_image.cpp
src/engine/renderer/tr_model.cpp
src/engine/renderer/tr_scene.cpp
src/engine/renderer/tr_skin.cpp
src/engine/server/sv_ccmds.cpp
src/engine/server/sv_client.cpp
src/engine/server/sv_init.cpp
src/engine/server/sv_main.cpp
src/engine/server/sv_sgame.cpp
src/engine/sys/sdl_glimp.cpp
src/engine/sys/sdl_input.cpp
src/shared/server/sg_api.cpp

Bonus: get rid of double newlines on all log messages

Console bug fixes: lost color on line wrap and /clear crash

---

src/engine/renderer/tr_local.h
src/engine/renderer/tr_model_md5.cpp
src/engine/renderer/tr_model_skel.cpp
src/engine/renderer/tr_surface.cpp

models: convert to MD5 half floats at load time, remake of #953 by @slipher:
- https://github.com/DaemonEngine/Daemon/pull/953

models: convert to MD5 half floats at load time, remake of #953

---

src/engine/framework/VirtualMachine.cpp
src/engine/renderer/tr_image_dds.cpp

Approved commits from:
- https://github.com/DaemonEngine/Daemon/pull/957#issuecomment-1806676043
I'm just running the CI on them.

CI: bmorel 928-01

---

src/engine/qcommon/common.cpp
src/engine/qcommon/cvar.cpp
src/engine/server/server.h
src/engine/server/sv_client.cpp

Approved commits from:
- https://github.com/DaemonEngine/Daemon/pull/957#issuecomment-1807276841
I'm just running the CI on them.

CI: bmorel 928-02

---

src/common/cm/cm_local.h
src/common/cm/cm_trace.cpp
src/common/cm/unittest.cpp
src/engine/qcommon/q_shared.h

https://github.com/Unvanquished/Unvanquished/issues/2848

Tracing: revert allsolid implementation for patches

---

src/engine/qcommon/files.cpp
src/engine/qcommon/qcommon.h
src/engine/server/sv_init.cpp

A clean-up commit that was first pushed to #964 but now unneeded so I submit it separately.

files: use std::string in FS_LoadPak

---

CMakeLists.txt
external_deps/build.sh

external_deps: update WebP

---

src/engine/client/cl_serverlist.cpp
src/engine/qcommon/msg.cpp
src/engine/qcommon/qcommon.h

I don't have access to a French network, so these numbers are pulled out
my ass and not based on any practical testing.

Enable ping retries and spacing by default

---

src/engine/renderer/tr_backend.cpp

bmorel sent me this patch, on my end it fixes:
- https://github.com/DaemonEngine/Daemon/issues/1002
Same as:
- https://github.com/DaemonEngine/Daemon/pull/1003
but smaller.

renderer: quick fix for grangermaze crash, fix #1002

---

external_deps/build.sh

Allow to fetch archives from various mirrors, cycling until one works.
Add a bunch of known mirrors for some packages.
Do some minor rewriting to unify the wording.
Fixes #1006 and #1007:
- https://github.com/DaemonEngine/Daemon/issues/1006
- https://github.com/DaemonEngine/Daemon/issues/1007

external_deps: allow to fetch archives from various mirrors

---

src/engine/renderer/tr_shade.cpp

Fix some bad whitespace introduced by lazy rebase merge

Fix some bad whitespace introduced by lazy rebase merge

---

src/engine/client/cl_cgame.cpp
src/engine/client/cl_keys.cpp
src/engine/client/keys.h
src/engine/null/NullKeyboard.cpp
src/engine/null/null_input.cpp
src/engine/qcommon/common.cpp
src/engine/qcommon/qcommon.h
src/engine/sys/sdl_input.cpp

This restructuring is needed for the code to implement input to the UI and binds simultaneously.

Keyboard input handling: refactoring and minor improvements

---

src/engine/renderer/tr_main.cpp

Complementary pr to: https://github.com/Unvanquished/Unvanquished/pull/2910
Previously, we had a naive implementation of portal rotations (i. e. the origin and axis of the view rendered in a portal surface), which resulted in incorrect rendering, e. g. on the map grangermaze.
Changes portal calculations to get proper views using local->world and world->local transforms with quats. Quats were chosen for convenience and because I plan to do some things with portals which would involve caching them - likely in cgame or sgame, so storing and potentially sending them from the server as 4 floats instead of e. g. 16 for a matrix would be better. Removed skinNum usage because it was previously used to give roll to cameras. It wasn't working and now it will be parsed in sgame anyway.
The code for …

Fix portal rotation

---

src/engine/renderer/gl_shader.cpp

Invalidate GLSL shaders when headers change.

renderer: invalidate GLSL shaders when headers change

---

src/common/System.cpp
src/common/System.h
src/shared/VMMain.cpp
src/shared/VMMain.h

Detect some operations invalid for a non-main thread

---

src/engine/renderer/tr_shade.cpp

Exported from:
- https://github.com/DaemonEngine/Daemon/pull/1075
This can be merged separately.

renderer: reusable SetRgbaGen

---

src/engine/renderer/tr_shade.cpp

Exported from:
- https://github.com/DaemonEngine/Daemon/pull/1075
This can be merged separately.

renderer: rewrite SetNormalScale without looping and branching

---

src/engine/renderer/tr_local.h
src/engine/renderer/tr_shade.cpp
src/engine/renderer/tr_shader.cpp

- use smaller stage struct
- prevent the engine to use the PBR shader when it is disabled (do not crash)
- improve the wording in various places

renderer: rewrite a bit the shader selection

---

src/engine/renderer/tr_backend.cpp
src/engine/renderer/tr_local.h
src/engine/renderer/tr_main.cpp
src/engine/renderer/tr_shade.cpp
src/engine/renderer/tr_shader.cpp

Move more material stage computation and branching previously done at render time to be done at shader parsing time (at map loading time).
Also factorize some boiler plate code.

renderer: select stage renderer at loading time

---

src/engine/renderer/gl_shader.cpp

gl_shader: use iterator

---

src/engine/client/cl_keys.cpp

Typo in 65b4369a.
Fixes https://github.com/Unvanquished/Unvanquished/issues/2982

Fix modifier key regression in 0.55 branch

---

src/engine/renderer/tr_shade.cpp

Remaining unreviewed commit from:
- https://github.com/DaemonEngine/Daemon/pull/1099

tr_shade: simplify Tess_Begin

---

.appveyor.yml
azure-pipelines.yml

ci: sync branch submodules

---

src/engine/renderer/tr_image_crn.cpp

Companion: https://github.com/DaemonEngine/crunch/pull/45
This should decrease the load time of Unvanquished by at least 5%.

Don't CRC all the .crn files in release mode

---

src/engine/renderer/gl_shader.cpp
src/engine/renderer/gl_shader.h

Remove some unused shader uniforms

---

azure-pipelines.yml
src/engine/client/cl_serverlist.cpp
src/engine/renderer/tr_model.cpp

azure: MacOS-11 -> MacOS-12

---

src/engine/renderer/tr_image.cpp

Fix some incorrect multipliers and add the computation for compressed formats.

Fix imageFormatNameSize for remaining texture formats

---

src/engine/server/sv_init.cpp
src/engine/server/sv_main.cpp

The bug is described in #1215.

Server: fix buggy configstring transmission

---

src/engine/renderer/tr_local.h
src/engine/renderer/tr_model_iqm.cpp
src/engine/renderer/tr_model_md3.cpp
src/engine/renderer/tr_model_md5.cpp
src/engine/renderer/tr_model_skel.cpp
src/engine/renderer/tr_model_skel.h
src/engine/renderer/tr_vbo.cpp

Also don't quit if the model name is bigger than the buffer. It doesn't really matter.

Show model names in /listVBOs command

---

src/engine/renderer/glsl_source/forwardLighting_fp.glsl
src/engine/renderer/glsl_source/lightMapping_fp.glsl

Fixed missing function argument. Also fixed the incorrect handling of standalone height map vs height map-in-normal map in lightMapping shader.

Fix legacy renderer forward shader

---

src/engine/renderer/gl_shader.cpp
src/engine/renderer/gl_shader.h
src/engine/renderer/glsl_source/generic_vp.glsl

Change the remaining vertex/fragment lib usages to use #insert instead and nuke the libs themselves.

NUKE vertex/fragment shader libs

---

src/engine/renderer/Material.cpp

Fix 0-size mip-levels in depth-reduction image

---

src/engine/renderer/Material.cpp
src/engine/renderer/Material.h
src/engine/renderer/gl_shader.cpp
src/engine/renderer/gl_shader.h
src/engine/renderer/tr_backend.cpp
src/engine/renderer/tr_bsp.cpp
src/engine/renderer/tr_local.h
src/engine/renderer/tr_shade.cpp
src/engine/renderer/tr_shade_calc.cpp
src/engine/renderer/tr_surface.cpp
src/engine/renderer/tr_types.h
src/engine/renderer/tr_vbo.cpp

Closes #730. This doesn't actually fix any bugs (except warning spam), but there are other, better issues which track the bugs.

Autosprite-related cleanup

---

src/engine/renderer/gl_shader.cpp
src/engine/renderer/tr_shade.cpp
src/engine/renderer/tr_vbo.cpp

- Material system on + `r_reflectionMapping 1`
- `r_arb_map_buffer_range 0` + `r_arb_sync 1` + `r_arb_buffer_storage 1`

Fix 2 cvar combinations which break the renderer

---

src/engine/renderer/Material.cpp
src/engine/renderer/Material.h

Fixes a regression introduced in #1204.

Fix stage sync

---

src/engine/renderer/Material.cpp

Clear portalStack on MaterialSystem::Free()

---

src/engine/renderer/tr_shader.cpp

Yes another step in my effort to make that shader code less messy and easier to follow, here moving more things out of the lengthy `FinishShader` function and factorizing the code more to avoid copy-paste errors when modifying it.

tr_shader: factorize stage checking and move the code to a dedicated function

---

src/engine/renderer/Material.cpp
src/engine/renderer/Material.h
src/engine/renderer/tr_backend.cpp
src/engine/renderer/tr_bsp.cpp
src/engine/renderer/tr_init.cpp
src/engine/renderer/tr_light.cpp
src/engine/renderer/tr_local.h
src/engine/renderer/tr_main.cpp
src/engine/renderer/tr_shade.cpp
src/engine/renderer/tr_surface.cpp
src/engine/renderer/tr_vbo.cpp

Mostly cleanup that's needed for #1281. There's one bug fix for scenes with lots of portals on the material system.

Renderer cleanup: tessellation and portals

---

src/engine/renderer/tr_bsp.cpp
src/engine/renderer/tr_image.cpp
src/engine/renderer/tr_local.h
src/engine/renderer/tr_sky.cpp

This can be seen on the Pulse map.

Use blackCube image instead of nothing for missing skybox image

---

src/engine/renderer/Material.cpp
src/engine/renderer/Material.h

Fixes the issue uncovered in #1301, as well as an issue that resulted in every view using the main view's origin.

Fix material system PVS lock

---

src/engine/renderer/gl_shader.cpp

In fact after factorizing the code more I brought back the vectors.
---
Original message:
@slipher recently taught me we can use shiny C++ for-each feature with classic C arrays, so better use C arrays instead of vectors where the data is known in advance, also make it static.

tr_shade: factorise GLSL header generation more

---

src/engine/renderer/glsl_source/computeLight_fp.glsl
src/engine/renderer/glsl_source/lighttile_fp.glsl

Fix a bug introduced in #1333.

Fix light ID computation

---

src/engine/renderer/glsl_source/computeLight_fp.glsl
src/engine/renderer/glsl_source/forwardLighting_fp.glsl

Better merge this before so I can rebase over it:
- https://github.com/DaemonEngine/Daemon/pull/1333

glsl: fix specular mapping with forward lighting

---

src/engine/renderer/tr_shade.cpp

Fix crash with glMapBufferRange-based vertex buffer

---

src/engine/renderer/tr_image.cpp

Account for mipmaps to report more accurate memory data.

Fix R_ListImages_f() image size

---

src/engine/renderer/tr_backend.cpp

Fix incorrect texture bind in RB_RenderGlobalFog()

---

README.md

readme: use same color as Unvanquished readme for irc link, do not advertise #daemon-engine anymore

readme: use same color as Unvanquished readme for irc link, do not advertise #daemon-engine anymore

---

src/engine/client/key_binding.cpp

I have no idea how else people are supposed to find anything in that list.

sort the output of command listBinds

---

src/engine/renderer/Material.cpp
src/engine/renderer/ShadeCommon.h
src/engine/renderer/gl_shader.cpp
src/engine/renderer/gl_shader.h
src/engine/renderer/glsl_source/liquid_fp.glsl
src/engine/renderer/tr_shade.cpp

Fix liquid shader compile error

---

external_deps/build.sh

external_deps: fix CFLAGS typo

external_deps: fix CFLAGS typo

---

cmake/DaemonGame.cmake

Also remove duplicative nacl-vms-pexe target.

Make NACL_VMS_PROJECTS accessible to outer scope

---

src/engine/renderer/tr_bsp.cpp

First it calculated the number of points along the negative and positive axes of a dimension of the light grid. Then, instead of just adding those two together to determine the total number of points on the axis, it calculated the coordinates of the minimum and maximum points, subtracted them, and divided by the cell size to get the number of points on the axis. This division was floored, not rounded, so if the difference in coordinates had an error of -0.000001 it would get the wrong answer.
Surprising that this didn't break earlier.
Fixes #1518.

Fix moronic light grid array size calculation

---

src/engine/framework/CvarSystem.cpp
src/engine/qcommon/common.cpp
src/engine/qcommon/cvar.h
src/engine/renderer/tr_backend.cpp
src/engine/renderer/tr_cmds.cpp
src/engine/renderer/tr_init.cpp
src/engine/renderer/tr_local.h
src/engine/server/server.h
src/engine/server/sv_bot.cpp
src/engine/server/sv_ccmds.cpp
src/engine/server/sv_client.cpp
src/engine/server/sv_init.cpp
src/engine/server/sv_main.cpp
src/engine/server/sv_sgame.cpp
src/engine/server/sv_snapshot.cpp
src/engine/sys/con_common.cpp
src/engine/sys/con_curses.cpp
src/engine/sys/con_passive.cpp

Also improved the behavior of `sv_maxclients`.

Cvar migration: handle remaining cvars that use `modified` flag

---

src/engine/client/cg_api.h
src/engine/client/cg_msgdef.h
src/engine/client/cl_cgame.cpp
src/engine/client/cl_serverlist.cpp
src/engine/client/client.h
src/shared/client/cg_api.cpp
src/shared/client/cg_api.h

This will let us start using any data we want from the server info without having to make an engine change.
Companion: https://github.com/Unvanquished/Unvanquished/pull/3311

Send entire server info string to cgame instead of filtering to certain fields

---

cmake/DaemonFlags.cmake

Use `-fPIC` when compiling all object files, but only `-pie` when linking executables.

cmake: use -fPIC when compiling all object files, but only -pie when linking executables

---

cmake/DaemonFlags.cmake

Fixes https://github.com/Unvanquished/Unvanquished/issues/2311.

Turn off fast-math mode by default

---

src/engine/renderer/tr_shade.cpp

Fix UI being affected by subgroup profiler

---

src/engine/renderer/gl_shader.cpp
src/engine/renderer/glsl_source/cameraEffects_fp.glsl

Fixes a regression from #1577.

Fix tonemapping enablement regression

---

src/engine/framework/CvarSystem.cpp

Sort the output of the `listCvars` command.
Inspired from a similar code from the `listCmds` command.
The `matchesValues` vector was unused so it is dropped and not ported to the new code.

framework: sort the output of the `listCvars` command

---

src/engine/framework/Network.cpp

It complained about char_traits<unsigned char> being requested somehow. Anyway allowing arbitrarily large sizes is bad in network code, so use a fixed-size buffer instead of the basic_string<byte>.

Fix compile error with latest Appleclang

---

src/engine/renderer/GLMemory.cpp
src/engine/renderer/Material.cpp
src/engine/renderer/gl_shader.cpp
src/engine/renderer/gl_shader.h

- Fix staging buffer pointer not being reset when freeing it
- Uniforms are now tightly packed into the material struct where possible, e. g. it will try to put a 1-component uniform after a vec3
- Cleaned up some unused material system stuff

Staging buffer and material system clean-up

---

src/engine/renderer/tr_shade.cpp
src/engine/renderer/tr_shader.cpp

Fix heat haze

---

src/engine/renderer/gl_shader.cpp

Remove bindless_image layout declaration from compute header

---

src/engine/renderer/tr_local.h
src/engine/renderer/tr_surface.cpp

Fixes performance regression on map assault caused by log spam from https://github.com/DaemonEngine/Daemon/commit/6b7a7dd23fd414eda97c39f71a754d4c43d02d93

Fix log spam due to bad autosprite configuration

---

CMakeLists.txt
external_deps/build.sh
src/engine/client/dl_main.cpp
src/engine/renderer/GLMemory.h
src/engine/renderer/tr_local.h

Stuff that's good independent of dep upgrades and doesn't conflict with anything else.

Some commits cherry-picked from the external_deps work

---

src/engine/null/null_renderer.cpp
src/engine/renderer/tr_bsp.cpp
src/engine/renderer/tr_init.cpp
src/engine/renderer/tr_local.h
src/engine/renderer/tr_public.h
src/engine/server/server.h
src/engine/server/sg_msgdef.h
src/engine/server/sv_sgame.cpp
src/shared/server/sg_api.cpp
src/shared/server/sg_api.h

Unused now that https://github.com/Unvanquished/Unvanquished/pull/3401 is merged.

NUKE trap_GetEntityToken()

---

src/engine/renderer/tr_image.cpp

When an image is requested to be loaded with different params (imageParams_t), but the only difference is that the first one had a larger minDimension, reuse the image. This happens with the models/buildables/arm/screen_s specular image, which is used with two diffuse maps that want different imageMinDimension.

Allow reusing image requested with lower min detail

---

src/engine/renderer/gl_shader.cpp

Fix wrong assert about material uniforms

---

src/engine/sys/sdl_glimp.cpp

Not that it's worth using on my Intel iGPU - I get like 30 FPS.
Fixes #1260.

Fix material system GLSL compile error on Intel
