- cmake/DaemonCBSE.cmake
- src/engine/client/cl_cgame.cpp
- src/engine/client/cl_keys.cpp
- src/engine/client/cl_main.cpp
- src/engine/client/cl_parse.cpp
- src/engine/client/cl_scrn.cpp
- src/engine/client/client.h
- src/engine/qcommon/common.cpp
This is part of the work to improve demos (see Unvanquished/Unvanquished#988).
It does the following:
* Renames cvars to `demo.*`
* Renames commands to `demo_*`
* Removes demo-related functionality that is completely broken (eg: audio recording)
* Fixes CMake to avoid overwriting submodules during builds
> Clean up the demo console interface

- cmake/FindLua.cmake
The FindLua.cmake function prefers to find the lua library that is
formatted like lua<version>.<os suffix>. This leads to it picking
incompatible headers and libraries on certain distros (notably
Arch). Therefore, if we prefer to find lua.<os suffix> it is more
likely to match with the includes.
> cmake: Prefer to find the raw lua library instead of a versioned one

- cmake/FindLua.cmake
This fixes a bug where the game finds liblua.so, but picks include/lua53
as the include path, causing a mismatch.
> FindLua: Also prefer to find ${PREFIX}/include/lua before versioned lua

- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_local.h
Alternative approach to https://github.com/DaemonEngine/Daemon/pull/11
Difference is that in this approach the console font bitmap is reused for the bone names. Not as clean as https://github.com/DaemonEngine/Daemon/pull/11
> Remove the need for tr.charsetImage

- src/common/Assert.h
- src/common/Compiler.h
- src/common/FileSystem.cpp
On @Kangz [suggest](https://github.com/DaemonEngine/Daemon/pull/14#discussion_r114242327), I added an `UNREACHABLE()` assert macro, but  now the compiler raises some miswarning:
```
warning: control reaches end of non-void function [-Wreturn-type]
```
But we know the code asserts before reaching end of non-void function.
So, instead of adding some useless `return` after the `UNREACHABLE()` assert macro everwhere the compiler raises mistakenly a warning, I added support for some builtin that tells the compiler this code can't be reached.
If the compiler is too old or is'nt supported, it will raise the useless warning, which is not a big issue.
The `UNREACHABLE()` assert macro was renamed to `ASSERT_UNREACHABLE()` like
other assert macros.
> add some unreachable builtin on UNREACHABLE() assert macro

- src/common/FileSystem.cpp
- use ~/.local/share/unvanquished instead of ~/.unvanquished
- move legacy path if exists
- fix Unvanquished/Unvanquished#730
> Linux: follow XDG guidelines

- src/common/Compiler.h
- src/common/FileSystem.cpp
- src/common/Log.cpp
- src/common/Log.h
- src/common/String.h
- src/common/System.h
- src/common/cm/cm_load.cpp
- src/engine/audio/Emitter.cpp
- src/engine/botlib/bot_debug.cpp
- src/engine/botlib/bot_nav_edit.cpp
- src/engine/framework/BaseCommands.cpp
- src/engine/framework/Resource.h
- src/engine/framework/System.cpp
- src/engine/qcommon/net_ip.cpp
- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/tr_animation.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_image_crn.cpp
- src/engine/server/sv_init.cpp
- src/engine/sys/sdl_input.cpp
This a PR replaying Unvanquished/Unvanquished#935 by @dimhotepus on Unvanquished source tree after the engine split.
It obsoletes Unvanquished/Unvanquished#935
This is all @dimhotepus' work, except a small commit I just added to rename an iterator to prevent misread.
> Fix a bunch of PVS-Studio static analyser warnings №2

- src/engine/renderer/tr_shader.cpp
fix badly rendered skyboxes, @gimhael's suggestion.
example of bad rendering:
[![badly rendered skybox](http://dl.illwieckz.net/b/unvanquished/bugs/ugly-skybox/unvanquished_2017-08-09_042549_000.jpg)](http://dl.illwieckz.net/b/unvanquished/bugs/ugly-skybox/unvanquished_2017-08-09_042549_000.jpg)
[![badly rendered skybox](http://dl.illwieckz.net/b/unvanquished/bugs/ugly-skybox/unvanquished_2017-08-09_055650_000.jpg)](http://dl.illwieckz.net/b/unvanquished/bugs/ugly-skybox/unvanquished_2017-08-09_055650_000.jpg)
[![badly rendered skybox](http://dl.illwieckz.net/b/unvanquished/bugs/ugly-skybox/unvanquished_2017-08-09_060043_000.jpg)](http://dl.illwieckz.net/b/unvanquished/bugs/ugly-skybox/unvanquished_2017-08-09_060043_000.jpg)
> fix badly rendered skyboxes

- cmake/DaemonFlags.cmake
[This](https://github.com/DaemonEngine/Daemon/blob/b6e41f7baae75adbd7121e70d7b73b7e19ec4b6a/src/common/Assert.h) is the only usage of the DEBUG_BUILD flag. As RelWithDebInfo is a "release" configuration, assertions should not be enabled. If anyone wants to debug with optimizations enabled, we could add another option for that.
> Turn off debug assertions in RelWithDebInfo builds.

- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_cmds.cpp
- src/engine/renderer/tr_local.h
> Fix RE_RotatedPic and RE_StretchPicGradient rendering.

- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shader.cpp
This change removes support for on-the-fly texture compression in the Daemon engine. The cvars /r_compress*Maps have been removed and the "nocompress" shader keyword has no function, but is kept for backward compatibility.
Anybody who wants to use compressed textures should use an offline texture compression tool, and provide the textures in .dds or .crn format.
> Remove IF_NOCOMPRESSION and compression-related cvars.

- libs/tinyformat/tinyformat.h
- src/common/Compiler.h
- src/engine/client/cl_cgame.cpp
- src/engine/client/cl_main.cpp
- src/engine/qcommon/cmd.cpp
- src/engine/qcommon/parse.cpp
- src/engine/qcommon/q_shared.cpp
Add a conditional macro "DAEMON_FALLTHROUGH" for compilers that care
about this type of thing (GCC7 and Clang6 for now). Update Tinyformat
because they claimed to have fixed the warnings.
> Fix -Wimplicit-fallthrough warnings

- CMakeLists.txt
This fixes [Unvanquished/Unvanquished issue #1002](https://github.com/Unvanquished/Unvanquished/issues/1002) as soon as that project gets updated to this daemon commit.
> add WORKING_DIRECTORY to git revision check, set to CMAKE_SOURCE_DIR

- src/engine/qcommon/qcommon.h
See #18 for the initial change that is now to be reverted.
The reverted change was motivated by the fact the VFS change to introduced DPK support and enable legacy PK3 download brokes too many things (which has implication on package downloading) so it sounded like a good idea to raise protocol number.
Well, it raises many other issues. First, protocol number is hardcoded in client, it can be fixed easily but _meh_. Second, unlike some idtech derivative games that has history of multiple protocol, tremulous never changed the number and unvanquished neither, because of that, no one third-party tool implemented a way to ask for server from all numbers, but they all hardcode the protocol number, it means `qstat`, `xqf`, `apelsin`, `osavul` and `obozrenie` will be broken, and most of them …
> Revert "bump protocol since dpk/pk3 support introduced pak list incompatibilities"

- src/common/FileSystem.cpp
This assert will trigger everytime there is an unrecongized file
in the pakpath. This is bad and wrong.
> FileSystem: Replace bad assert with a verbose log

- src/engine/server/server.h
- src/engine/server/sv_bot.cpp
- src/engine/server/sv_client.cpp
- src/engine/server/sv_init.cpp
- src/engine/server/sv_main.cpp
- Avoid potential crashes with out of bounds value of `sv_privateClients`.
- Implement my suggestion [here](https://github.com/Unvanquished/Unvanquished/issues/1028#issuecomment-335695254) for server stats in the presence of private slot users. Namely, the difference between the number of current clients and the max should be the number of open public slots. For comparison, #40 proposes max clients = max(number of public slots, number of clients).
- Actually prevent users without the right password from occupying the private slots (fixes #41).
> Fix some issues regarding private client slots

- CMakeLists.txt
- cmake/DaemonFlags.cmake
- cmake/DaemonGame.cmake
Pass more flags to the nacl vms build (such as build type and use pch), and fix the bug in pch generation introduced by using a generator expression for DEBUG_BUILD.
> Cmake fixes

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/tr_types.h
- src/engine/sys/sdl_glimp.cpp
Some versions of NVidias OpenGL driver seem to have a bug, and it was just a
performance optimization anyway.
This should fix Unvanquished issue #919.
> Disable extension GL_ARB_texture_gather on NVidia GeForce.

- libs/crunch/crn_decomp.h
- libs/crunch/crn_defs.h
- libs/crunch/crnlib.h
See https://forums.unvanquished.net/viewtopic.php?f=4&t=2158
for a large forum post explaining what's happening.
Basically, Unity is shipping an improved crnlib within their own tools
and they litterally broke the format to make it better.
See https://github.com/Unity-Technologies/crunch/tree/unity
for the original unity's crunch code.
See https://github.com/illwieckz/crunch/tree/unity-daemon
for a temporary branch applying our improvements above unity's ones.
Using their tool on a corpus large by 1979 files from our asset repository
I reported that compression time was divided by more than 4 (reducing from
multiple hours to less than half one) and more than 11% file space saved
in comparison with the crnlib version we currently use (which is an older
version of the same source tree they …
> import unity's improvements to crnlib

- src/engine/renderer/tr_animation.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_model.cpp
- do not try to load iqm animation names as files, they are not files!
- do not complain on missing LoD md3 models, fix #52
- do not complain on missing texture with hardcoded extension since other extensions will be tried
> prevent some false-positive errors to be raised on optional files or file formats

- src/engine/renderer/tr_shader.cpp
There is two possibilites:
- if it's a warning, it does not have to return;
- if it has to return, it's not a warning but an error.
After some testing it appeared it's a warning
so we just have to ignore the whole line and
let the parser read the next line.
It's very useful to ignore unknown dp* and xon* keywords
from darkplaces and xonotic when loading maps from them
for example.
It will help any project wanting to port existing game to
Dæmon to have a better partial support more quickly: this
kind of project would appreciate to be able to focusing on
implementing the ones required for gameplay while not having
any urge to implement the ones that are only needed for
eye candy.
> do not abort shader on “unknown general shader parameter” warning

- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_image_crn.cpp
- src/engine/renderer/tr_image_dds.cpp
- src/engine/renderer/tr_image_ktx.cpp
- src/engine/renderer/tr_local.h
This should enable DXT3/BC2 support for the daemon engine (see issue #82 ).
> DXT3/BC2 support for .dds, .crn and .ktx file formats

- src/engine/framework/Crypto.cpp
[ 69%] Building CXX object daemon_build/CMakeFiles/engine-lib.dir/src/engine/framework/Crypto.cpp.o
/home/modi/unv/Unvanquished/daemon/src/engine/framework/Crypto.cpp: In function ‘Crypto::Data Crypto::Encoding::Base64Encode(const Data&)’:
/home/modi/unv/Unvanquished/daemon/src/engine/framework/Crypto.cpp:157:26: error: invalid conversion from ‘unsigned char*’ to ‘char*’ [-fpermissive]
&ctx, output.data(), input.size(), input.data()
~~~~~~~~~~~^~
In file included from /home/modi/unv/Unvanquished/daemon/src/engine/framework/Crypto.cpp:34:0:
/usr/include/nettle/base64.h:98:1: note:   initializing argument 2 of ‘size_t nettle_base64_encode_update(base64_encode_ctx*, char*, size_t, const uint8_t*)’
base64_encode_update(struct base64_encode_ctx *ctx,
^ …
> crypto: Add casts to fix compile errors.

- src/common/FileSystem.cpp
- src/common/FileSystem.h
- src/engine/framework/System.cpp
The bug is obvious:
In #20 (see also #39) I modified `DefaultHomePath()` in `src/common/FileSystem.cpp` to move legacy homepath to XDG's `.local/share/unvanquished` path (or to follow XDG env vars). But `DefaultHomePath()` is called in `cmdlineArgs_t` initialization in `src/engine/framework/System.cpp` and `cmdlineArgs` is initialized in `ParseCmdline()` in `src/engine/framework/System.cpp` _before_ `-homepath` switch is parsed. So, the engine try to do the default homepath move even if an arbitrary homepath is forced by command line. Which is wrong.
This fix is an attempt to fix that this way:
- `DefaultHomePath()` only returns the xdgpath, so `cmdlineArgs` can be initialized without doing the legacy homepath move;
- an `MigrateHomePath()` function was created to do the homepath move (if …
> do not migrate legacy homepath when using -homepath arg

- src/engine/framework/Crypto.cpp
libnettle 3.4 changed the base64 API to make the args
accept char instead of uint8_t. This causes compile time
warnings (and errors if you compile without -fpermissive),
so wrap the functions for newer versions of nettle to
silence those warnings.
> crypto: Support libnettle 3.4+ without warnings

- src/engine/renderer/tr_shade.cpp
I bisected #68 and found https://github.com/Unvanquished/Unvanquished/commit/833ae67bd157c818eda18791ea8d858b1b9db7ac as the cause. This is a commit that fixes the issues with the particular texture on Thunder. It's probably completely wrong though, so @gimhael should feel free to write his own fix.
> Try to fix the bug with some lightmaps on translucent textures.

- cmake/DaemonGame.cmake
for some reason some nacl vm related build steps are driven by the engine cmake
configuration, hence when the engine is not built as a submodule, the cmake script
has to tell the vm build process where the engine source tree is.
> pass DAEMON_DIR back to nacl vm build

- src/engine/renderer/tr_shader.cpp
everywhere in code normalMap keyword can be used in place of the bumpMap one
except in the blend case, now fixed.
see the original broken code:
```sh
Daemon/src $ grep -r bumpMap
engine/renderer/tr_shader.cpp:			else if ( !Q_stricmp( token, "bumpMap" ) )
engine/renderer/tr_shader.cpp:			else if ( !Q_stricmp( token, "normalMap" ) || !Q_stricmp( token, "bumpMap" ) )
engine/renderer/tr_shader.cpp:		else if ( !Q_stricmp( token, "normalMap" ) || !Q_stricmp( token, "bumpMap" ) )
```
without this, if someones write `blend normalMap` instead of `blend bumpMap`, the engine prints those warning and when affected surface has to be rendered, the engine abort the game and returns to main menu:
```
Warn: unknown blend mode 'normalMap' in shader 'textures/thunder_eX/eX_floor_grate03s', substituting …
```
> normalMap is another name for bumpMap in blend case too

- libs/crunch/crn_decomp.h
- src/engine/renderer/tr_image_crn.cpp
The crunch library apparently "trusts" all input files to have the correct format, and will crash or cause memory corruption if they don't. So this is a hack to turn the `CRND_ASSERT` statements into runtime exceptions, since some of the assertions will usually trigger if you load a file with the old format.
> Catch some crn decoding errors

- .travis.yml
Might remove the engine builds from Unvanquished next so that things only get built in the places they are relevant in.
> improve travis build: +ccache, +osx build, -dependencies

- src/engine/client/cl_cgame.cpp
- src/engine/server/sv_sgame.cpp
The to-be-assigned strings are already providing null-terminated strings, often by means of `Q_strncpyz`, so `std::string::assign(cstring)` will correctly stop copying on termination (excluding '\0').
The replaced usages of `std::string::assign(cstring, size)` were continuing copying past the message body/past any termination to the full buffer length (often `MAX_STRING_CHARS`=1024 bytes)
This was mostly hidden by additional `Q_strncpyz` calls for c-string api compatibility in trap-functions but would fail in modernized code (e.g. with `empty()`).
> Fix buffer over-read via std::string::assign copying from buffers past '\0'.

- src/common/FileSystem.cpp
No longer attempts to get timestamp for directories.
Fixes bug where my_stat (_wstat64i) was failing on Windows when
trailing slash was present.
In the future, trim trailing slash should work on all platforms.
Not sure if this has unintended consequences (are timestamps _really_ useless for dpkdirs?). Please review.
> Fixing FS::InternalLoadPak to only get timestamp for .dpk files.

- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shader.cpp
xmap was the name of the XreaL's fork of q3map
- no need to check for those keywords since original XreaL content
is very unlikely to reach Dæmon without being edited first;
- it's better to tell users about things they use.
The code already talked about q3map instead of xmap in other places of the code so that's now consistent.
> drop references to xmap

- src/common/Serialize.h
- src/engine/renderer/tr_public.h
- src/engine/renderer/tr_types.h
Mostly fixes #148 although there could be a few more `bool`s hiding out in structs.
> Don't serialize bools by copying memory

- src/engine/renderer/glsl_source/liquid_fp.glsl
introduced in 86d4352d6aad71d66360403264ff4a22cd77f72d
I still don't know why the shader compiler never complained before today
> fix buggy parenthesis in liquid glsl shader

- src/engine/server/server.h
- src/engine/server/sv_ccmds.cpp
See #167,  `downloadName` is set to `256` in client but `64` in server, and in anyway, 64 is not large enough.
https://github.com/DaemonEngine/Daemon/blob/9322bda72627da2846310f5e4f624449b22122bf/src/engine/qcommon/q_shared.h#L199-L200
https://github.com/DaemonEngine/Daemon/blob/9322bda72627da2846310f5e4f624449b22122bf/src/engine/client/client.h#L344
https://github.com/DaemonEngine/Daemon/blob/9322bda72627da2846310f5e4f624449b22122bf/src/engine/server/server.h#L171
https://github.com/DaemonEngine/Daemon/blob/9322bda72627da2846310f5e4f624449b22122bf/src/engine/server/sv_ccmds.cpp#L143
> server: 64 bytes are not enough to fit a pak name, client already expects 256, fix #167

- src/engine/renderer/glsl_source/liquid_fp.glsl
`RayIntersectDisplaceMap` is already defined in `reliefMapping_fp.glsl`, doing the exact same thing:
https://github.com/DaemonEngine/Daemon/blob/9322bda72627da2846310f5e4f624449b22122bf/src/engine/renderer/glsl_source/reliefMapping_fp.glsl#L203-L253
> glsl: deduplicate RayIntersectDisplaceMap

- src/engine/audio/Sample.cpp
- src/engine/audio/SoundCodec.cpp
Use `null.wav` as default sound sample instead of `sound/feedback/hit/wav`.
When loading a map with an ambient (looping) sound missing, player just hear an horribly annoying endless `tick tick tick tick` sound. Having a warning or notice in console saying the sound is missing must be enough. No need for a sound feedback.
> null default sound sample

- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_local.h
This is to avoid those boring, false-positive debug messages:
```
Debug: Failed to open 'env/shared_vega_src/sky' for reading: No such file or directory
Debug: Failed to open 'env/shared_vega_src/sky' for reading: No such file or directory
```
Note that the `R_FindImageLoader` code (first two commits) is the one I first pushed in #159.
If first worked on `R_FindImageLoader` for the need of the removal of this debug message, but working on Xonotic stuff was more exciting. :stuck_out_tongue: 
This is better to merge this first, as the image commits will be together, and then the dpMaterial PR would just be 1 commit.
> R_FindCubeImage: avoid the boring “Failed to open” on skybox format try

- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_shader.cpp
detect heightmap in normalmap alpha channel and enable parallax for the given shader
this makes removes the need of an explicit shader keyword telling the engine there is an heightmap embedded in normalmap: if there is an alpha channel in normalmap there is an eightmap, else there is only a normalmap
was experimented first in #159
> R_UploadImage: detect heightmap in normalmap alphachanel

- src/engine/client/cl_main.cpp
- src/engine/client/client.h
This is a PR similar to https://github.com/Unvanquished/Unvanquished/pull/1106 and https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/pull/6
This is to resize the console font size according to screen size so low resolutions don't have huge chars and high resolutions don't have tiny chars.
A `cl_consoleFontScaling` is available for people who wants to disable console font scaling. Making this enabled by default ensures people have a readable console on hiDPI screens.
> responsive: compute console font size from screen size

- src/engine/renderer/tr_image.cpp
The skybox code was very ugly with 10 gotos and buggy behavior, for example it would not attempt to load any multifile skybox if a single-file skybox was successfully loaded but had invalid content.
Also, the code was inefficient, for example it was doing the image rotation operation for every face even if the rotation has an angle of 0°, hence allocating a new image, copying all the pixels in the new image et. for nothing.
Some quake3 skyboxes were shipped with a smaller bottom face, for example a `16×16` bottom face while other faces were `512×512` that was probably a trick to save file size when textures were stored losslessly in a tga and bandwith was low as voice modems.
To fix this, a new `R_Resize` function is added to `tr_image.cpp` that is just a wrapper to `ResampleTexture` that …
> revamp cubemap code and fix quake3 skybox with small bottom face, fix #142

- src/engine/renderer/tr_shader.cpp
If `r_dpMaterial` is set to `on`, load extra textures the [DarkPlaces way](https://gitlab.com/xonotic/darkplaces/blob/7f47f772ef10b488f4ae8012bda40deb30862ed2/gl_rmain.c#L3526) by looking for extra files with special suffixes like `_norm` or `_gloss`.
> ParseShader: load extra maps the DarkPlaces way if r_dpMaterial enabled

- src/engine/botlib/bot_api.h
- src/engine/botlib/bot_convert.cpp
- src/engine/botlib/bot_convert.h
- src/engine/botlib/bot_debug.cpp
- src/engine/botlib/bot_debug.h
- src/engine/botlib/bot_load.cpp
- src/engine/botlib/bot_local.cpp
- src/engine/botlib/bot_local.h
- src/engine/botlib/bot_nav.cpp
- src/engine/botlib/bot_nav_edit.cpp
- src/engine/botlib/bot_navdraw.h
- src/engine/botlib/bot_types.h
- src/engine/botlib/nav.h
- src/engine/renderer/glsl_source/depthtile1_fp.glsl
- src/engine/renderer/glsl_source/depthtile1_vp.glsl
- src/engine/renderer/glsl_source/depthtile2_fp.glsl
- src/engine/renderer/glsl_source/depthtile2_vp.glsl
- src/engine/renderer/glsl_source/fxaa_fp.glsl
- src/engine/renderer/glsl_source/fxaa_vp.glsl
- src/engine/renderer/glsl_source/lighttile_fp.glsl
- src/engine/renderer/glsl_source/lighttile_vp.glsl
See Unvanquished/Unvanquished#1030 for a similar PR on Unvanquished side.
This PR is created to submit licensing fixes and rewording to Daemon source code.
The first commit is about brand new files by @gimhael introduced in commit 0bb3550ce16ab7b165a88ebb365edf6b2837d1f5 that has Tr3b  GPL header just because the skeleton was copypasted (header and main block) but everything is original work.
See that talk:
```
2017-09-06 09:37:16 +0200 <illwieckz>	I have a question though, why the depthtile*glsl / lighttile*glsl files have Tr3b/XreaL/GPL copyright header if they are brand new? Can't we put another copyright and license on them?
2017-09-06 09:37:38 +0200 <illwieckz>	they were introduced in 0bb3550ce16ab7b165a88ebb365edf6b2837d1f5 (Daemon tree)
2017-09-06 09:40:27 +0200 <illwieckz> …
```
> Licensing fixes

- src/engine/renderer/tr_shader.cpp
I hope that it does the same thing the `ColorAdaptor` line did but without modifying alpha channel:
https://github.com/DaemonEngine/Daemon/blob/714566b0db058094eb86090420d3c31b955f929a/src/common/Color.h#L126-L128
[![fixedbug](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/waterbug/unvanquished_2019-03-10_233447_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/waterbug/unvanquished_2019-03-10_233447_000.jpg)
[![fixedbug](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/waterbug/unvanquished_2019-03-10_235500_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/waterbug/unvanquished_2019-03-10_235500_000.jpg)
[![fixedbug](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/waterbug/unvanquished_2019-03-10_235509_000.jpg)] …
> ParseStage: do not overwrite alpha channel with rgbGen const, fix #120

- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_shader.cpp
- improve readability
- reduce cpu complexity
- make it extendable
- fix bug when surface with reflectionmap is not normalmapped
- fix lightmap being applied twice and glow map being lightmapped (note: lightmap alphaGen blend not yet supported)
- reduce the lighting stage type count to two: Phong (any combination including diffuse and something that is not material, including specular) and PBR (any combination including diffuse and material)
- fix the bug when a reflection type is applied to shader lighting type
> tr_shader: revamp the stage collapse code

- src/engine/renderer/gl_shader.cpp
- first commit prepends line numbers to glsl shader dump
- second commit properly reinitializes line count after the the loading of a glsl lib like `reliefMapping_fp.glsl`
> numberize glsl dump output, count lines properly

- src/engine/renderer/gl_shader.h
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_shade.cpp
clean-up some useless macro boilerplate, because it's easier to debug code that has less code
> gl_shader: clean-up some useless macro boilerplate

- src/engine/renderer/tr_shade.cpp
fix a regression introduced in 3d53075
before regression:  
[![deluxe without normal](https://dl.illwieckz.net/b/daemon/bugs/deluxe-without-normal/unvanquished_2019-03-31_093518_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/deluxe-without-normal/unvanquished_2019-03-31_093518_000.jpg)
after regression:  
[![deluxe without normal](https://dl.illwieckz.net/b/daemon/bugs/deluxe-without-normal/unvanquished_2019-03-31_093634_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/deluxe-without-normal/unvanquished_2019-03-31_093634_000.jpg)
after fix:  
[![deluxe without normal](https://dl.illwieckz.net/b/daemon/bugs/deluxe-without-normal/unvanquished_2019-03-31_094947_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/deluxe-without-normal/unvanquished_2019-03-31_094947_000.jpg)
> tr_shader: do not enable deluxe map on material without normal map

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/glsl_source/cameraEffects_fp.glsl
- src/engine/renderer/glsl_source/cameraEffects_vp.glsl
- src/engine/renderer/glsl_source/fogQuake3_fp.glsl
- src/engine/renderer/glsl_source/fogQuake3_vp.glsl
- src/engine/renderer/glsl_source/forwardLighting_fp.glsl
- src/engine/renderer/glsl_source/forwardLighting_vp.glsl
- src/engine/renderer/glsl_source/generic_fp.glsl
- src/engine/renderer/glsl_source/generic_vp.glsl
- src/engine/renderer/glsl_source/heatHaze_fp.glsl
- src/engine/renderer/glsl_source/heatHaze_vp.glsl
- src/engine/renderer/glsl_source/lightMapping_fp.glsl
- src/engine/renderer/glsl_source/lightMapping_vp.glsl
- src/engine/renderer/glsl_source/lightVolume_omni_fp.glsl
- src/engine/renderer/glsl_source/liquid_fp.glsl
- src/engine/renderer/glsl_source/liquid_vp.glsl
- src/engine/renderer/glsl_source/reflection_CB_fp.glsl
- src/engine/renderer/glsl_source/reflection_CB_vp.glsl
- src/engine/renderer/glsl_source/shadowFill_fp.glsl
- src/engine/renderer/glsl_source/shadowFill_vp.glsl
- src/engine/renderer/glsl_source/vertexLighting_DBS_entity_fp.glsl
- src/engine/renderer/glsl_source/vertexLighting_DBS_entity_vp.glsl
- src/engine/renderer/glsl_source/vertexLighting_DBS_world_fp.glsl
- src/engine/renderer/glsl_source/vertexLighting_DBS_world_vp.glsl
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_shade.cpp
The extra compute and boilerplate code seem useless and it already ended in bugs when parallax offset was applied to diffuse, normal, specular but nor glow map, and I would find stupid to add more boilerplate when height map will be implemented.
Diffuse/normal/specular/glow/height maps are component of the same material, so there is no reason to handle their coordinates separately.
Doing this would also avoid the need for a lot of `ifdef` code when normal/specular/glow/parallax support is disabled.
And well, that extra code seems useless even when they are enabled.
It unify the symbol names to `var_TexCoords`.
Alongside the `var_TexDiffuse`, `var_TexNormal`, `var_TexSpecular`, `var_TexGlow` there was some occurrence of `var_Tex`.
Some comments in already rewritten code told that Tr3b had …
> use only one texCoords per surface

- src/engine/audio/SoundCodec.cpp
- src/engine/client/cl_cgame.cpp
- src/engine/client/cl_main.cpp
- src/engine/null/null_renderer.cpp
- src/engine/qcommon/q_shared.h
- src/engine/renderer/tr_font.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_public.h
\+ misc tiny changes
Fixes #162.
> Fix console font resizing

- src/engine/renderer/tr_shader.cpp
ignore inactive stages in collapsable stage lookup
> tr_shader: ignore inactive stages in collapsible stage lookup

- src.cmake
- src/engine/audio/Audio.h
- src/engine/client/ClientApplication.cpp
- src/engine/client/cl_cgame.cpp
- src/engine/client/cl_main.cpp
- src/engine/client/client.h
- src/engine/client/hunk_allocator.cpp
- src/engine/null/null_client.cpp
- src/engine/qcommon/common.cpp
- src/engine/qcommon/qcommon.h
- src/engine/server/ServerApplication.cpp
- src/engine/server/sv_main.cpp
- src/engine/server/sv_sgame.cpp
This is some stuff that has come up while working on #201.
> Preliminary work for VM restarts

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/glsl_source/computeLight_fp.glsl
- src/engine/renderer/glsl_source/dispersion_C_fp.glsl
- src/engine/renderer/glsl_source/forwardLighting_fp.glsl
- src/engine/renderer/glsl_source/heatHaze_fp.glsl
- src/engine/renderer/glsl_source/lightMapping_fp.glsl
- src/engine/renderer/glsl_source/lightVolume_omni_fp.glsl
- src/engine/renderer/glsl_source/liquid_fp.glsl
- src/engine/renderer/glsl_source/reflection_CB_fp.glsl
- src/engine/renderer/glsl_source/refraction_C_fp.glsl
- src/engine/renderer/glsl_source/skybox_fp.glsl
- src/engine/renderer/glsl_source/vertexLighting_DBS_entity_fp.glsl
- src/engine/renderer/glsl_source/vertexLighting_DBS_world_fp.glsl
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_shader.cpp
While I was working on a branch to collapse the reflection cube map stage with the common lightmap one, I did this clean-up.
It makes working on this part of the code easier, but don't have to wait for featural changes to be merged.
Note that one commit makes sure reflective specular is not used whith PBR assets since current reflective specular code is not PBR compatible.
> some tr_shade/glsl code cleanup

- src/engine/renderer/gl_shader.cpp
That's an issue I'm facing since a long time, with problems appearing randomly… Last time I got it was when I was working on #193 and this time it was fully reproducible.
The cached binary shader is expected to be invalidated (then rebuilt) when the content of the shader source change. This is done by computing a checksum at shader compile time and comparing it lately.
Unfortunately, the checksum operation was not checksuming against the header that defines constants like `r_normalMapping`, only the content of the `.glsl` file and some macro. Because of that the shaders where not recompiled when such cvar were modified.
This fixes the issue by concatenating the constant header to the text that is sent to the checksum operation.
> gl_shader: also checksum engine constants to invalidate the shader on cvar change

- src/engine/renderer/tr_bsp.cpp
code by @gimhael :champagne: :100: :tada:
it works and fix #35:
[![parpax fan](https://dl.illwieckz.net/b/unvanquished/bugs/crazy-fan/unvanquished_2019-07-01_223749_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/crazy-fan/unvanquished_2019-07-01_223749_000.jpg)
[![train fan](https://dl.illwieckz.net/b/unvanquished/bugs/crazy-fan/unvanquished_2019-07-01_223844_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/crazy-fan/unvanquished_2019-07-01_223844_000.jpg)
[![metro fan](https://dl.illwieckz.net/b/unvanquished/bugs/crazy-fan/unvanquished_2019-07-01_225414_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/crazy-fan/unvanquished_2019-07-01_225414_000.jpg)
> fix texture rotation, <3 @gimhael, fix #35

- src/engine/renderer/tr_shader.cpp
I was toying with some maps, I was surprised to see many textures missing without any warning telling me what was wrong. It's better to make this a warning.
> make missing shader image a warning

- src/engine/audio/SoundCodec.cpp
- src/engine/renderer/tr_image.cpp
At Quake 3 time it was common to add the .blend suffix to glow maps
so people made files named like:
- textures/something/somename.blend.jpg
If the shader use the full path, the engine will find the file even
if it's shipped in another format, because the engine will look for:
- textures/something/somename.blend.jpg
- textures/something/somename.blend.crn
- textures/something/somename.blend.png
- etc.
But the shader use the extension-independent path, the engine will
not find the file because the .blend suffix will be mistakenly
removed like if it was an extension, and the engine will look for:
- textures/something/somename.jpg
- textures/something/somename.crn
- textures/something/somename.png
- etc.
The engine may either fail to load the file, or load the wrong file
given the …
> load image and sound file with dot in their extension-independent name

- src/common/System.cpp
- src/common/System.h
- src/engine/client/ClientApplication.cpp
- src/engine/client/cl_main.cpp
- src/engine/framework/Application.cpp
- src/engine/framework/Application.h
- src/engine/framework/System.cpp
- src/engine/server/ServerApplication.cpp
- src/engine/server/sv_sgame.cpp
This avoids weird states where a lot of code is unexpectedly executing after a disconnect.
> Start throwing exceptions for disconnect

- src/common/FileSystem.cpp
- src/common/FileSystem.h
- src/common/Log.cpp
- src/engine/client/cl_download.cpp
- src/engine/client/dl_main.cpp
Refactor the HTTP download code with better handling of libcurl errors.
Introduce the PAKSERVER file security feature (see the comments in dl_main.cpp for explanation).
Reviewers may prefer to look at the combined (as opposed to per-commit) diffs for dl_main.cpp as I moved some stuff around multiple times.
Before merging, we should get everyone running a server with HTTP downloads enabled to add the PAKSERVER file.
> HTTP download enhancements

- src/engine/client/cl_download.cpp
- src/engine/client/client.h
- src/engine/client/dl_main.cpp
- src/engine/qcommon/qcommon.h
- src/engine/server/sv_client.cpp
The initial implementation requires the PAKSERVER file to exist in every
directory with downloadable content. This commit makes a change to the
download protocol (to be switched on in the next release) which allows
any prefix of the download URL that ends in '/' to be used as the
directory to check.
> Subdirectory support for PAKSERVER checks

- src/engine/sys/sdl_glimp.cpp
Fix comment to not mislead code readers.
If this test if true, the engine aborts by telling the user:
```
Warn: Couldn't load a renderer
```
> there is no 1.x renderer anymore

- src/engine/botlib/bot_api.h
- src/engine/botlib/bot_load.cpp
- src/engine/server/sv_init.cpp
- srclibs.cmake
I imported the current master of the official repository as the 'upstream' branch in our fork, and pointed the submodule reference to that. I plan to rename the current `master` branch to `obsolete/daemonassert` after that.
But maybe instead of all that, it would be better to revert the one commit in our repository that's different, and merge all the commits from upstream into our master branch. WDYT?
> Remove need for our patch to Detour (see #130)

- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_shader.cpp
This is my attempt to implement pre-collapsed shader stages, as defined in #216.
This will allow to use more than one collapsed (multi-texture) stage per shader.
Historical syntax (Doom3-like) with collapsing heuristic is still there.
> implement pre-collapsed shader stage, fix #216

- src/engine/renderer/glsl_source/reliefMapping_fp.glsl
- src/engine/renderer/tr_image.cpp
fix heightmap in normalmap detection: heightmap is not anymore a depthmap, fix #233
> fix heightmap in normalmap detection: heightmap is not anymore a depthmap, fix #233

- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_shader.cpp
This PR sits above #230.
The engine usually attempts to autodetect heightmap in normal map, but this keyword is for people who don't trust the engine (no one will blame your for that, see #233).
Some idtech3 derivated engines like OpenJK did it this way. This is not a bad idea.
> implement per-stage normalHeightMap

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/glsl_source/computeLight_fp.glsl
- src/engine/renderer/glsl_source/forwardLighting_fp.glsl
- src/engine/renderer/glsl_source/lightMapping_fp.glsl
- src/engine/renderer/glsl_source/vertexLighting_DBS_entity_fp.glsl
- src/engine/renderer/glsl_source/vertexLighting_DBS_world_fp.glsl
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_shader.cpp
This PR sits above #230.
Enable PBR for lightMapping rendering, add support for physicalMap.
physicalMap expects ORM support (glTF 2.0 standard).
Test map provided by @SomaZ, I edited the shader, converted the assets and build the package the way this branch expects it:
https://dl.illwieckz.net/b/daemon/wip/pbr/map-test-pbr_0%2B20191212-075241%2B9a1edb3.dpk
I removed the swizzle mask code because as long as we don't get expected result on PBR side, we can't know if experiments with swizzles are working or not.
The PR introduces `r_physicalMapping` cvar, which is currently disabled by default (set to `0`) since PBR is not production ready.
Some part of the PBR rendering looks OK, but the lighting is not. Fixing PBR is out of topic. This PR is about being sure assets are piped through the …
> enable PBR for lightMapping rendering and add support for physicalMap

- src/engine/renderer/glsl_source/vertexLighting_DBS_world_fp.glsl
**I FIXED VERTEX LIGHTING**
> _now that's what I call permutation programming_
> -- @Calinou © 2019
**I FIXED VERTEX LIGHTING**
**blame** 4f0a5403621f52fbb2bfdc79f3a3ffdd7cc80304 “Fix vertexlighting world dlights” by @cmf028,
_hiding easter eggs for illwieckz since 20th century_.
**I FIXED VERTEX LIGHTING**
```
\_o< kwaak
kwaak >o_/
_o/* BLAM!
```
**I FIXED VERTEX LIGHTING**
I was just bikeshedding, by renaming accross shaders the variables that contains the same information but named with different names, and then… in my diff tool a line popped as different between `vertexLighting_DBS_world_fp.glsl` and `vertexLighting_DBS_world_fp.glsl`, a line that MUST not be different because it must uses the same boilerplate:
```diff
-	mat3 tangentToWorldMatrix = mat3(var_Tangent.xyz, …
```
> vertexLighting_DBS_world: fix vertex lighting, use xyz instead of xyx

- .appveyor.yml
use Visual Studio 2019 and do 32-bit and 64-bit build
> appveyor: use Visual Studio 2019 and do 32-bit and 64-bit build

- src/common/FileSystem.cpp
- src/common/IPC/CommonSyscalls.h
- src/common/IPC/Primitives.cpp
- src/common/IPC/Primitives.h
- src/engine/botlib/bot_load.cpp
- src/engine/client/cin_ogm.cpp
- src/engine/client/cl_avi.cpp
- src/engine/client/cl_main.cpp
- src/engine/framework/CommonVMServices.cpp
- src/engine/null/null_renderer.cpp
- src/engine/qcommon/files.cpp
- src/engine/qcommon/parse.cpp
- src/engine/qcommon/qcommon.h
- src/engine/qcommon/translation.cpp
- src/engine/renderer/tr_public.h
- src/shared/CommonProxies.cpp
To make WebAssembly migration easier by getting rid of IPC calls which aren't purely sending bytes.
The feature is currently not used anywhere. There is one bit of code in the cgame which depends on PakPath::ReadFile, but that turns out not to be used also...
> Drop support of OS file handles in gamelogic

- src/engine/renderer/glsl_source/liquid_fp.glsl
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_shader.cpp
Renderer code polishing: better way to write things doing the same things.
This is mainly to make easier to implement things since the code base will be less dirty.
Basically, once this is merged, the lone heightmap support is one commit away.
A special effort is made to make boilerplate code looking the same to make easier to fix code across copy-pasted boiler plate.
Note that parallax offset operation is currently only usable with Darkplaces' `dpoffsettmapping` shader keyword. A per-stage keyword will be implemented one day. That's not a regression since this feature is not yet used outside of xonotic parallax testbed, which uses `dpoffsettmapping`.
> renderer code polishing: better way to write code doing the same things

- src/engine/renderer/tr_init.cpp
The glsl code expects this to be defined before compilation.
Not having this a latched cvar means different code is
run when `r_normalMapping` is switched off but `vid_restart`
is not yet called, and when `r_normalMapping` is already off
when vid_restart is called.
The previous code was preventing shader compilation error
to be detected in some scenarii, when `r_normalMapping` was
switched off then switched on before doing `vid_restart`.
> tr_init: make r_normalMapping a latched cvar

- src/engine/renderer/tr_image.cpp
see also #245, 071c7890394f2d05c6c869e87ec696b85b014f3e
- depthmap was a bad design requiring a lot of tricks
- industry uses heightmap that does not require those tricks
- no alpha channel is normalmap means white heightmap means flat heightmap
hence, no trick is required
> tr_image: heightmap is not anymore a depthmap

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/tr_shade.cpp
**gl_shader: load specularmap and physicalmap properly**
fix a bug introduced in 5dd263b9bfa4a65e6bd55e3caacd11cf5f8bc58c
the renaming of a variable was not done everywhere
because of that, the memory video for specularmap was not set,
and by kind of luck the glsl was capturing… the diffuse map instead that was just bound before, so the diffusemap was used as a specular map but in 90% of the case this was not really noticeable (except snow on chasm being so much bright and turret texture being a bit mat.
this mistake was also breaking physical mapping as the diffusemap was also used as physicalmap, see #240
**tr_shade: fix pbr route in vertex world shader, do not use physical map as specular one**
such mistake would be harder to do if vertex entity shader and vertex world shader were only …
> fix materialmaps: properly load specular and physical maps, ref #240

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/glsl_source/liquid_fp.glsl
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shade.cpp
By making this code live again, we make easier to not introduce bugs in this code.
A cvar is available for adventurous people to debug the feature, named `r_liquidMapping`, disabled by default.
The specular code is refactored against the one in `computeLight` library.
> renderer: revive liquid shader (currently disabled because it is broken)

- .travis.yml
attempt to make brew more resilient
by using `BrewFile` mechanism, `brew` does not fail if package is already installed
> travis: attempt to make brew more resilient

- .appveyor.yml
README says the minimum supported VS is VS2017 so it's better to test it
Unvanquished uses `NMake Makefiles` generator so it's better to test it
> appveyor: also test Visual Studio 2017 and investigate NMake generator as we support them

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/glsl_source/lightMapping_fp.glsl
- src/engine/renderer/glsl_source/liquid_fp.glsl
- src/engine/renderer/glsl_source/vertexLighting_DBS_entity_fp.glsl
- src/engine/renderer/glsl_source/vertexLighting_DBS_world_fp.glsl
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
implement `r_showNormalMaps`
`r_showEntityNormals` is dropped, in any way, `vertexLighting_DBS_entity`
and `vertexLighting_DBS_world` glsl are asking for merge
also beautify some code for other `r_show*` cvar
also introduce `r_showMaterialMaps` to debug specular and physical maps.
> debugging: implement r_showNormalMaps and r_showMaterialMaps

- src/engine/renderer/glsl_source/reliefMapping_fp.glsl
I discovered that bug while toying with `r_showNormalMaps` (see #257).
I was like:
Wait,
[![weird normal z reconstruction](https://dl.illwieckz.net/b/daemon/bugs/weird-normal-z-reconstruction/unvanquished_2019-12-31_001650_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/weird-normal-z-reconstruction/unvanquished_2019-12-31_001650_000.jpg)
Wait…
[![weird normal z reconstruction](https://dl.illwieckz.net/b/daemon/bugs/weird-normal-z-reconstruction/unvanquished_2019-12-31_001632_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/weird-normal-z-reconstruction/unvanquished_2019-12-31_001632_000.jpg)
Wait………
[![weird normal z reconstruction](https://dl.illwieckz.net/b/daemon/bugs/weird-normal-z-reconstruction/unvanquished_2019-12-31_001747_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/weird-no …
> renderer: fix normalmap dark blotches

- src/engine/renderer/glsl_source/forwardLighting_fp.glsl
- src/engine/renderer/glsl_source/lightMapping_fp.glsl
- src/engine/renderer/glsl_source/liquid_fp.glsl
- src/engine/renderer/glsl_source/vertexLighting_DBS_entity_fp.glsl
- src/engine/renderer/glsl_source/vertexLighting_DBS_world_fp.glsl
unify the way glsl shaders are written:
- make easier to compare them while looking for bugs
- make factorisation or merge easier
This is the way I fixed #247
This makes easier to merge vertex entity and vertex world shaders as one, and maybe merge the lightmapping one too, one day. This would be good to avoid duplicates of code living their own life with their own bugs.
> polishing: unify the way glsl shaders are written

- src/common/Cvar.h
- src/engine/client/cl_main.cpp
- src/engine/framework/CvarSystem.cpp
- src/engine/framework/CvarSystem.h
- src/engine/qcommon/common.cpp
- src/engine/qcommon/cvar.h
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/sys/sdl_input.cpp
To do before merging: Prevent `The change will take effect after restart` messages from being printed when the cvars are set from command line/configs.
> Implement CVAR_LATCH for new cvars

- src/engine/renderer/gl_shader.h
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shader.cpp
DarkPlaces only supports one alphaFunc operation:
https://gitlab.com/xonotic/darkplaces/blob/324a5329d33ef90df59e6488abce6433d90ac04c/model_shared.c#L1875-1876
Which is GE128:
https://gitlab.com/xonotic/darkplaces/blob/0ea8f691e05ea968bb8940942197fa627966ff99/render.h#L95
Because of that people may silently introduce regressions in their textures
designed for GT0 by compressing them using a lossy picture format like Jpg.
Xonotic texture known to trigger this bug:
models/desertfactory/textures/shaders/grass01
Using GE128 instead would hide Jpeg artifacts while not breaking that much
non-Darkplaces GT0.
No one operation other than GT0 an GE128 was found in whole Xonotic corpus,
so if there is other operations used in third party maps, they were broken
on Darkplaces and will work there. …
> DarkPlaces only supports one alphaFunc operation, GE128

- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shader.cpp
- now useless very ugly `FindMapInStage` is now dropped
- now useless heightmap collapsing code is now dropped
- extra maps loading for non-shader images is now enabled
as DarkPlaces only supports one kind of lightmap blend operation we can blindly collapse lightmap stages in darkplaces pre-collapsed stages.
So, shader parsing and rendering must be faster, and code is cleaner.
Next step is to merge cube Reflection with lightMapping glsl shader, a lot of code will disappear and bugs with it.
> renderer: make dpMaterials collapsed shader from the start, including non-shader images

- src/common/FileSystem.cpp
- src/engine/renderer/tr_shader.cpp
- reimplement latched cvar in new cvar system
- make `r_dpMaterial` a latched cvar
- make `fs_legacypaks` and `fs_maxSymlinkDepth` latched cvars
All I want is to be told to restart when I change those cvars.
Note that:
1. it seems to work
3. @Kangz wrote in ad04f91 that `CVAR_LATCH` is ”not longer supported” and “will be implemented by the proxy” which is not I done (and I don't know what Kangz expected): https://github.com/DaemonEngine/Daemon/blob/ad04f91fb60508d04a894205f728159abf912681/src/engine/framework/CvarSystem.h#L40
So, they may be dragons!
> cvar: make r_dpMaterial, fs_legacypaks and fs_maxSymlinkDepth latched cvars

- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shader.cpp
drop specific `IF_HEIGHTMAP` that was only set with heightmap in normal map alpha channel
but not with loose heightmaps.
also mark `IF_ALPHATEST` as unused.
`IF_NORMALMAP` is used in many places so it has to be kept.
> renderer: make R_UploadImage set IF_ALPHA if alpha channel

- src/common/cm/cm_plane.cpp
With hope to find the cause of #169 I was comparing our code with the one from other engine and my sharp eyes noticed this. This is not the cause of #169, but it may be useful anyway.
Adapted from patch by @zturtleman, he said at that time it was to fix a bug uncovered by Coverity.
See https://github.com/ioquake/ioq3/commit/ee2541efee2eace042303197a1645013d22fcc34
See https://github.com/etlegacy/etlegacy/commit/0fa531a3a958a287d424a6e56198ac14fc3aec5c
@zturtleman for some reason, compared to ioquake3 the etlegacy patch only has 2 fixes on 3, do you know why? Is it an oversight?
> Fix range checks for numBorders in CM_AddFacetBevels

- src/engine/renderer/tr_shader.cpp
While #277 fixed alpha blending of pre-collapsed shaders, I've discovered translucency was still not working on them, while it was working on color maps and diffuse maps. Since a lone diffuse map is processed as a collapsed shader even if it only has one texture, I was surprised to see it working with diffuse map but stopping working as soon I added a specular map or a normal map.
The cause of the bug was a required operation done only when the stage is a diffuse map, so when the next stage was parsed, if it's not a diffuse map, it would change the behavior. Fix is to not test for diffuse map bug for collapsed stage. As said, a lone diffuse map is processed as a collapsed shader any way, so no need to keep an explicit test for it.
[![blended collapsed …
> tr_shader: fix translucency of pre-collapsed shaders

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/glsl_source/lightMapping_vp.glsl
- src/engine/renderer/glsl_source/vertexLighting_DBS_entity_vp.glsl
- src/engine/renderer/glsl_source/vertexLighting_DBS_world_vp.glsl
- src/engine/renderer/tr_shade.cpp
This is the huge rewording work I made when I was looking for the fix described in #277.
Basically I had identified that the bug was bound to the `Render_lightMapping()` function as swaping it with `Render_generic()` or `Render_vertexLighting_DBS_world` made the feature working.
But at this point I didn't know if the issue was in those C++ functions, in GLSL fragment code, or in GLSL vertex code.
At the same time, I wanted to do that rewording because it would benefit for many other work: collapsing the cube reflection, perhaps merge this vertex/lightmapping code one day if it does not clutter the code too much, etc. etc.
Three noticeable changes:
- The `Render_lightMapping()` C++ function was using some global variable directly while other code from `Render_vertexLighting_DBS_world()` …
>  tr_shade: reduce diff noise between vertex entity, vertex world and lightmap code (and more)

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/glsl_source/cameraEffects_fp.glsl
- src/engine/renderer/glsl_source/contrast_fp.glsl
- src/engine/renderer/glsl_source/depthtile1_fp.glsl
- src/engine/renderer/glsl_source/fogGlobal_fp.glsl
- src/engine/renderer/glsl_source/forwardLighting_fp.glsl
- src/engine/renderer/glsl_source/fxaa_fp.glsl
- src/engine/renderer/glsl_source/generic_fp.glsl
- src/engine/renderer/glsl_source/heatHaze_fp.glsl
- src/engine/renderer/glsl_source/lightVolume_omni_fp.glsl
- src/engine/renderer/glsl_source/liquid_fp.glsl
- src/engine/renderer/glsl_source/motionblur_fp.glsl
- src/engine/renderer/glsl_source/portal_fp.glsl
- src/engine/renderer/glsl_source/screen_fp.glsl
- src/engine/renderer/glsl_source/ssao_fp.glsl
- src/engine/renderer/glsl_source/volumetricFog_fp.glsl
Maybe I'm a wizard, then.
I've noticed that if the bug is not in SSAO neither FXAA code, using both makes worst artifacts than only one of those. I also noticed that ticking FXAA on and off (the later not requiring an engine restart), I was seeing the screen being more streched with on than off, in real time.
Here is with  and without fxaa (while ssao is enabled):
[![with ssao, without fxaa](https://dl.illwieckz.net/b/daemon/bugs/boggy-lines/unvanquished_2020-02-09_122221_000.png)](https://dl.illwieckz.net/b/daemon/bugs/boggy-lines/unvanquished_2020-02-09_122221_000.png)
[![with ssao, with fxaa](https://dl.illwieckz.net/b/daemon/bugs/boggy-lines/unvanquished_2020-02-09_122226_000.png)](https://dl.illwieckz.net/b/daemon/bugs/boggy-lines/unvanquished_2020-02-09_122226_000.png)
Those …
> renderer: fix infuriating grey line

- src/engine/renderer/glsl_source/lightMapping_fp.glsl
- src/engine/renderer/glsl_source/vertexLighting_DBS_entity_fp.glsl
- src/engine/renderer/glsl_source/vertexLighting_DBS_world_fp.glsl
It is now possible to do:
```c
textures/hangar28_pk02/stone_sand
{
qer_editorimage   textures/shared_pk02_src/rock01_d
q3map_nonplanar
q3map_shadeangle 170
q3map_lightmapmergable
{
// Primary
diffuseMap      textures/shared_pk02_src/rock01_d
normalMap       textures/shared_pk02_src/rock01_n
specularMap     textures/shared_pk02_src/rock01_s
rgbGen identity
}
{
// Secondary
diffuseMap      textures/shared_pk02_src/sand01_d
normalMap       textures/shared_pk02_src/sand01_n
specularMap     textures/shared_pk02_src/sand01_s
blendFunc blend
alphaGen vertex
}
}
```
Before:
[![flat shader with terrain alpha blending](https://dl.illwieckz.net/b/daemon/wip/pre-collapsed-shaders/unvanquished_2020-01-31_221624_000.jpg)](https://dl.illwieckz.net/b/daemon/wip/pre-collapsed-shaders/unvanquished_2020-01-3 …
> glsl/lightmapping: fix terrain alpha blending for collapsed materials

- src/engine/renderer/gl_shader.cpp
This should fix the underlying issue worked around in #287.
> Preserve exact values when passing floats in GLSL #defines

- src/engine/renderer/tr_shader.cpp
Before (light mapping/vertex lighting):
[![wrong colormap blend](https://dl.illwieckz.net/b/daemon/bugs/wrong-colormap-blend/unvanquished_2020-02-13_101512_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/wrong-colormap-blend/unvanquished_2020-02-13_101512_000.jpg)
[![wrong colormap blend](https://dl.illwieckz.net/b/daemon/bugs/wrong-colormap-blend/unvanquished_2020-02-13_101544_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/wrong-colormap-blend/unvanquished_2020-02-13_101544_000.jpg)
After (light mapping/vertex lighting):
[![correct colormap blend](https://dl.illwieckz.net/b/daemon/bugs/wrong-colormap-blend/unvanquished_2020-02-13_101612_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/wrong-colormap-blend/unvanquished_2020-02-13_101612_000.jpg)
[![correct colormap …
> tr_shader: fix loose texture lighting, fix #289

- src/engine/renderer/tr_shader.cpp
Without this fix, typing `shaderlist` in console would crash the engine.
> renderer: fix shaderlist command to not crash the engine

- src/engine/renderer/glsl_source/liquid_fp.glsl
- src/engine/renderer/glsl_source/vertexLighting_DBS_entity_fp.glsl
- src/engine/renderer/glsl_source/vertexLighting_DBS_world_fp.glsl
- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_light.cpp
- src/engine/renderer/tr_local.h
> The ambient and directional colors are packed into 4 bytes, the packing method assumes that the ambient and directional colors are similar, but that is usually the case.
Patch by @gimhael. Please send much love to him.
Our engine is great again.
> Change Light Grid format to store full light direction vectors, fix #291

- src/engine/client/cl_console.cpp
When we pass arg to /condump command, it should be taken as file
name where command output should be written to.
Now if arg is passed, it is taken as file name. If no arg is passed, file name
is generated by the engine.
Fixes https://github.com/DaemonEngine/Daemon/issues/304
> Write condump output to passed file name

- src/engine/framework/Crypto.cpp
As we encrypt `plain_text` with `key` and write result to `output`,
there is no reason to decrypt `output` and rewrite `plain_text`.
Fixes https://github.com/DaemonEngine/Daemon/issues/305
> Remove unused AES256 decryption

- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shader.cpp
There is no working rendering path without collapsing anyway.
It's almost dead code, we must _not_ use it.
Dropping this makes easier to do refactorize the engine as we can now assume all materials are collapsed materials in all case.
> renderer: drop r_collapseStages, do not allow to not collapse material stages

- src/common/cm/cm_polylib.cpp
Tell the workaround is applied (as a warning) so we don't forget we applied a workaround.
See #169 for details about the issue.
> polylib: workaround MAX_POINTS_ON_WINDING in ChopWindingInPlace, ref #169

- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_main.cpp
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_surface.cpp
- src/engine/renderer/tr_world.cpp
See #302 for explanations about the issue it fixes.
If I color in red what is rendered by `vertexLighting_DBS_entity_fp.glsl`, in green what is rendered by `vertexLighting_DBS_world_fp.glsl` and in blue what is rendered by `lightMapping_fp.glsl`, I get this:
While world vertex lighting is disabled:
[![bsp surface](https://dl.illwieckz.net/b/daemon/bugs/map-entities-as-models/unvanquished_2020-04-11_085656_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/map-entities-as-models/unvanquished_2020-04-11_085656_000.jpg)
While world vertex lighting is enabled:
[![bsp surface](https://dl.illwieckz.net/b/daemon/bugs/map-entities-as-models/unvanquished_2020-04-11_085727_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/map-entities-as-models/unvanquished_2020-04-11_085727_000.jpg)
Everything looks …
> tell a surface belongs to the bsp, properly select the renderer

- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_shader.cpp
Do a refactorization of some renderer thing, move some computation that are done every frame for every surface in `tr_shade.cpp` to be done only once at map load (or when shader is created) in `tr_shader.cpp`.
This makes also easier to implement some features, pull request #307 (_engine-agnostic normal fomat_) relies heavily on this.
Also deletes 150 lines.
> renderer: factorize and move some computation done every frame for every surface in tr_shade to be done only once in tr_shader

- src/engine/qcommon/files.cpp
Map meta lookup: only check for map in packs starting with `map-` prefix, fix #285.
- don't look for map in packs whose name is too small to have a map-prefix
- don't look for map in packs not starting with `map-` prefix
- don't look for map in packs with empty string after `map-` prefix
---
- fix #285 bug
- may speedup map listing
Note: looking for stuff in `meta/` looks to be game-specific.
> map meta lookup: only check for map in packs starting with “map-” prefix, fix #285

- src/engine/renderer/glsl_source/reliefMapping_fp.glsl
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_shader.cpp
Introduce engine-agnostic `normalFormat` material stage keyword.
There is already a `normalScale` keyword which allows to revert channel by using a negative value, but this is not a way to describe the _format_ of the file that is loaded. So, people would have to use a negative `normalScale` Y value in their `.shader` file if the normal map file is stored in DirectX way and the engine is computing normal maps the OpenGL way, but a positive Y `normalScale` value if file format and engine format matches.
By introducing the `normalFormat` stage keyword, artist can describe the normal map file format and don't mind about what the engine does. It also means the engine may switch its internal format without having to mind anything, the coder implementing another normal format would know how to …
> renderer/tr_shader: introduce engine-agnostic normalFormat material stage keyword

- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_shade.cpp
The cubemap feature and reflective specular thing is not working, anyway, this PR makes sure the engine does not crash when the cubemaps are generated:
1. do not attempt to generate cubemaps (`buildcubemaps` command) when no map is loaded (for example in main menu);
2. always load a `whiteCubeImage` when cubemap pointers are null and do more tests for this.
Note that the renderer attempts to use cubemaps while they are built so maybe the extra tests for null pointers are only required until they all are build successfully, but I have no proof there would not be a bug somewhere trying to bind `nullptr` as image in some other scenario.
> do not crash the engine when using cubemaps

- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_image_crn.cpp
- src/engine/renderer/tr_image_dds.cpp
- src/engine/renderer/tr_image_jpg.cpp
- src/engine/renderer/tr_image_ktx.cpp
- src/engine/renderer/tr_image_png.cpp
- src/engine/renderer/tr_image_tga.cpp
- src/engine/renderer/tr_image_webp.cpp
* Handle case for non-array cubemap textures.
* Fix out of buffer read for KTX numberOfMipmapLevels.
* Better checks for KTX structure errors.
* Cleanup WebP image reader.
* Common image readers log format like `<image type> image '<image path>' <log message>`.
Fixes https://github.com/DaemonEngine/Daemon/issues/244
@illwieckz could you please check the patch?
> Fix KTX file format support and unify image reader logs

- src/common/IPC/CommonSyscalls.h
- src/engine/client/cg_api.h
- src/engine/client/cg_msgdef.h
- src/engine/client/cl_cgame.cpp
- src/engine/client/client.h
- src/engine/qcommon/msg.cpp
- src/engine/qcommon/q_shared.h
- src/engine/qcommon/qcommon.h
- src/engine/server/server.h
- src/engine/server/sg_msgdef.h
- src/engine/server/sv_ccmds.cpp
- src/engine/server/sv_main.cpp
- src/engine/server/sv_sgame.cpp
- src/engine/server/sv_snapshot.cpp
- src/shared/CommonProxies.cpp
- src/shared/VMMain.h
- src/shared/client/cg_api.cpp
- src/shared/server/sg_api.cpp
A lot of hacks! There are a few fields referenced in the engine code, so I'm keeping those hard-coded in for now. I have only implemented loading the table from sgame so far, not from cgame (though it's matter of trivial copy and paste), so it only works with a local server.
The point is to be able to change the definition of playerState_t without rebuilding the engine.  If we like this, there's another table for entityState_t that it can also be done for.
> Gamelogic-configurable netcode for playerState_t

- src/engine/sys/sdl_glimp.cpp
Abort on missing required GL extension, fix #348
I would appreciate comments on error message wording.
> Abort on missing required GL extension, fix #348

- src/engine/sys/sdl_glimp.cpp
For each format attempt, the renderer creates a window and try to create a context using this window.
But anytime a context cannot be created, the next one is tried without destroying the previous window first, or reusing it.
This is an attempt to fix #349.
> Reuse window when attempting to create a context, fix #349

- src/engine/renderer/gl_shader.cpp
Print shader name and macro at build time, may help to trouble shoot various things.
That debug code prints something like that in console:
```
Debug: building shadowFill shader permutation with macro: none
Debug: building shadowFill shader permutation with macro: USE_VERTEX_SKINNING
Debug: building shadowFill shader permutation with macro: USE_VERTEX_ANIMATION
Debug: building shadowFill shader permutation with macro: LIGHT_DIRECTIONAL
Debug: building shadowFill shader permutation with macro: USE_VERTEX_SKINNING LIGHT_DIRECTIONAL
Debug: building shadowFill shader permutation with macro: USE_VERTEX_ANIMATION LIGHT_DIRECTIONAL
```
> renderer: print shader and macro names at glsl build time

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/glsl_source/depthToColor_fp.glsl
- src/engine/renderer/glsl_source/volumetricFog_fp.glsl
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_types.h
- src/engine/sys/sdl_glimp.cpp
See #352, the code was reading GL version to select GL 2 or GL 3 features, but was looking hardcoded string (related to 10 years old hardware and software) to activate some optimizations for pre GL3 hardware.
The code already reads GL version and we can assume an hardware having a driver supporting GL3 is a GL3 hardware.
On a side note, we currently know only one GL 2.1 configuration that works with Unvanquished: the GMA X3100 / GM964 (Core 2 Duo L7500) on Linux. This GPU driver does not support GL 2.1 on Windows, other tested GL 2.1 hardware are either getting serious issues (see #344) or just lacks required extension (see #348). Even the GMA X3100 on Linux is not able to perform 30fps with 800x600 resolution and 1:4 texture size. Then, we can assume everything is GL3 instead of the …
> Cleanup GPU detection code, fix #352

- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_shader.cpp
Hardware that hangs with full size texture and full size lightmap does not hang with `1:4` texture and full size lightmap. While downscaling textures may give a 10% performance boost on low end old hardware, not downscaling lightmaps does not have any performance impact on the same hardware.
The fact lightmaps are downscaled looks like a bug: some lightmap format uses `IF_NOPICMIP` some does not. The code already assumes some lightmap have to not be downscaled.
So, this patch prevents all lightmaps to be downscaled, there is no alternative.
It seems there is no usage on earth to downscale the lightmap, and engine has still an option to use lightgrid to not read the lightmap (but GLSL code seems to be more complex for lightgrid, hence it is likely to produce larger shaders and run slower …
> Do not scale down lightmaps, fix #347

- src/engine/client/key_binding.cpp
Binds: allow to set modcase commands without / like everywhere else, vstr users can use `vstr`,
also make the code simpler, nowhere else the code requires ending `\n`.
Rogue commit stolen from dead #330.
> binds: allow to set modcase commands without / like everywhere else, vstr users can use vstr

- src/engine/renderer/tr_shader.cpp
Disable useless heightMapInNormalMap if both normal and relief mapping are disabled, fix #376.
Before:
[![wrong normal format detection disables shader](https://dl.illwieckz.net/b/daemon/bugs/wrong-normal-format-detection-disables-shader/unvanquished_2020-09-29_010422_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/wrong-normal-format-detection-disables-shader/unvanquished_2020-09-29_010422_000.jpg)
After:
[![wrong normal format detection disables shader](https://dl.illwieckz.net/b/daemon/bugs/wrong-normal-format-detection-disables-shader/unvanquished_2020-09-30_234455_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/wrong-normal-format-detection-disables-shader/unvanquished_2020-09-30_234455_000.jpg)
This bug is known to affect Nvidia Curie (Geforce 6000/7000 series) with driver Nvidia …
> disable useless heightMapInNormalMap if both normal and relief mapping are disabled, also fix #376

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/tr_shade.cpp
This is just 8ba2505033014de931b5a00525b6b04b0b6d0e08 rewritten in a better way: no need to pop from a list something that is never added to the list to begin with.
Also maybe the `bloom` string for bloom was wrong since the shader is named `screen`.
> renderer: rewrite 8ba2505 in a better way, do not build unused GLSL shaders

- src/engine/sys/sdl_glimp.cpp
This may also match Quadro cards and not apply the workaround to all Nvidia products.
> sys/sdl_glimp: rewrite the workaround for Nvidia GT218 on 340 driver, fix #368

- src/engine/renderer/tr_shader.cpp
With this PR,
- `normalMap` material keyword loads a file and assume it's a normal map without height map in alpha channel (even if the engine believes there is an alpha channel because of a format being wrongly guessed on missing GL extension, see #375).
- `normalHeightMap` material keyword loads a file it's a normal map with an height map in alpha channel.
This code also introduces an internal `ParseNormalMapDetectHeightMap` function that attempts to detect an alpha channel and declare it's an heightmap. There is no material keyword for that and it must not be implemented as a keyword.
This internal function is only purposed to be used by compatibility code like the Darkplaces compatibility mode. Darkplaces-based games being known to not use formats that would break on detection, it's …
> tr_shader: do not detect heightmap in normalmap alpha channel, unless asked to, fix #375

- src/engine/renderer/tr_image.cpp
Some improvements to help debugging:
- add debug log for unknown formats when listing images,
- add some code names for RGTC variant when listing images,
- add code name for compressed RGB when listing images.
Note that I made up myself the code names.
This is the way I did them:
- since `a` in `DXT1a` is for `alpha` channel, I made `RGTC1r` and `RGTC2rg` with `r` and `g` for `red` and `green`,
- since `F` in `RG32F` is for `float` type, I made `RGTC1Sr` and `RGTC2Srg` with `S` for `signed`,
- since `C` in `RGTC` if for `compression`, I made `RGBAC` with `C` for `compressed`.
I made this to investigate #375 and #376.
Before this PR:
```
209:  128  128  yes   2D   ????     s.rept  t.rept   textures/shared_pk02_src/floor01_n
```
With debug logs added:
```
Debug: Undocumented image format …
```
> tr_image: add debug log for undocumented formats and add more code names when listing images

- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_fbo.cpp
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_vbo.cpp
Do not call `RB_RenderPostDepth` when the tiled renderer is disabled. It looks like this function added in 0bb3550ce16ab7b165a88ebb365edf6b2837d1f5 is only used when the tiled renderer is enabled.
The light tile code is known to be too large for the tiny ALU of the Radeon R300 GPU. See #344.
With this simple modification, the R300s GPU like the X300, X550HM and X1050 become able to run the game.
Also rename `RB_RenderPostDepth` to `RB_RenderPostDepthLightTile` to make this characteristic more obvious when reading the code.
Also disable more light tile code when the tiled renderer is disabled, for better performance in that case.
With that PR merged, we know no one OpenGL 2.1+ hardware that is not able to render Unvanquished.
I would be happy to get a comment by @gimhael since I touched …
> Do not use lightTile code when tiled renderer is disabled, fix rendering on Radeon R300 with tiny ALU, fix #344

- src/engine/sys/sdl_glimp.cpp
Attempt to fill window with black at creation time, to prevent this (and fix #373):
[![empty window](https://dl.illwieckz.net/b/daemon/bugs/empty-window/20200723-231745-000.unvanquished-empty-window.png)](https://dl.illwieckz.net/b/daemon/bugs/empty-window/20200723-231745-000.unvanquished-empty-window.png)
It works but I know nothing about OpenGL and SDL, so maybe I'm introducing a time bomb…
@gimhael or @Kangz, is it OK to do that?
> Fill window with dark grey at creation time, fix #373

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_fbo.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_main.cpp
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_vbo.cpp
With this, positive value for `r_dynamicLight ` would enable the tiled renderer, which is the only verified one for dynamic lights.
- This ensure people already having this value set to 1 will get the best we have on 0.52.0 release,
- This ensure people setting this value to 1 will not get what they don't expect.
In the future, we may do “if value equals to 2 then set 1”, but for the moment we can live with any positive value to enable the tiled renderer (and it allows 0.51 and 0.52 cohabitation).
At some point in the future we would want to nuke the forward renderer. In fact it already started to rot: the dynamic lighting seems to be broken. I'm a bit concerned about such huge code deletion since some features are not yet ported (things like real time shadows which is really buggy …
> deprecate forward renderer, requires r_dynamicLight to be -1

- src/engine/renderer/tr_cmds.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
Also remove duplicated code for printing names of GL errors.
> Make GL error check non-fatal in SMP mode

- cmake/DaemonFlags.cmake
It is redundant since we have the executable's directory in the rpath
also, and we copy the dependencies to this directory in the build.
Fixes #387.
> Remove DEPS_DIR from Mac rpath

- src/engine/framework/CvarSystem.cpp
- src/engine/null/null_renderer.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_types.h
- src/engine/sys/sdl_glimp.cpp
- src/engine/sys/sdl_input.cpp
This makes it possible to toggle r_fullscreen more than once without getting stuck.
Still want to look at a couple other things:
- Delete the code that makes (undesirable) changes to window cvars in response to SDL window resize events
- I noticed that toggling r_noBorder repeatedly causes a growing black space in the window.
> Fix fullscreen toggling bug (#365)

- src/engine/renderer/glsl_source/motionblur_fp.glsl
Fixes https://github.com/DaemonEngine/Daemon/issues/34.
The cleaner diff is basically
```patch
-discard;
-return;
+outputColor = texture2D( u_ColorMap, st );
```
> fix motion blur bug

- src/engine/sys/sdl_input.cpp
Fixes https://github.com/DaemonEngine/Daemon/issues/408 and https://github.com/Unvanquished/Unvanquished/issues/1136.
Could fix https://github.com/DaemonEngine/Daemon/issues/365 and https://github.com/DaemonEngine/Daemon/issues/234.
If it doesn't, it will at least give an easy workaround: switch away from and back to the window.
> Detect that window isn't minimized more often

- src/engine/renderer/tr_shade.cpp
Some really minor change.
1. avoid some useless texture OpenGL bind for unused feature (note: I left intact the forward renderer and other less tested code),
2. a tiny rewriting to move a test outside of a function to inside the function to be consistent with the way other function do.
> avoid some useless texture OpenGL bind for unused feature

- CMakeLists.txt
- cmake/toolchain-pnacl.cmake
This makes the toolchain automatically find python2 installation even on
systems with /usr/bin/python that's python3.
The FindPython2 module was intrudoced in CMake 3.12 so Daemon's CMake
requirement is bump to that version. Note that it is an older version
than what's in Debian stable and oldstable's backports.
Fixes #411
> toolchain-pnacl: Use the FindPython2 module

- .travis.yml
- CMakeLists.txt
- azure-pipelines.yml
- src/common/Serialize.h
- src/engine/client/cl_console.cpp
- src/engine/qcommon/common.cpp
- src/engine/qcommon/msg.cpp
- src/engine/renderer/tr_local.h
Completely removes the Travis Mac build which stopped working, and adds an Azure Pipelines-based one. Plus some warning fixes so it will run with -Werror.
Unlike Travis, this service lets you download the binaries it builds, so it is also possible to use it for releasing. This what I used to build the Mac version of the updater.
We might consider moving the Linux build to this also (it supports all 3 of our OSes), since it seems to have much shorter queueing times than Travis now.
Ping me if you want to be invited to the "UnvanquishedDevelopment" organization on the Azure Pipelines site.
> Azure Pipelines continuous build for Mac

- src/engine/renderer/tr_shader.cpp
To not delay 0.52 more, I propose to just disable relief mapping on grids for now, see #334.
> tr_shader: workaround relief not applied on alpha mask by disabling relief, ref #334

- src/engine/qcommon/common.cpp
common: misnamed `common.framerate.fixed` cvar is about frametime
> common: misnamed common.framerate.fixed cvar is about frametime

- src/common/FileSystem.h
- src/engine/client/cl_cgame.cpp
- src/engine/framework/CommonVMServices.cpp
- src/engine/framework/CommonVMServices.h
- src/engine/qcommon/files.cpp
- src/engine/qcommon/qcommon.h
- src/engine/server/sv_sgame.cpp
In my tests the cgame and sgame usually had 1 open file each.
> Close file handles of dead VMs

- src.cmake
- src/engine/renderer/InternalImage.cpp
- src/engine/renderer/InternalImage.h
- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shader.cpp
I imported `imageMinDimension`/`imageMaxDimension`, `r_imageMinDimension`/`r_imageMaxDimension` from #394.
What's interesting for the release is `r_imageMaxDimension` (engine cvar) and `imageMinDimension` (material keyword).
> introduce r_imageMaxDimension (from #394)

- src/engine/renderer/tr_init.cpp
GL Clear is expected to paint the screen with an arbitrary color before painting anything else, and that action is not expected to slow down things as far as I know. This is used make sure the non-drawn area are filled with something and prevent garbage do be displayed instead.
Enabling GL Clear by default has two benefits:
- prevent legacy maps with small void surfaces to be rendered without glitching. Arachnid2 is one of them. Given the large amount of Tremulous map existing out there and people want to port them, clearing is the best we can do to support those legacy maps with glitchy part without modification. Also, because it is a `cheat` cvar, if it's disabled by default players are not able to hide the void when playing on regular games. Fun stuff is that people playing to …
> renderer: enable GL clear by default

- CMakeLists.txt
I noticed the deps download is initiated with http then redirected to https, it's better to request https directly.
> cmake: download deps with https

- src/engine/renderer/tr_shade.cpp
The forwared renderer is deprecated and now uses -1 value.
The tiled renderer is meant to use 1 value one day, but both 1 and 2
can be usable for tiled renderer in 0.52.0, in order to keep
compatibility with 0.51.0 config files when testing releases candidates.
Those test rewrite were missing in be7229a.
See https://github.com/DaemonEngine/Daemon/issues/386#issuecomment-823196130
The issue was spotted thanks to https://github.com/DaemonEngine/Daemon/issues/386#issuecomment-823196130
I don't expect this to fix #386 if people experiencing problems with Nvidia used `r_dynamicLight` `2`.
> renderer: tiled renderer is r_dynamicLight > 0, see be7229a

- src/engine/qcommon/SurfaceFlags.h
Restore `mover` content flag to the value used in Tremulous, was probably mistakenly set to Wolf:ET one when merging Wolf:ET code.
This flag seems to be set by the engine to be used by the game, there is no mention of it either in map compiler source code, neither in the `custinfoparms.txt` the map compiler reads, so the `.bsp` file is not expected to carry it.
As long as you recompile the game code with this revision of the engine, there is no regression. Even movers in Wolf:ET maps would work as expected if Wolf:ET code was built and run with this engine.
Restoring this flag to the Quake3/Tremulous value is required to avoid collision with the `nobuild` content flag that is (currently) using the same value. The `nobuild` content flag is set by the map compiler (defined in …
> restore mover content flag like ioq3/tremulous, avoid collision with nobuild content flag

- external_deps/build.sh
Fixes #445.
Regardless of the build type, you can enable spam by setting `ALSOFT_LOGLEVEL=2` in the environment, or disable it by `ALSOFT_LOGLEVEL=1`.
> Stifle warning spam (with self-built OpenAL)

- src/common/FileSystem.cpp
While the “symlink in dpk file system” feature was at first implemented to load Xonotic assets to use them as test bed for renderer features like relief mapping, I now believe we have one very good usage for this: third-party compatibility packages, like the [`res-tremulous`](https://github.com/InterstellarOasis/res-tremulous_src.dpkdir) one.
When I first distributed `res-tremulous` to be used by legacy maps being ported from Tremulous, I did a huge deduplication, this plus ad-hoc compression, reduced the `res-tremulous` package to only `13M`.
One thing is that the zip format stores each file independently, so we can't rely on the archive compression to deduplicate files.
Along that manual deduplication I did, I provided a [compatibility `.shader` …
> filesystem: enable 1 symlink depth for future res-tremulous community dpk

- CMakeLists.txt
- src/engine/framework/System.cpp
- src/engine/sys/manifests/dpi-aware.manifest
- src/engine/sys/manifests/supported-os.manifest
Include manifests for:
* OS support info to signal Windows our app supports it as is without quirks.
* DPI aware v.2 (with v.1 fallback) scaling to disallow Windows to scale our window.
> [windows] Include OS / DPI Aware manifests

- src/engine/qcommon/translation.cpp
The bug was introduced about 1 year ago (859709d6c46cbdcad001b65fabae885821cb5fd3), so it is a regression in 0.52.
> Handle null locale country

- src/common/Compiler.h
- src/engine/client/cl_main.cpp
- src/engine/qcommon/common.cpp
- src/engine/qcommon/q_shared.h
- src/engine/qcommon/qcommon.h
Allows compiler to infer pointer usage and optimize better.
> [client,common,qcommon] Mark allocators with allocator / malloc like

- src/engine/sys/sdl_glimp.cpp
Not having a GLX context is not a bug: wayland uses EGL for example.
This is inspired by:
https://github.com/endless-sky/endless-sky/pull/5230/commits/5f5fb100422685f2eed443bb5bf7f5dbadef2aa9
This may help in https://github.com/DaemonEngine/Daemon/issues/474.
With this commit, the game will start on wayland, see https://github.com/DaemonEngine/Daemon/issues/482.
> Don't fail on non-GLX backends

- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_model_iqm.cpp
- src/engine/renderer/tr_model_md5.cpp
- src/engine/renderer/tr_surface.cpp
I was looking to see if there was a way to reduce engine side the impact of some model slowing down a lot the game on some older hardware (see https://github.com/Unvanquished/Unvanquished/issues/1207) so I incrementally did minor changes over minor changes to make it easier to read, understandable and refactorisable and in the end that was what I got.
Now I know why the performance drops so much, and any improvement to this code can't do magic. Anyway, this code now looks better and may even save some cycles (or rely less on compiler optimization). Also, two loops were rewritten at once in a way the code only iterate once for both.
I reported such changes to the MD5 model code and then it gave me some example to clean-up the IQM code a bit more in return.
There is two changes I have …
> some revamp on IQM and MD5 model code

- src/engine/renderer/tr_image.cpp
clang 12 was complaining:
```c
Daemon/src/engine/renderer/tr_image.cpp:2078:39: warning: loop variable 'format' creates a copy from type 'const multifileCubeMapFormat_t' [-Wrange-loop-construct]
for ( const multifileCubeMapFormat_t format : multifileCubeMapFormats )
^
Daemon/src/engine/renderer/tr_image.cpp:2078:8: note: use reference type 'const multifileCubeMapFormat_t &' to prevent copying
for ( const multifileCubeMapFormat_t format : multifileCubeMapFormats )
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
&
```
I'm not sure this is the way to do it, I'm surprised to not have to modify other lines of code to silent the warning.
> renderer/tr_image: prevents copying when looping cubemap formats

- src/common/FileSystem.cpp
FileSystem: do not look for DEPS file in pk3dir.
The code already ignores DEPS file in pk3 archives.
I found this by attempting to implement a way for partial dpk and dpkdir to set a list of deleted files to not load from deps.
> FileSystem: do not look for DEPS file in pk3dir

- src/engine/renderer/tr_world.cpp
This value, according to src/engine/renderer/tr_bsp.cpp, means that the "location is in the void". So it seems appropriate not to try to render it.
> Avoid undefined behaviour when area is set to -1

- src/engine/audio/Audio.cpp
- src/engine/audio/Sound.cpp
- src/engine/client/cl_main.cpp
- src/engine/null/NullAudio.cpp
Do not abort on missing or busy sound device.
fix https://github.com/Unvanquished/Unvanquished/issues/1031
There was already a lot of
```c++
if (not initialized) {
return;
}
```
I added a bunch of others, and turned the `Sys:Error` calls into `Log::Warn` ones.
> audio: do not abort on missing or busy sound device

- src/engine/qcommon/msg.cpp
Replaces a hack to get offsets by the built-in C "offsetof". This reduces UBsan's noise and makes things more readable.
> use std::offsetof

- src/engine/renderer/tr_shade.cpp
liquidMapping is not functional and not used yet, but we need to not
crash when loading liquidMap test assets while liquidMapping is disabled.
When liquidMapping is disabled this patch just display the liquidMap as
a diffuseMap with a white opaque texture and the liquidMap as normalMap.
No playable map uses liquidMap yet and liquidMap syntax is likely to be
entirely redone in the future so I see no need to implement more complex
workaround (like adding translucency).
> tr_shade: workaround to not crash on liquidMap when liquidMapping is disabled

- src/common/FileSystem.cpp
- src/common/IPC/CommonSyscalls.h
- src/engine/framework/CommonVMServices.cpp
- src/engine/qcommon/files.cpp
- src/engine/qcommon/q_shared.h
- src/engine/qcommon/qcommon.h
- src/shared/CommonProxies.cpp
Used to make it possible to have files which can be in either of homepath or pakpath, but with homepath taking predence.
> Add syscalls for reading only one of homepath/pakpath

- src/common/FileSystem.cpp
- src/common/FileSystem.h
- src/common/System.cpp
- src/common/System.h
- src/engine/client/ClientApplication.cpp
- src/engine/client/cl_main.cpp
- src/engine/framework/LogSystem.cpp
- src/engine/framework/LogSystem.h
- src/engine/framework/System.cpp
- src/engine/qcommon/common.cpp
- src/engine/qcommon/files.cpp
- src/engine/qcommon/qcommon.h
- src/engine/server/ServerApplication.cpp
- src/engine/server/sv_init.cpp
- src/engine/sys/con_curses.cpp
- src/shared/VMMain.cpp
Shut down the engine quickly instead of doing nonsense like reloading the filesystem before exit. If you want to do all that stuff for debugging purposes (e.g. to detect memory leaks) you can use the `common.pedanticShutdown` cvar.
Things I identified as important shutdown tasks which shouldn't be skipped:
- Flush files
- Terminate gamelogic VMs
- Send "dead heartbeat" to master server (not done because it might block on DNS)
- Restore terminal state
- Close the single-instance lock file
- SDL_Quit to clean up full screen stuff
- For clients, send disconnection packet to the server
- Delete temp files from downloads (not implemented)
- Remove temp files from FS_WRITE_VIA_TEMPORARY
- Finish demo recording
- Finish video recording
Also do proper shutdown when clicking X on the Windows …
> Fast engine shutdown

- src/common/Log.cpp
- src/common/Log.h
`logs.logLevel` is too long and repetitive :)
> logs.logLevel -> logs.level in cvar names

- src/common/IPC/Primitives.cpp
On MacOS, dlclose has no effect if the shared library contains a
thread_local variable. Get rid of an instance of thread_local
in gamelogic DLLs to fix this. It is important for gamelogic
DLLs to be unloaded and reloaded so that memory is freed and
variables reinitialized.
> Fix DLL unloading on MacOS

- src/common/FileSystem.cpp
- src/common/FileSystem.h
My recent filesystem changes on the Unvanquished - in particular, using PakPath::ReadFile more - triggered this bug where ReadFile doesn't work on paks loaded after the first frame.
> PakPath::ReadFile - don't rely on FileExists

- src/engine/client/cl_main.cpp
- src/engine/framework/System.cpp
- src/engine/renderer/tr_cmds.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_public.h
- src/engine/renderer/tr_types.h
- src/engine/sys/sdl_glimp.cpp
_Update:_ 2022-02-16
~~This PR is low priority (existing code works).~~ This fix many bugs, this is now highly wanted.
The effort was initially motivated by #477 to provide a new GL selection code that first detects the higher GL version supported before trying any custom configuration, and if no custom configuration (or it fails), loads the higher GL version possible. This way `/gfxinfo` displays the higher GL supported by the card (Nvidia proprietary driver rewrites the GL and GLSL version strings with currently requested GL version).
With default configuration, the code only tries OpenGL 3.2 core and 2.1 compatibility for success (and all versions below on error to provide user a meaningful error message). By setting `r_glExtendedValidation` to `1`, an user can also detect (at the cost …
> renderer/glimp: new GL detection and selection code

- src/engine/renderer/tr_shade.cpp
A minor rewrite of a useless convolution I just spotted while looking at the code.
> renderer/tr_shade: simplify tests in Render_depthFill()

- src/common/FileSystem.cpp
- src/common/FileSystem.h
- src/common/IPC/CommonSyscalls.h
- src/engine/client/cg_api.h
- src/engine/framework/CommonVMServices.cpp
- src/engine/qcommon/files.cpp
- src/engine/qcommon/qcommon.h
- src/engine/server/sv_ccmds.cpp
- src/shared/CommonProxies.cpp
Implement the restriction that a map named $NAME must be in a pak named map-$NAME. Fixes #557.
This allows us to avoid a big filesystem hit of loading all map paks upon loading a map or listing maps.
Companion: https://github.com/Unvanquished/Unvanquished/pull/1782
> Map paks must be named map-<mapname>

- src/engine/renderer/tr_shade.cpp
tr_shade: also load gl_forwardLightingShader_projXYZ when dynamic shadows are enabled to prevent a crash
Dynamic shadows are believed to be part of the old forward renderer,
and they are known to be very buggy.
Anyway commit message of a09f03bc8e775d83ac5e057593eff4e88cdea7eb
seems to imply they may be usable with tiled renderer as well:
> Use conventional shadow mapping code for inverse lights.
> This re-enables shadows for players in the tiled renderer.
After this commit no dynamic shadow is rendered but at least there
is no crash when setting to cg_shadows a value greater than 1 to
enable dynamic shadowing.
Note: for some reasons while the cvar is named r_shadows on renderer code,
the cvar is named cg_shadows in game console, probably because of some
quake3 legacy.
> Also load gl_forwardLightingShader_projXYZ when dynamic shadows are enabled to prevent a crash

- CMakeLists.txt
The `IMPLICIT_DEPENDS` feature is currently unsupported with Ninja.
> Note that the IMPLICIT_DEPENDS option is currently supported only for Makefile generators and will be ignored by other generators.
> -- https://cmake.org/cmake/help/latest/command/add_custom_command.html
Supersedes:
- #603
> Turn off precompiled headers with Ninja generator

- src/engine/renderer/tr_backend.cpp
Reflection mapping isn't working yet, but those two patches avoid two crashes related to reflection mapping code.
> Avoid some crashes in cubemap code (reflection mapping).

- src/engine/sys/sdl_input.cpp
SDL_Init doesn't necessarily return -1, but any negative value on error.
There was a bit more changes initially, but illwieckz fixed the other issues :eyes:
> Improve SDL joystick error handling and error reporting

- src/engine/renderer/tr_init.cpp
This makes possible for the user to quickly reach the game main menu without building all GLSL shaders and set a low graphics preset before joining a game and loading a map.
Doing so prevents building unwanted or unsupported GLSL shaders on slow and/or old hardware and drastically reduce first startup time.
On Unvanquished side, the UI was already modified to display a message to the user to make him wait for the GLSL shaders being compiled at map load:
- https://github.com/Unvanquished/Unvanquished/pull/1470
> Delay GLSL shader build until first map load.

- src/engine/framework/System.cpp
Add cvar to shutdown on drop, fix #487.
By setting `common.shutdownOnDrop` to `on`, the engine will quit when the game quit. This is useful to get the engine quit after having timed a demo for benchmarking purpose.
See:
- #487
- https://github.com/Unvanquished/Unvanquished/issues/1440#issuecomment-864646180
> Add cvar to shutdown on drop, fix #487

- src/engine/client/cl_main.cpp
Name demo file as date_time_host_map
instead of host_map_date_time.
This make it easy to sort by date in file browser.
Also, better use _ as field separator in all cases.
> cl_main: rename demo file

- src/engine/qcommon/common.cpp
That cvar has very specific usage and we may want to prevent it to be stored. People making use of it know what they do, and they're usually scripting it already.
Also timedemo being enabled has side effects when not playing demo (like defeating the fps cap), though, the cvar being cheat prevents this to happen in regular games.
This kind of cvar being stored can bite in the back at some unexpected moment.
> common: make demo.timedemo cvar temporary

- src/engine/framework/System.cpp
The socket listener thread was being started before the Breakpad
initialization which forks. Unusually, the exec() is done in the parent
process. As a result any non-main threads are killed by the forking.
Fixes #78.
> Fix command forwarding on Linux + Breakpad

- CMakeLists.txt
See:
- #600
> The "Fixed event pump starvation" that improves it is part of SDL2.20, and the "Fixed mouse warping" commit is part of SDL2.16. Meaning that every version of SDL2.x where 16≤x≤20 is known bad.
> -- @necessarily-equal
> cmake: print a warning if SDL version is between 2.16 and 2.20 included, ref #600

- CMakeLists.txt
Disable geoip by default, remove it as release build requirement, fix #492
After this commit support for GeoIP will not be built by default, meaning libgeoip will not be a requirement for release builds anymore.
Since libgeoip will not be a release build requirement, we would be able to remove libgeoip from prebuilt dependencies.
The geoip code is still there and people can still build their own server with geoip support enabled, but that's up to them to decide if it's good or not and it's up to them to deal with the questions regarding to the geoip database.
> disable geoip by default, remove it as release build requirement, fix #492

- CMakeLists.txt
- fix version, see https://github.com/DaemonEngine/Daemon/issues/600#issuecomment-1107661519
- fix previously merged #621 which was in fact breaking build if `sdl2-config.cmake` was available but the workspace was empty brand new, it looks like `find_package(SDL2 CONFIG)` still requires `find_package(SDL2)`.
- this code may be removed later in favor of #624 but the priority is to make `master` build again.
> Rewrite SDL warning to fix build

- src/engine/sys/sdl_input.cpp
For more information, see the discussion in https://github.com/libsdl-org/SDL/issues/5569
Fixes https://github.com/DaemonEngine/Daemon/issues/600
> Only center the mouse if we get a mouse event with relative motion

- CMakeLists.txt
- README.md
- external_deps/build.sh
- src/engine/qcommon/net_ip.cpp
- src/engine/qcommon/qcommon.h
- src/engine/server/sv_client.cpp
Fixes #492. I noticed that since the last GeoIP release was in 2018, it is either not working at all, or we are using an ancient database (since no one actually knows how to configure an external database). After realizing this it seems better to nuke it right away instead of after a release.
> Nuke GeoIP

- src/engine/qcommon/common.cpp
A regression in 443bf08c would cause the FPS to be unlimited when
unfocused/minimized with default settings.
> Use normal max FPS without unfocused/minimized set

- CMakeLists.txt
- src/engine/sys/sdl_input.cpp
Closes https://github.com/DaemonEngine/Daemon/issues/600. Hopefully for good this time.
> Correct relative mouse input handling

- src/engine/qcommon/q_shared.cpp
This fixes a crash in entityList in debugMode because Com_EntityTypeName
returns nullptr if the enum is not found and is less than ET_EVENT.
> beacons: Register Beacons as a type in Com_EntityTypeName.

- src/engine/client/ClientApplication.cpp
You usually want to see the error instead of a broken frozen window.
Note I couldn't test it because my version of SDL isn't compiled with it or something. In theory it shouldn't blow up, but this change needs someone to test it.
> Keep error window in front of daemon window on error

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/tr_shade.cpp
Also show a useful error message when crashing from this class of bug (using an "unused" permutation).
> Fix crash with r_vertexLighting

- src/engine/sys/sdl_glimp.cpp
Window resolution can also change without calling `vid_restart`: it happens when the window failed to be created and a lower resolution is tried instead.
This replaces:
- https://github.com/DaemonEngine/Daemon/pull/644
This is a fixup for:
- https://github.com/DaemonEngine/Daemon/pull/478
Not recreating the window when the fallback resolution is tried because the context creation failed was a regression.
> sdl_glimp: also recreate window on resolution change

- src/engine/renderer/glsl_source/computeLight_fp.glsl
- src/engine/renderer/tr_init.cpp
This happens due to a NaN in the specular mapping calculation.
Fixes #471.
> Fix dark patches from dynamic lights

- src/engine/renderer/glsl_source/computeLight_fp.glsl
This is low priority but I just stumbled upon it while reading the code.
Note that it has a computational change as the `NdotL` compute that was only clamped for physical mapping is now clamped in all cases. But I have read in some place that `NdotL` is expected to be `0` for `0°` angle and `1` for `90°` and maybe this value should never go beyond.
I have seen no regression with both light mapping and dynamic lighting (this code is used by both), I tested lighting on basic materials, specular materials and physical materials.
Since it modifies a code that is known to be affected by a bug (see #471), it may be interesting for affected people to test this code to see if by pure luck that makes a difference, I doubt though.
> Factorize some code between basic, specular and physical lighting

- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shader.cpp
Remove sunShader and flareShader. They are only used in ET and not
actually used anywhere in the engine. They just spam us.
> shaders: Remove some ET only shaders.

- src/engine/client/cl_main.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_public.h
- src/engine/sys/sdl_glimp.cpp
The null renderer doesn't even define them.
This doesn't fix a bug or anything, but will make it easier to untangle for the next one.
> Remove cvar functions from refimport_t

- src/engine/null/null_renderer.cpp
/mnt/media/code/Unvanquished/daemon/src/engine/null/null_renderer.cpp: In function ‘bool RE_BeginRegistration(glconfig_t*, glconfig2_t*)’:
/mnt/media/code/Unvanquished/daemon/src/engine/null/null_renderer.cpp:196:15: error: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘struct glconfig2_t’ with no trivial copy-assignment; use assignment or value-initialization instead [-Werror=class-memaccess]
196 |         memset( glconfig2, 0, sizeof( glconfig2_t ) );
|         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> null_renderer: Fix warning about memsetting non-trival struct.

- src/engine/renderer/tr_shade.cpp
The first attempt #656 is a correct idea in principle, but it doesn't actually do anything on its own because the specular exponent uniform was not even initialized. Apparently it seemed to work due to randomness in an uninitialized value.
> Really fix specular mapping black patches (#471)

- src/engine/renderer/tr_shade.cpp
The statement saying standalone lightmaps are passed as
diffuse with white lightmap was wrong, standalone lightmaps
are already passed as lightmaps on white diffuse.
This updates the comment and tells the code may disable some
standalone lightmaps in some corner cases and also says this
is better wanted as it would never prevent default lightmaps
to be applied (and then it would looks good) while this code
is known to fix many other glitches.
The comment now contains an explicit FIXME to recommend
further investigations and states that the tests currently
take care of only allowing operations that are actually
known to not glitch.
This rewrites ba9ad6d71db2c8f95c017b702eda2c1b1e776c4f better.
> tr_shader: update comment about standalone lightmap blending

- CMakeLists.txt
Newer versions of GCC complain about our serialization code and prevent
it from builing under -Werror. Let's disable the warning as Werror for
now.
> cmake: Don't make stringop-overflow an a -Werror

- src/engine/client/cl_input.cpp
If someone wants to type a +command like +speed or +attack in console it
doesn't work (even if they add a random arg with it) because this check
will always pass and it returns. However, since +commands in console
never have a key asscoiated with them, check whether the key is valid
first.
> cl_input: Fix typing +command in console for repeat key press.

- src/common/cm/cm_plane.cpp
ioq3 has it as a debug print. ET:Legacy has it commented it out all together. It seems this check doesn't apply anymore.
- ioq3: https://github.com/ioquake/ioq3/blob/main/code/qcommon/cm_patch.c#L966
- et:l: https://github.com/etlegacy/etlegacy/blob/master/src/qcommon/cm_patch.c#L1175
Fixes https://github.com/Unvanquished/Unvanquished/issues/2109
> cm: Silence invalid bevel warnings.

- src/engine/renderer/tr_shader.cpp
I needed better debug information while diagnosing for #677.
The shader list displayed information for only one stage per shader, but to debug #667 I needed to print every stage information, and anyway assuming stage information is relevant for the whole shader isn't right.
After having added listing for every stage of a shader, I wanted them to not only print the information for 2 or 3 uses case but I was afraid at adding a new switch of 21 cases and padding all the strings by hand so I rewrote the column printing using `std::map`.
I also added a proper table header, etc.
While I was at it, at the end of the table not only the number of shaders is printed but also the number of stages and the maximum number of stage listed shaders have.
The may be a more c++-ish way to do the …
> tr_shader: rework shaderlist printing

- src/engine/framework/BaseCommands.cpp
Better supports integers and small numbers.
> Format math command output as %g

- src/engine/client/cg_api.h
This doesn't break compat because this function is already compiled in, just not declared.
> cg_api: Expose const Cmd::Args& trap_Args().

- cmake/DaemonCBSE.cmake
I got this issue:
```
-- git reported v0.53.2-5-gfb3d55449
-- Using CBSE Python executable: /usr/bin/python3.8
CMake Error at Daemon/cmake/DaemonCBSE.cmake:48 (message):
Missing dependences for CBSE generation.  Please ensure you have python ≥
2, python-yaml, and python-jinja installed.
Use pip install -r src/utils/cbse/requirements.txt to install
Call Stack (most recent call first):
CMakeLists.txt:153 (CBSE)
```
But I had the required python modules:
```
$ python3 -c 'import jinja2, yaml, collections, argparse, sys, os.path, re' && echo ok
ok
```
But I recently upgraded my distro and the python binary path changed:
```
$ /usr/bin/python3.8
bash: /usr/bin/python3.8: No such file or directory
```
```
$ realpath "$(command -v python3)"
/usr/bin/python3.10
```
So this PR attempts to force …
> cmake/DaemonCBSE: find python again if currently cached python path is invalid

- .appveyor.yml
Both of the Windows builds were just building the same thing (64-bit). One of them is intended to be 32-bit.
> CI: fix Windows bitness configuration

- src/shared/VMMain.cpp
This lets us get a crash dump with the stack trace, albeit at the cost of not being able to read a std::exception's message().
The trace can look like this (I programmed the `rocket` command to throw an exception):
```
Thread 0 (crashed)
0  main.nexe!abort [abort.c : 21 + 0x0]
rax = 0x0000000000000000   rdx = 0x0000000000000000
rcx = 0x000000000ffc13e0   rbx = 0x0000000000000000
rsi = 0x0000000000000000   rdi = 0x00000000fffe4d68
rbp = 0x00000000fffeff80   rsp = 0x00000000fffe4d90
r8 = 0x0000000000000000    r9 = 0x0000000000000000
r10 = 0x0000000000000000   r11 = 0x0000019000585860
r12 = 0x0000000000000037   r13 = 0x0000000000000288
r14 = 0x00000000100944c5   r15 = 0x0000019000000000
rip = 0x0000000000585896
Found by: given as instruction pointer in context
1  main.nexe!abort_message + …
```
> Avoid catching fatal exceptions under NaCl

- src/engine/renderer/tr_main.cpp
This makes navmesh flickering less jaggering, even if there are still some weirdness.
The problem this fixes is that the botDebugDrawCommands buffer was cleared after every rendering frame, while the server frame which did set the value (calling RE_SendBotDebugDrawCommands) did run less often, likely at a rate of sv_fps.
A good way to show how this change is useful is to notice how the flickering was much more annoying at /timescale 0.1, but is now not any worse.
@bmorel I think you'd be interested in that one too, since you complained loudly about that flickering before.
> navedit: less flickering

- .gitmodules
- CMakeLists.txt
- src.cmake
- src/engine/client/ClientApplication.cpp
- src/engine/framework/Application.cpp
- src/engine/framework/Application.h
- src/engine/framework/ApplicationInternals.h
- src/engine/framework/CommandSystemTest.cpp
- src/engine/framework/System.cpp
- src/engine/null/NullApplication.cpp
- src/engine/server/ServerApplication.cpp
1. Add namespace-aware cvar autocompletion (fixes #449). Thanks to @peoro for the original idea.
2. Introduce unit testing using Googletest (a.k.a GTest). To start with there are tests for the cvar namespace collapsing.
Our codebase is not very modular in terms of having independently buildable units; I have worked around this by building the tests directly into the engine binary. A `test` command is used to run the tests. (We could consider a `-test` command line flag instead, but I fear that would run into problems later with things not being initialized.) This approach could be nice for the gamelogic too since it is not easy to make a standalone NaCl binary.
The tests I added are for some `engine/framework` stuff so they are built into all engine binaries including dummyapp. Other …
> Cvar namespaces + unit tests

- src/engine/renderer/tr_fbo.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/sys/sdl_glimp.cpp
Fallback on `EXT_framebuffer_object` if `ARB_framebuffer_object` is missing.
`ARB_framebuffer_object` does more things than `EXT_framebuffer_object` so hardware supporting `EXT_framebuffer_object` may not support `ARB_framebuffer_object` but it looks like our game does not do crazy things enough and `EXT_framebuffer_object` seems to be usable as a fallback for missing `ARB_framebuffer_object`.
This makes the engine run on all Nvidia NV40 (Curie) on Linux with nouveau nv30 driver.
The proprietary nvidia 304 driver emulated `ARB_framebuffer_object` over `EXT_framebuffer_object` but nouveau doesn't, and the proprietary nvidia 304 driver isn't provided on Linux distributions anymore, leaving nouveau the only driver for this range of hardware.
I first tried to enable `ARB_framebuffer_object` …
> renderer: fallback on `EXT_framebuffer_object` if `ARB_framebuffer_object` is missing

- src/common/Color.cpp
- src/common/Color.h
- src/common/String.h
- src/engine/client/cl_console.cpp
- src/engine/client/cl_scrn.cpp
- src/engine/qcommon/q_shared.h
- src/engine/renderer/tr_decals.cpp
- src/engine/sys/con_common.cpp
- src/engine/sys/con_curses.cpp
- src/engine/sys/con_tty.cpp
Companion: https://github.com/Unvanquished/Unvanquished/pull/2304
The existing API failed to make it easy to do some common tasks, namely converting a color string to plain text and dealing with the possibility of dangling carets at the end of a string.
> Redesign Color::TokenIterator API

- src/engine/framework/VirtualMachine.cpp
> VirtualMachine: disable NaCl platform qualification to run armhf nexe on Raspberry Pi 4

- .gitmodules
Fetch `googletest` repository from `DaemonEngine` organization.
By using `DaemonEngine/googletest` as upstream (even if a 1:1 copy of `google/googletest`) we are allowed to:
- set the exact same name for the default branches of all submodules and then automatically commit and build submodules based on branch names
- tag all submodules with release tags like `unvanquished/0.54.0`
The same is true for every submodule we use.
> submodules: fetch googletest from DaemonEngine organization

- src/engine/renderer/tr_fbo.cpp
- src/engine/renderer/tr_local.h
- src/engine/sys/sdl_glimp.cpp
Follow-up of #727. This also the proof our engine can perfectly works with `EXT_framebuffer_object` as it was written against it, then EXT_fbo functions were replaced with ARB_fbo ones.
Before `EXT_framebuffer_object` was replaced by `ARB_framebuffer_object`
in c122d65c626f0b45507f044c4edae73af3709508, `EXT_framebuffer_blit`
was also required (now part of `ARB_framebuffer_object`) and two extra
errors specific to `EXT_framebuffer_object` were caught.
This enforces the requirement of `EXT_framebuffer_blit` if `EXT_framebuffer_object`
is available but not `ARB_framebuffer_object`, and restore catching for those
`EXT_framebuffer_object` errors.
An extra commit do some bikeshedding on comment wording.
> sdl_glimp,tr_fbo: also require EXT_framebuffer_blit if EXT_framebuffer_object, catch EXT errors

- src/engine/renderer/tr_shader.cpp
_Note:_ It also removes a previous implementation that revealed itself to be broken.
_Note:_ It would be very easy to add a cvar to reuse this code to disable light styles when light mapping is enabled. This can be useful for getting better performances on low presets.
Light styles are only compatible with light mapping as light styles are just extra light map stages with blend effects.
So we disable extra light map stages when light styles are not supported.
The first light map stage can be rendered using grid lighting, the other ones have no way to be rendered.
When light mapping is disabled, this:
```c
gloom2/7C9AD47A87BC98CCA1FF30C4D788DD47
{ // Q3Map2 defaulted
{
map $lightmap
rgbGen identity
}
// Q3Map2 custom lightstyle stage(s)
{
map $lightmap
blendFunc GL_SRC_ALPHA GL_ONE
rgbGen …
```
> tr_shader: disable extra lightmap stages when lightmapping is disabled

- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shader.cpp
#750 must be merged first, the target of this branch has to be changed to `master` once #750 is merged.
This allows to set `r_lightStyles 0` to disable light styles.
Light styles are special effects that blends multiple light maps to create fake dynamic lights, like lights of blinking neons.
Every extra light map is a different material stage and can't be collapsed, meaning every extra light map requires an extra render pass.
When extra light map tiles are stored in a light map file not shared with any static light map tile, the option would even prevent the loading of those extra light map files from file system and not upload them to GPU, reducing both load time and memory usage.
The purpose of this option is to be enabled by default but disabled in low graphics presets.
> tr_shader: add r_lightStyles cvar to disable light styles

- src/engine/renderer/tr_bsp.cpp
Note: _the engine already not loads light maps when light mapping is disabled: d2624fe9bb9d729629ef13dfcf5a152f342d82d1 from #358._
This makes the engine not loads deluxe maps when deluxe mapping is disabled. For example thunder has 7 deluxe maps that are 1024×1024 RGB textures. Before when deluxe mapping was disabled we still uploaded 7×1024×1024×3 bytes (25.9MB) to GPU for nothing.
---
Original message:
First purpose of this is to _not_ load deluxe maps when deluxe mapping is disabled, saving loading time from file system, uploading time to GPU and GPU memory  when using low presets. This is expected to divide by two the GPU memory used by light maps on low presets, which can be a big deal since light maps don't use DXT compressed format. Until now those deluxe maps were loaded in all …
> tr_bsp: do not load deluxemap if deluxemapping is disabled

- CMakeLists.txt
- src/common/FileSystem.cpp
Do not require pthread, cursesw, minizip and zlib when only building the game code.
Note: for some reasons zlib is still needed when building nacl game code.
We may be able to disable more code in `Fileystem.cpp` that may be unused when building game code, but at least the zlib-specific code is disabled and then not linked against.
This is motivated by some work-in-progress changes I'm doing to the release scripts.
> Do not require pthread, cursesw, minizip and zlib when only building the game code

- external_deps/build.sh
- linux-i686 cost is null
Now that the toolchain is fully cross-compilation compliant, building the engine for i686 is just a matter of setting `CC` to `i686-linux-gnu-gcc`. So the cost of it is null.
There is no change to be done on engine code neither on engine cmake to build a linux i686 engine as we already take care of engine i686 compatibility for Windows.
While the oldest supported amd64 CPU is 21 years old and the oldest supported GPU is 20 years old, Intel introduced new 32-bit-only processors until 2011 _included_, so the more recent 32-bit only Intel CPU is 11 years old. Also Intel sold amd64 compatible CPUs as 32-bit CPUs hiding the fact they were 64-bit compatible. I myself hosted linux network services for companies I worked for on such hardware, given I was _aware_ of it I …
> external_deps: do not prevent i686, and minor touchup (almost bikeshedding)

- CMakeLists.txt
- cmake/DaemonGame.cmake
It's useful when building and testing nexe without having to wait the linkage of other architectures.
> cmake: makes possible to build specific nexe architecture

- src/engine/framework/Network.h
- src/engine/qcommon/net_ip.cpp
- src/engine/server/sv_init.cpp
- src/engine/server/sv_main.cpp
Also make the `net_restart` command restart more stuff.
Fixes https://github.com/Unvanquished/Unvanquished/issues/2261.
> Fix DNS resolution breaking after sgame drop

- src/engine/client/cl_main.cpp
- src/engine/client/cl_parse.cpp
- src/engine/client/client.h
- src/engine/server/server.h
- src/engine/server/sv_client.cpp
- src/engine/server/sv_init.cpp
From reading, this shouldn't break demo loading for demos recorded before this commit. This changes the netcode however, so this PR is against 0.54.0/sync.
> Drop checksumFeed

- src/engine/renderer/tr_image_jpg.cpp
Current implementations should likely be either more recent than libjpeg6.2 or be libjpeg-turbo which from at least debian-oldoldstable supports the new command, even though it exposes `JPEG_LIB_VERSION` == 62.
> Remove old libjpeg 6.2 checks

- src.cmake
- src/common/String.cpp
- src/common/String.h
- src/common/StringTest.cpp
- src/engine/client/cl_main.cpp
- src/engine/qcommon/files.cpp
- src/engine/qcommon/qcommon.h
- src/engine/renderer/tr_animation.cpp
- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_image_crn.cpp
- src/engine/renderer/tr_image_dds.cpp
- src/engine/renderer/tr_image_jpg.cpp
- src/engine/renderer/tr_image_ktx.cpp
- src/engine/renderer/tr_image_png.cpp
- src/engine/renderer/tr_image_tga.cpp
- src/engine/renderer/tr_image_webp.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_model.cpp
- src/engine/renderer/tr_model_iqm.cpp
- src/engine/renderer/tr_model_md3.cpp
- src/engine/renderer/tr_model_md5.cpp
- src/engine/renderer/tr_public.h
- src/engine/renderer/tr_shader.cpp
- src/engine/renderer/tr_skin.cpp
A lot of places in the engine are using a file opening function that checks both VFS and homepath for stuff that should really only come from the VFS. For example if q3shaders are read from the homepath then you could cheat by adding a shader that makes walls invisible or something.
> Read various files from pakpath only (not homepath)

- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
GLSL_InitGPUShaders was mistakenly grouped with the code that only runs
if the GL context needs to be recreated. This meant the shader text is
only regenerated if you change something about the window or invoke
/vid_restart. But it should run every time the renderer restarts
(e.g. on map change). It is necessary to regenerate the text because
it may be affected by (latch) cvars.
To see the bug, change the value of `r_dynamicLight` and then change map.
The change will not take effect (despite the cvar being unlatched) and
in some cases the engine will crash (if dynamic light shaders were
never built but are used).
To be clear, this does NOT cause any additional shaders to be built
as long as no cvars were changed. We ALREADY compile or load from cache
each shader on every renderer restart. …
> Fix shaders not updating without vid_restart

- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/sys/sdl_glimp.cpp
renderer: drop unused `r_ext_multisample` and `r_alphabits` cvars
- `r_ext_multisample` belongs to MSAA and MSAA was only implemented in legacy renderer and was never reimplemented since.
- `r_alphabits` was only used in the legacy renderer.
____
Initial message:
We set some `r_ext_multisample` values with Unvanquished graphics preset, but the feature is not implemented yet and then the values aren't tested. It means the day we implement the feature, people may have the bad surprise of a potential performance hit because the variable may have been silently set to an high value before.
This patch ensures that any future released build of the engine will reset the cvar on user's configuration to clean-up them from random untested values.
Deleting the cvar would not reset the bad value in …
> renderer: drop unused `r_ext_multisample` and `r_alphabits` cvars

- src/engine/renderer/tr_model.cpp
MD3 models do some extra processing so it copies `name` to `filename`. We were loading `name` which was causing crashes when trying to view md3 models.
Fixes https://github.com/Unvanquished/Unvanquished/issues/2371
> tr_model: Fix typo when reading md3 models

- src/engine/sys/sdl_glimp.cpp
The engine is probably working without a DXT textures, but the only released game (Unvanquished) cannot run without DXT support because almost all textures make usage of it.
The first device that may provide all required features but s3tc extension to be working with the Dæmon engine is the Broadcom  VideoCore IV which was released in 2016 and is well known to be used in the Raspberry Pi 3 that was released in 2018.
This patch only flags the s3tc GL extension as required to avoid an engine crash if it's missing. I intentionally not purged yet the various code that may rely on this extension being there or not to branch on different code (mainly, logging).
I think it would be interesting to have an in-engine crn/DDS to RGBA fallback for the cases where the GPU does not support s3tc or does …
> sdl_glimp: flag the s3tc GL extension as required

- src/engine/renderer/tr_shader.cpp
Allow depth shader name to be longer than `MAX_QPATH`, fix Unvanquished/Unvanquished#2370
Also unify some logging.
> allow depth shader name to be longer than MAX_QPATH, fix #2370

- src/common/FileSystem.cpp
- src/common/FileSystem.h
FS::PakPath::ListFiles could return a 'no such directory' error. But the pakpath doesn't even have a concept of directories. It was actually just returning an error if the number of files found is zero. So it doesn't make sense to report an error.
Fixes https://github.com/Unvanquished/Unvanquished/issues/2373.
> PakPath::ListFiles - don't error on empty result

- src/engine/renderer/glsl_source/computeLight_fp.glsl
The dynamic lights are evenly divided into four "layers". Due to the typo of 'return' instead of 'break' (unnoticed since the original tiled renderer commit), only lights assigned to the first layer were being rendered.
This seems to fix https://github.com/Unvanquished/Unvanquished/issues/2351, although it doesn't makes sense. The bug fixed here is that we skip rendering some lights, which should make things dimmer, not brighter. (With the NVidia bug the light is far brighter than what you get from just rendering all lights correctly.) If I change the `return;` to `layer = 9; break;`, which should not change the meaning of the existing code, then the excessive brightness go away. So it seems that we have some sort of compiler bug or optimization quirk with Nvidia drivers.
It was not as …
> Render all dynamic lights, not a random 25%

- external_deps/build.sh
Some various changes:
- factorize platform definition
Right now adding a linux platform would be as easy as adding a one-line function, this way:
```bash
setup_linux-amd64-default() {
common_setup linux x86_64-unknown-linux-gnu
}
```
- rename `MSVC_SHARED` as `CONFIGURE_SHARED`
It makes the name more relevant.
- remove `-m32` and `-m64` flags
We already hardcode the 32-bit and 64-bit compilers anyway.
- always reset flags from the environment and require compiler names to be hardcoded
We heavily cross-compile and must not inherit any stray flag from environment.
Require the compiler names to be explicitly hardcoded, we should not inherit them from environment as we heavily cross-compile. They are already all hardcoded, make sure to get an error when adding a new platform without writing …
> external_deps: factorize platform definition and other things

- src/engine/client/cg_api.h
- src/shared/CommonProxies.cpp
- src/shared/CommonProxies.h
Declare these functions used in both gamelogics in their rightful header rather than duplicating the definitions in cg_api.h and sg_trapcalls.h.
> Declare trap_* from CommonProxies.cpp in a single header

- src/common/Endian.h
- src/common/Platform.h
1. common/Endian: remove Xbox 360 code
Only Xbox 360 is big-endian (PowerPC). Original Xbox, Xbox One and Xbox Series are little-endian (i686 for the Original,
amd64 for others). We don't build for Xbox anyway.
2. common/Platform: unify macOS wording
Rename _Mac OS X_ as _macOS_ following current Apple naming conventions.
Moved from:
- https://github.com/DaemonEngine/Daemon/pull/799
> Platform code touchup

- CMakeLists.txt
- src.cmake
- src/engine/client/cl_cgame.cpp
- src/engine/client/cl_main.cpp
- src/engine/client/client.h
- srclibs.cmake
This makes possible to build the engine without mumblelink, by setting `USE_MUMBLE` cmake option to `OFF`.
I was too lazy to fix mumblelink on Android, and since it's not required to play the game, why not making possible to disable it on platform that doesn't build that code?
Borrowed from:
- https://github.com/DaemonEngine/Daemon/pull/799
> cmake: make mumblelink optional

- src/common/FileSystem.cpp
- src/common/FileSystem.h
- src/engine/framework/ApplicationInternals.h
- src/engine/framework/System.cpp
Introduce `FS::DefaultTempPath()`
Make sure `TMPDIR` is always used when needing a temporary file
outside of Windows.
`TMPDIR` is a standard variable, for example it is used by `mktemp`.
Android doesn't give access to `/tmp` but Termux sets `TMPDIR`.
This is needed by:
- https://github.com/DaemonEngine/Daemon/pull/799
This fixes this error on systems not allowing to write in `/tmp` but setting `TMPDIR` instead:
> `Warn: Could not bind singleton socket: No such file or directory`
> common/FileSystem: introduce `FS::DefaultTempPath()`

- CMakeLists.txt
Do not require dependencies on unsupported systems.
Display a warning instead.
This allows to build the native binaries, for example to run a server using exe game code, even if there is no provided deps and especially no NativeClient binaries.
> cmake: do not require dependencies on unsupported systems

- src/engine/framework/System.cpp
Currently when daemon fails to create a socket, it does not says what it tries to do, making it a pain to know which file to clean. This PR gives this information in logs.
I got annoyed by the lack of info about which file to remove after a crash, hence this PR.
> say which file failed when checking socket

- src/common/Platform.h
Platform: do not require to duplicate dll and exe extensions and path separator defines
Windows is very likely the only one requiring something different, and if exists, the other systems not doing things the Unix way may be even more rare or have least interest than systems like Android, BSD variants, and others.
On that part of the code, it's now only required to add an ifdef and a define (two lines) for setting a new platform if it's WIN32 or UNIX compatible.
> Platform: do not require to duplicate dll and exe extensions and path separator defines

- src/engine/framework/System.cpp
It looks like that, after many rewrite before merging:
- https://github.com/DaemonEngine/Daemon/pull/800
I failed to notice I actually changed the socket path, changing it from a “`file named X in a directory named Y`” to a “`file named Y`”.
While the merged code works (the socket works), the unwanted socket path modification broke command forwarding between older and newer engines because they don't agree on that socket path.
> framework/System: restore socket path

- src/engine/renderer/tr_local.h
Bump `MAX_IMAGE_ANIMATIONS` to `32` (from `24`)
On game side, the particle system has `MAX_PS_SHADER_FRAMES` set to `32`, so let's unify this number.
There may be animations with 25 images around or more, like the new Unvanquished groundfire:
- https://github.com/UnvanquishedAssets/res-weapons_src.dpkdir/pull/15
Without this patch, it was expected the engine only loaded `24` images instead of `25`.
> bump `MAX_IMAGE_ANIMATIONS` to `32`

- src/common/FileSystem.cpp
Some rewrite:
- Do not check for `HOME` if `XDG_DATA_HOME` is set
- Check for environment variables not only being set but also not empty
- More usage of `Path::Build()`
- Single `return` for all failures
- etc.
> common/FileSystem: rewrite `FS::DefaultHomePath()`

- src/engine/renderer/tr_bsp.cpp
Set `internalLightMapSize` in the block using it, a global variable is useless.
> tr_bsp: set internalLightMapSize in the block using it

- src/engine/renderer/tr_bsp.cpp
Do not load the light grid if precomputed lighting is disabled.
> tr_bsp: do not load the light grid if precomputed lighting is disabled

- src/engine/renderer/tr_init.cpp
Make `r_precomputedLighting` a cheat cvar.
Disabling this cvar disables all precomputed shadows and then makes everything fullbright, which gives
an unbalanced advantage by making everything visible.
_Note:_ to actually get the expected behaviour from this cvar, ones need to also merge:
- https://github.com/DaemonEngine/Daemon/pull/820
> tr_init: make r_precomputedLighting a cheat cvar

- src/engine/renderer/tr_local.h
Cleanup an useless declaration.
This would have been useful if a struct or a function declaration used that type before that type was declared, but this is not happening.
> tr_local: cleanup an useless declaration

- src/engine/client/cl_input.cpp
Use `Math::Clamp`.
---
_Original message:_
Use `std::min` and `std::max`.
> cl_input: use `Math::Clamp`

- README.md
Replace dead Travis badges by Azure ones.
Also rename OSX as macOS.
> readme: replace dead Travis badges by Azure ones

- src/common/cm/cm_test.cpp
- src/common/cm/cm_trace.cpp
When spamming grenades, some parts of the tracing codes is iterated millions time. For example the `CM_TestInLeaf` function can count for 10 or 15% of the CPU time spent by the game, not because the compute is heavy, but because it is done so many time. In this case even simple things are costly, like dereferencing a pointer of pointer instead of deferencing a pointer, because it is done millions time.
So I turned some array index iterators into pointer iterators in those precious functions. While I was at it and for completeness, I also did it for every leaf brush, leaf surface, and brush side in both `tr_trace.cpp` and `tr_test.cpp`.
This PR also brings some commits unrolling some loops, helping the compiler to vectorize them, for similar reasons: small speedup can become large when …
> common: some optimizations in tracing code

- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_main.cpp
- src/engine/renderer/tr_shader.cpp
This may happen if, for example, a portal is seen while being outside the map.
There can be other broken ways to reproduce the bug.
The bug can be reproduced with Spacetracks map 1.1.3 from Unvanquished 0.54 and: `/setviewpos 378 -1906 625 80 1`
This would break the render, even loading another map would not fix the render.
To fix the render, one would have to do: `vid_restart` or move to a place where a portal is properly rendered like this: `/setviewpos 27 -1838 668 147 13`
The code already supports recursive portals, the maximum recursion
is configured with  `r_max_portal_levels` cvar (set to `5` by default).
`256` seems too low.
> A bunch of portal fixes

- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shade.cpp
The render is now as expected not only when `r_precomputedLighting` is enabled but also when it is disabled.
Disabling lightmapping while keeping deluxemapping enabled now still loads the deluxemaps to use them with gridlighting.
A variable named `tr.worldLightMapping` is used to know when light mapping is enabled instead of redoing all the tests
with potential mistakes. The is similar to the already existing `tr.worldDeluxeMapping` variable.
`Render_LightMapping()` always knows how to render, there are fallback everywhere.
Rendering with depth fill when there is no lighting is simply wrong, it was probably a very early workaround from before then engine was setting up a fallback lighting.
> tr_bsp,tr_shade: rework precomputed light, light map, deluxe map enablement

- src/engine/server/sv_client.cpp
Original patch by @ineedbots
See:
- https://github.com/ioquake/ioq3/pull/596
- https://github.com/callofduty4x/CoD4x_Server/pull/336
Commit message:
> Fix bad client reliableAcknowledge DOS exploit
>
> Having a reliableAcknowledge of 0x7FFFFFFF causes a massive loop to be executed in SV_UpdateServerCommandsToClient due to the + 1 overflow.
Rewritten from a suggestion by @slipher
> Import and rewrite a fix from ioq3

- external_deps/naclsdk-pydir-python3.patch
That's a very minor patch and is not required to build the game.
It makes possible to get pnacl compiler version this way:
```
external_deps/linux-amd64-default_8/pnacl/bin/pnacl-clang --version
```
> external_deps: also fix `pnacl-clang --version` on python3

- external_deps/build.sh
Copy `ld-linux-armhf.so.3` instead of renaming it, binaries may still reference `ld-linux-armhf.so.3` as dependency (not only as a loader).
Add a comment explaining why we don't use `patchelf` but do some hacky in-place `sed` rewriting instead.
> external_deps: copy `ld-linux-armhf.so.3` instead of renaming it

- external_deps/build.sh
Patch stolen from:
external_deps: set recommended architecture and build options like the engine
> external_deps: set recommended architecture and build options like the engine

- external_deps/build.sh
Patches stolen from:
This makes easier to update libraries requiring NASM.
Actually the `NASM` environment variable used by libjpeg doesn't have the same name in this or that libjpeg (newer versions use another name), and this is specific to libjpeg. Relying on `PATH` mechanism is more reliable, future-proof and library-independent.
> external_deps: improvements around NASM support

- azure-pipelines.yml
Stolen from:
This adds Mingw build in Azure Pipelines CI.
Since our official release builds for Windows are built on Linux using Mingw, we may also want to make sure such build scenario doesn't break.
> azure-pipelines: add Mingw build

- src/engine/sys/sdl_input.cpp
When combined with a call to trap_SetMouseMode(MouseMode::SystemCursor) during CG_Init, this fixes #866.
> Fix disappearing cursor during load on Mac

- src/engine/qcommon/translation.cpp
The auto-detected language will no longer by archived by default. It will only be archived if you use `seta` or choose a language from a (not yet existing) menu in the UI.
Fixes https://github.com/Unvanquished/Unvanquished/issues/2165.
> Don't archive language cvar

- src/engine/client/ClientApplication.cpp
- src/engine/client/hunk_allocator.cpp
- src/engine/qcommon/qcommon.h
Free the memory allocated by `Hunk_Init()` so that doesn't count as leaked memory.
> client: add `Hunk_Shutdown()` to make easier to read valgrind output

- src/engine/renderer/tr_model_iqm.cpp
Should fix #880:
- https://github.com/DaemonEngine/Daemon/issues/880
All other similar vboData initialization code already do the same, like:
- `src/engine/renderer/tr_model_skel.cpp` (md5 models)
- `src/engine/renderer/tr_model_md3.cpp`
- `src/engine/renderer/tr_light.cpp`
- `src/engine/renderer/tr_vbo.cpp`
- `src/engine/renderer/tr_bsp.cpp`
> tr_model_iqm: fix use of uninitialized data

- external_deps/build.sh
- `base` and `all` package lists
- do not build curl with brotli and zstd
> external_deps: add package lists and disable brotli and zstd when building curl

- src/engine/renderer/tr_image.cpp
tr_image: avoid a copy when iterating an array of struct
> tr_image: avoid a copy when iterating an array of struct

- src/common/cm/cm_load.cpp
- src/engine/client/cl_main.cpp
- src/engine/server/sv_init.cpp
I've noticed a lot of stuff allocated with `CM_Alloc` were remaining on shutdown.
Previously it was only done on map load.
So I made sure `CM_FreeAll()` is also called on shutdown.
Also don't call `CM_ClearMap` in `CL_ShutdownAll`.
> cm: call `CM_FreeAll()` when doing `CM_ClearMap()`

- src/engine/audio/OpusCodec.cpp
OpusCodec: free buffer after use.
Fixes #881:
- https://github.com/DaemonEngine/Daemon/issues/881
> OpusCodec: free buffer after use

- src/engine/framework/CommandSystem.cpp
Partially frees some cvar leaks:
- https://github.com/DaemonEngine/Daemon/issues/885
It looks like all cvars spawn a command, those commands are never freed.
This only _partially_ fixes the problem because:
- Cvar code is still leaking a lot because CvarProxy code is leaking a lot too.
> CommandSystem: free all commands on exit

- CMakeLists.txt
Fix SDL2 copy on MSVC.
I hope this don't break MingW copy.
I have not tested it on Windows with MSVC.
> cmake: fix SDL2 copy on MSVC

- src.cmake
- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/glsl_source/generic2D_fp.glsl
- src/engine/renderer/shaders.cpp
- Don't use the same cache file for the generic and generic2D GLSL shader
Do not rebuild generic GLSL shaders on every map load.
- set `GENERIC_2D` define without relying on an extra file.
Fixes #889:
- https://github.com/DaemonEngine/Daemon/issues/889
> don't use the same cache file for the generic and generic2D GLSL shader, etc.

- external_deps/build.sh
It looks to have been mistakenly removed in 93d4c3e7eaea03eea2cf854f4197681461f88970, likely a rebase error.
> external_deps: re-add a case “;;” mistakenly removed

- src/engine/framework/CvarSystem.cpp
Continuation of:
- https://github.com/DaemonEngine/Daemon/pull/896
Finishes to fix #885:
- https://github.com/DaemonEngine/Daemon/issues/885
First commit fixes that (valgrind):
```
==00:00:00:59.515 213477== 24 bytes in 1 blocks are possibly lost in loss record 23 of 535
==00:00:00:59.515 213477==    at 0x4845013: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==00:00:00:59.515 213477==    by 0x38940D: void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) (basic_string.tcc:225)
==00:00:00:59.515 213477==    by 0x4226CD: Cvar::InternalSetValue(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, …
```
> CvarSystem: free all cvars on exit

- src/engine/audio/Audio.cpp
- src/engine/audio/Emitter.cpp
- audio: rewrite an iterator in a code requiring performance
That's the reason why I did this branch first, it's to rewrite a loop in a code that has a critical need for performance (it's one of the hot spot of the engine).
- audio: rewrite some iterators for the sake of more c++ism
This commit is just doing similar changes in less or not critical parts of the code and that's mostly bikeshedding, I just took care of them too while I was around.
> Rewrite some iterators in audio code

- src/engine/client/ClientApplication.cpp
- src/engine/client/cl_cgame.cpp
- src/engine/client/cl_main.cpp
This will open an error message to the client's main menu stating why they have been disconnected from the server (whether kicked or otherwise).
> set the error message when disconnected from the server

- src/engine/client/cl_cgame.cpp
- src/engine/client/cl_main.cpp
- src/engine/client/client.h
The important commit:
> The cvars cl_pingSpacing, cl_pingSpacingRetry1, and cl_pingSpacingRetry2
can be used to configure serverinfo queries (used to populate the server
list) to be attempted up to 3 times, possibly with a minimum delay
between outgoing packets which may be different for each round of
attempts. All first tries must be completed/timed out before starting
2nd attempts, etc.
>
> Default behavior is the same as 0.54 - one attempt with no delays.
>
> Fixes https://github.com/DaemonEngine/Daemon/issues/654.
> Retries and rate limiting for serverinfo queries

- external_deps/build.sh
SDL2 CMake requires the `bin/` dir to exist even when not using anything from it
Fixes #946:
- https://github.com/DaemonEngine/Daemon/issues/946
This also fixes doing release builds for Linux (yay!).
> deps: SDL2 CMake requires the bin/ dir to exist even when not using anything from it

- src/engine/renderer/tr_surface.cpp
This is CPU fallback code for when GPU can't accelerate model, to test this code one can do `set r_vboVertexSkinning 0`.
Continuation of the talk from there:
- https://github.com/DaemonEngine/Daemon/pull/953#discussion_r1382713656
> @slipher: Hmm do you have an argument for why precision isn't needed here? We had that bug with black patches in models due to the GLSL compiler compiling the same code slightly differently in 2 different shaders, so you can't just say that it's graphics so the precision doesn't matter...
> @illwieckz: Unfortunately I don't have an argument for why precision isn't needed here, I only have an argument for why performance is wanted here. 😅️
> @illwieckz: I don't know if that can help, but as far as I know when this code is used, the GLSL compiler is not used …
> renderer/tr_surface: use vectorNormalizeFast in MD5/IQM code

- src/common/FileSystem.cpp
- src/engine/framework/System.cpp
The idea is to allow to provide a complete tree of dpk archives in an subfolder and get them loaded first.
This will be useful for the nightly server, or for any mod.
Basically by running the game like this:
```sh
./daemon -set fs_pakprefixes 'dev'
```
The engine will look for `pkg/dev/unvanquished` dpk before the `pkg/unvanquished` one, and load it if exists.
It means we can host a whole copy of upcoming Unvanquished dpk archives in `pkg/dev` and get clients download it from `pkg/dev`, not breaking default installs on user side.
Like `fs_extrapaks`, the `fs_pakprefixs` cvar can gets a space-separated list of folders, so for example one can set `race dev` and the engine is expected to look first in `pkg/race`, then in `pkg/dev`, then in `pkg`.
First prefix to have a package for the given …
> files: implement fs_pakprefixes

- src/engine/client/client.h
Set `originalDownloadName` size to `MAX_OSPATH` since we copy there `downloadName` which is size `MAX_OSPATH`.
We have this code in `src/engine/client/cl_download.cpp`:
```
Q_strncpyz( cls.originalDownloadName, cls.downloadName, sizeof( cls.originalDownloadName ) );
```
but `sizeof(cls.downloadName)` is `256` (`MAX_OSPATH`) and `sizeof(cls.originalDownloadName)` is `64` (`MAX_QPATH`), meaning the server can tell the client to download a package whose name is longer than what the client string can carry. Let's just enlarge that string.
Large pak names with checksums would be truncated otherwise, letting the client stuck in an infinite download loop because the download of the pak will never succeed.
See:
- https://github.com/DaemonEngine/Daemon/issues/681
> client: set originalDownloadName size to MAX_OSPATH since we copy there downloadName which is size MAX_OSPATH

- src/engine/framework/Application.cpp
Fixes this error on Intel ICX 2023.2.2:
```
In file included from Unvanquished/daemon/src/engine/framework/Application.cpp:31: In file included from Unvanquished/daemon/src/engine/framework/Application.h:35: Unvanquished/daemon/src/common/String.h:287:20: error: unknown type name 'uint8_t'
287 |     char HexDigit( uint8_t digit );
|                    ^
1 error generated.
```
Replaces:
- https://github.com/DaemonEngine/Daemon/pull/968
> framework: include Common.h in Application.cpp

- external_deps/build.sh
external_deps: always use system curl, not self-built curl from external_deps custom PATH
> external_deps: always use system curl, not self-built curl from external_deps custom PATH

- cmake/DaemonGame.cmake
- cmake/DaemonNacl.cmake
- cmake/toolchain-pnacl.cmake
Very minor.
When toying with Saigo I noticed this code could be factored: the `PLATFORM_EXE_SUFFIX` is set in the toolchain file so there is no need to hardcode the value there. The same code would probably work for `.pexe`, direct `.nexe` or even `.wasm` as long as the toolchain properly sets `PLATFORM_EXE_SUFFIX`.
> cmake/DaemonGame: make code more reusable for other toolchains

- src/engine/renderer/tr_shade.cpp
Fix the use of lightgrid on bsp surfaces without lightmap.
It looks like a line was mistakenly deleted in 56d0d83ca64d0712a315d6637a3dfb0ccf74a5ab.
Seems to fix #990:
- https://github.com/DaemonEngine/Daemon/issues/990
> Fix the use of lightgrid on BSP surfaces without lightmap

- src/engine/renderer/tr_image.cpp
Something I spotted while reading the code.
On line `2884` we have
```
imageParams.bits = IF_NOPICMIP | IF_NORMALMAP;
```
So we must re-set this variable to `IF_NOPICMIP` when creating the cinematic images.
Once such variables are set, there is no need to set them again for following images with same options, so I just moved existing lines at an early point.
> tr_image: _cinematic image is not a normal map

- src/engine/qcommon/translation.cpp
Will fix https://github.com/Unvanquished/Unvanquished/issues/2867 when combined with deleting the country suffixes from the selector.
> Localization: don't try to detect country

- CMakeLists.txt
- src/engine/client/cl_console.cpp
- src/engine/qcommon/common.cpp
- src/engine/qcommon/q_shared.h
There was only one reference to REVISION, in qcommon.h, but it was never used because the relevant header was not included.
It's not implemented reliably anyway. The revision detection only reruns at random times (when cmake stuff is modified), so it is only reliable for a freshly created build dir, like for a release. But for releases we just hard-code the version with update-version-number.sh. The revision could be made always correct by forcing the revision header to be re-created on every build but that's ugly since it slows down incremental builds.
> Remove unused git revision info

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
We shouldn't just believe what the shader cache file says the size of its binary program is. If the file were truncated, believing it would cause an out-of-bounds read.
On my machine the Nvidia driver crashed even when incorrectly told that the length of the shader binary is 0, which would seem fairly innocuous...
> Validate shader cache binary size

- src/common/IPC/Common.h
- src/engine/client/cg_api.h
- src/engine/client/cl_cgame.cpp
- src/engine/framework/VirtualMachine.cpp
- src/engine/framework/VirtualMachine.h
- src/engine/server/sg_api.h
- src/engine/server/sv_sgame.cpp
- src/shared/VMMain.cpp
- src/shared/VMMain.h
Companion: https://github.com/Unvanquished/Unvanquished/pull/2874
The previous mechanism was that one should update some constants CGAME_API_VERSION and GAME_API_VERSION, but no one ever did it. The counters only got to 3 in 10 years of development.
Instead tie gamelogic ABI versioning to "major" Unvanquished releases. The assumption is that in each major release there will always be a few compatibility-breaking changes, while a point release definitely should not have any such changes or else the previous gamelogic can't run.
This will help users get an informative error message when they try to replay a demo or run a mod that is not compatible with the current Daemon.
Additionally there is a constant defined for whether the gamelogic ABI contains breaking changes intended for an …
> Better detect incompatible versions of game VMs

- src/engine/client/cg_api.h
- src/engine/client/cg_msgdef.h
- src/engine/client/cl_cgame.cpp
- src/shared/client/cg_api.cpp
Implement `trap_S_UpdateEntityPositionVelocity` to set position and velocity in one call.
Engine sidecar of:
- https://github.com/Unvanquished/Unvanquished/pull/2680
> cg_api: implement `trap_S_UpdateEntityPositionVelocity` to set position and velocity in one call

- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_local.h
Sets glDepthFunc to GL_ALWAYS when rendering the portal surface and enables depth test. Fixes #1012, https://github.com/Unvanquished/Unvanquished/issues/2476, and partially fixes #1010.
Introduces GLS_DEPTHFUNC_ALWAYS which sets glDepthFunc to GL_ALWAYS. Shifted some enums to avoid conflicts in GL_State().
Here are some comparison screenshots (before / after):
> Fix portal blending with foreground translucent surfaces

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/glsl_source/computeLight_fp.glsl
- src/engine/renderer/glsl_source/forwardLighting_fp.glsl
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_shader.cpp
Robert Beckebans, original XreaL author, said:
> Hi Thomas,
> The wrap around lighting term was something that was discussed in a very old game presentation where the devs provided some cheap outdoor lighting.
> I just experimented with it a bit but you can remove it. I would never use it again in such a way and yeah the code is wrong :)
> NUKE wrapAroundLighting

- src/engine/sys/sdl_glimp.cpp
Workaround texture distorsion bug on Intel GPU
This bug seems to only affect gfx9 but detecting gfx9 may not be easy.
See:
- https://github.com/DaemonEngine/Daemon/issues/909
- https://gitlab.freedesktop.org/mesa/mesa/-/issues/10224
This workaround was suggested here:
- https://gitlab.freedesktop.org/mesa/mesa/-/issues/10224#note_2230107
I confirm this workarounds the bug on my end on Intel HD 520 on Linux.
> sdl_glimp: workaround texture distorsion bug on Intel GPU, fix #909

- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_main.cpp
- src/engine/renderer/tr_shade.cpp
Fixes portal blending with portal surfaces, misc_portal_surface entity selection and GL_FrontFace for mirrors in chains of recursive portals/mirrors. Fixes #1011. Disables the 64qu distance limit for portal entities which wasn't working properly anyway.
Portal entities are now chosen based on their distance to the center of the portals surface (calculated as the average of all vertices). Old code was checking if they are within 64qu of the plane, which was resulting in portals entities that are actually much further away being chosen.
Introduces Tess_StageIteratorPortal(), intended for portals to properly write to stencil buffer.
Screenshots (some blended surfaces look slightly off, this might be an issue with lighting in general, portals themselves blend correctly):
> Fix portal surface blending, entity selection and recursive mirrors

- src/engine/renderer/glsl_source/computeLight_fp.glsl
- src/engine/renderer/glsl_source/lightMapping_fp.glsl
- src/engine/renderer/glsl_source/liquid_fp.glsl
Make GLSL code easier to read with computeLight, computeDirectionalLight and computeDynamicLights.
The real magic is in `lightMapping_fp.glsl`, it makes easier to spot the actual alternative code to directional light computation that was previously disseminated everywhere, we now have a simple if/else condition calling one or the other function.
> renderer: make GLSL code easier to read with computeLight, computeDeluxeLight and computeDynamicLights

- src.cmake
- src/common/Util.cpp
- src/common/Util.h
- src/common/UtilTest.cpp
- src/engine/client/ClientApplication.cpp
- src/engine/framework/Application.cpp
- src/engine/framework/Application.h
- src/engine/framework/BaseCommands.cpp
- src/engine/server/ServerApplication.cpp
- src/engine/sys/con_curses.cpp
Implement an exponential moving average algorithm for counting FPS and make it available for the engine in two ways: a `showfps` printing command, and a counter in the curses console. This can be useful to monitor for server performance issues.
I also have a branch to replace the cgame FPS counter with this algorithm (haven't uploaded it yet). It's better than the current algorithm because if you have a perfectly stable FPS, the FPS counter will also be stable (unless it's right at a half-integer I guess). With the current algorithm the FPS tends to flicker between various numbers even if the frame times are very consistent.
> Add FPS counter to curses window and /showfps command

- src/common/Compiler.h
The `DAEMON_ARCH_pnacl` define is now `DAEMON_ARCH_nacl` (PNaCl is a toolchain, NaCl is an architecture), without this change, the Game CI raises this warning and aborts.
> compiler: avoid breakpoint warning when building nacl gamecode (fix CI)

- src/engine/renderer/tr_backend.cpp
Changes the portal surfaces to render as a BSP surface in Tess_Begin() in FinalisePortalCommand. Sets the lightmapNum and fogNum, although this isn't necessary since &lightmap always uses worlds lightmap (-1).
Note: this does not fix dynamic lights for portals.
Screenshots:
Without lightmap:
With lightmap:
Without lightmap:
With lightmap:
> Fix lightmaps for portal surfaces

- src/engine/client/key_binding.cpp
- src/engine/renderer/tr_animation.cpp
- src/engine/renderer/tr_fbo.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_model.cpp
- src/engine/renderer/tr_shader.cpp
- src/engine/renderer/tr_skin.cpp
- src/engine/renderer/tr_vbo.cpp
This is some lazy task I did to change my mind and this put an end to something that annoyed me for a long time. This unifies our engine `list` commands and functions.
I was worrided we had `listCvars` and `listCmd` but `imagelist` and `shaderlist`, so we no also have `listImages` and `listShaders`, which also greatly improves command completion when looking for “_what do we can list_”? This also totally removes the extra useless mental load of thinking about “_is the name of the command I need starting or ending with `list`_”?
I also unified the related functions.
For example we had `R_InitVBOs()`, `R_ShutdownVBOs()`, `R_InitFBOs()`, and `R_ShutdownFBOs()` but `R_VBOList_f()` and `R_FBOList_f()`, we now have `R_ListVBOs_f()` and `R_ListFBOs_f()` which is more consistent with other …
> Unify list command and function naming

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/glsl_source/skybox_fp.glsl
- src/engine/renderer/glsl_source/skybox_vp.glsl
- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_main.cpp
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_shader.cpp
- src/engine/renderer/tr_sky.cpp
- src/engine/renderer/tr_surface.cpp
Generate a persistent mesh for the skybox consisting of a cube with 8 vertices and 12 triangles.
Old code was creating a mesh consisting of many "blocks" (2 triangles each) on the CPU and uploading it to the GPU *every frame that the sky was rendered*. Not only that, but it performed operations on mapped memory. The mesh itself normally consisted of 1k+ triangles, which in itself is not much for modern hardware, but it's far more than needed and often more than the rest of the view combined. This was horrible for perfomance.
New mesh:
Old mesh example:
Move cloud generation to fragment shader. The fragment shader will now branch on a uniform to sample different textures, which will likely be faster than switching shader programs. The skybox itself will now always be centered on the view …
> Optimisation: skybox rendering

- external_deps/build.sh
Fixes Unvanquished/unvanquished-infrastructure#37:
- https://github.com/Unvanquished/unvanquished-infrastructure/issues/37
Also brings other improvements and fixes.
This implements:
-   external_deps: tell curl to set the remote timestamp of the downloaded archive
-   external_deps: add --download-only option
-   external_deps: fix all windows-amd64-mingw package list
-   external_deps: add meta platforms like 'all'
This make possible to do:
./build.sh --download-only all all
or:
./build.sh build-linux base
-   external_deps: add our own mirror and add --prefer-ours option (disabled by default)
-   external_deps: make options cumulative
-   external_deps: fix help printing on macOS
-   external_deps: prefer xz archives when available
> external_deps: add our own mirror, and options to only download or prefer our own mirror

- src/engine/renderer/tr_sky.cpp
> Reset GL_State when rendering outer skybox

- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_shader.cpp
This deeply rewrites the stage collapse, I needed this when implementing sRGB as I had to be sure of what I was rendering.
This also fix some bugs and uncovers some. For example our creep material is currently lacking a lightmap but because of a bug it was rendered properly. Once this is merged it will be rendered as buggy as it should be with the mistake.
This also collapse more stages. For legacy materials done this way:
```
color map
lightmap with multiplication
```
```
light map
color map with multiplication
```
They are automatically turned into diffuse stages.
While for legacy materials done this way:
```
color map
lightmap with multiplication
colormap with addition
```
```
light map
color map with multiplication
color map with addition
```
They are automatically turned into diffuse …
> renderer: revamp shader stage collapsing

- src/engine/renderer/tr_shade.cpp
It doesn't make sense to bind `tr.lighttileRenderImage` with generic GLSL shader, especially not with 2D one.
> renderer: do not bind tr.lighttileRenderImage with generic GLSL shader

- src/engine/renderer/tr_main.cpp
Width and height in glScissor() must not be negative, so if surfRect has lower x2 or y2 than x1 or y1, then flip the scissor parameters. Tested on `test-portals-recursion` on viewpos -2223 639 65 91 3.
Fixes a GL_INVALID_VALUE at https://github.com/DaemonEngine/Daemon/blob/1872b92274fbd9533e622633c56a515a4ff899c0/src/engine/renderer/tr_backend.cpp#L359
> Fix portal scissor test

- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shader.cpp
Deep revamp of image and shader listing functions.
- Make it always use `Log::CommandInteractionMessage` to avoid being truncated by `logs.suppression.enabled`.
- More `std::string`, less `char*` and related C functions.
- More map-based decision (more generic code, and move copy-pasting risks to data instead of logic).
- Added strings for all image formats that I managed to list but were not known before.
A rewrite of the shader listing was already done by me some time ago, the rewrite of the image listing was now done in a similar way but even pushed forward, and the shader listing was then pushed to that same level.
> renderer: revamp image and shader listing

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/glsl_source/cameraEffects_fp.glsl
- src/engine/renderer/glsl_source/contrast_fp.glsl
- src/engine/renderer/glsl_source/fogGlobal_fp.glsl
- src/engine/renderer/glsl_source/fogQuake3_fp.glsl
- src/engine/renderer/glsl_source/generic_fp.glsl
- src/engine/renderer/glsl_source/lightMapping_fp.glsl
- src/engine/renderer/glsl_source/skybox_fp.glsl
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_scene.cpp
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_shader.cpp
- src/engine/renderer/tr_sky.cpp
* renderer: implement complete overBright in GLSL
We cannot overBright separate stage as stage are clamped within `[0.0, 1.0]` when blending multiple stages together, meaning the result of the multiplication of a separate light stage with a light factor will be clamped before blending it with the color map.
This implementation implements overBright in the camera shader, but to only apply this overBright to surfaces having received lights, surfaces that do not receive lights gets divided by the light factor in a way re-multiplying them cancels the division.
Stages and surfaces to be blended over other stages or surfaces are also divided to avoid multiplying multiple time the same surface, in order to have the final result being `(m * a) + b` instead of `m * (a + b)` wich would be
`(m * a) …
> renderer: implement complete overBright in GLSL and high-precision frame-buffer

- src/common/cm/cm_load.cpp
- src/engine/renderer/tr_bsp.cpp
This will be required for the overBright settings in 0.55, and is useful in many other cases.
A map's worldspawn can have something like this:
```
"mapOverBrightBits" "3"
"forceLegacyMapOverBrightClamping" "1"
```
`forceLegacyMapOverBrightClamping` makes the engine use the overbright settings we used to have until a few days ago. We have to assume that some old maps will look bad without using the legacy setting. Yet we do not want to patch the old maps' .bsp files. This PR proposes to optionally read the entities from a file `maps/<map>.ent`. If this file is present, the .bsp file's entities are ignored.
Extracting the entities from a .bsp file is easy. One method is to simply copy them with a text editor.
A test scenario for map plat23. Create a file `maps/plat23.ent`:
<details> …
> load entities string from an optional file maps/<map>.ent

- src/common/Cvar.h
- src/engine/client/cl_main.cpp
- src/engine/client/client.h
- src/engine/client/hunk_allocator.cpp
- src/engine/framework/CrashDump.cpp
- src/engine/framework/CvarSystem.cpp
- src/engine/framework/CvarSystem.h
- src/engine/framework/LogSystem.cpp
- src/engine/framework/System.cpp
- src/engine/qcommon/common.cpp
- src/engine/qcommon/net_chan.cpp
- src/engine/qcommon/q_shared.h
- src/engine/qcommon/qcommon.h
- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/server/sv_init.cpp
- src/engine/sys/sdl_glimp.cpp
- src/engine/sys/sdl_input.cpp
I am working on migrating the engine cvars from `cvar_t` to `Cvar::Cvar` with the help of a script, like I did for all gamelogic cvars. These are the first steps (written by hand except for the deleting unused cvars commit).
I tested that INIT works as expected, ROM cvars are getting set, and `rate` (a USERINFO cvar) works.
> Begin migrating engine cvars to new-style

- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_main.cpp
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_surface.cpp
Use VBOs/IBOs everywhere. Avoid unnecessary data transfers to the GPU. The ability to use client-side vertex arrays is also removed in 3.2+ core OpenGL.
`skipVBO` set by portals is never used because portal surfaces are skipped when building the world VBO, so their vbo/ibo is never set.
> NUKE client-side vertex arrays

- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
Remove some redundant code.
`cullFace` is never needed because the check against the current state is already done when comparing `culltype` to `glState.faceCulling` in GL_Cull().
> Remove redundant cullFace

- src/engine/renderer/gl_shader.cpp
UI, which is what this shader is used for, doesn't have bones (vertexSkinning). It also doesn't use .md3/.mdc (vertexAnimation is used to interpolate vertices in those formats).
I'm not entirely sure if vertexSprite is unused, so I've kept it there for now.
> Remove vertexSkinning and vertexAnimation from GLShader_generic2D

- src/engine/renderer/tr_shader.cpp
Do not collapse lightmap having custom `depthFunc`.
This fixes the glass material in USS Tremor 1.1 (regression):
```
textures/usstremor_custom_src/glass_01
{
qer_editorimage textures/usstremor_custom_src/glass_01
qer_trans 0.5
surfaceparm trans
surfaceparm lightfilter
surfaceparm alphashadow
{
map textures/usstremor_custom_src/glass_01
blendFunc GL_DST_COLOR GL_ZERO
rgbGen identity
}
{
map $lightmap
rgbGen identity
blendFunc GL_DST_COLOR GL_ZERO
depthFunc equal
}	
}
```
Before:
After:
> tr_shader: do not collapse lightmap having custom depthFunc

- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
q3map2 finds @illwieckz's names too verbose :stuck_out_tongue: 
When q3map2 sees the key "forceLegacyMapOverBrightClamping" in the worldspawn entity, it protests that it is too long and shuts down. Shorten that to "forceLegacyOverBrightClamping".
> Shorten name of light clamping worldspawn key

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/tr_main.cpp
It was missing in 1872b92274fbd9533e622633c56a515a4ff899c0 from:
- https://github.com/DaemonEngine/Daemon/pull/1045
> renderer: missing break in shadowing code and other things

- src/engine/renderer/tr_shader.cpp
Exported from:
- https://github.com/DaemonEngine/Daemon/pull/1075
This can be merged separately.
> renderer: extend missing texture logging

- src/engine/renderer/tr_shader.cpp
Also enable deluxe mapping if there is a lone specular map.
Deluxe mapping works as long as there is either a normal map or a specular map.
> renderer: also enable deluxe mapping if there is a lone specular map

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/glsl_source/depthtile1_vp.glsl
- src/engine/renderer/glsl_source/depthtile2_vp.glsl
- src/engine/renderer/glsl_source/fxaa_vp.glsl
- src/engine/renderer/glsl_source/motionblur_vp.glsl
- src/engine/renderer/glsl_source/ssao_vp.glsl
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_surface.cpp
- src/engine/renderer/tr_vbo.cpp
Part 1 of changing some 2d rendering to use static VBOs.
Changes Tess_InstantQuad() to use the same VBO and calculate the modelView matrix to get the correct quad coordinates.
This would be best moved to the world VBO, but that can be done later. Doesn't do too much on its own, but with more such changes should help performance by getting rid of some buffer uploads.
> Use static VBO for instant quad

- src/engine/framework/System.cpp
Intended to be used with a protocol handler that routes through the updater. If the updater gets the "URL" first, it can validate it so we don't need to ignore further arguments as a defense against bad input.
This improves on -connect in case the user uses the command line customization feature of the updater like %command% -foo +bar. The -connect2 arg could be inserted in %command% without cutting off the rest.
I'm intentionally leaving the original variant in; it may be useful to have both possibilities.
> Add variant of -connect command line argument that needn't be last

- src/engine/qcommon/q_math.cpp
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_shade_calc.cpp
Avoid useless pointer dereferences and let the compiler vectorize matrix copy.
> renderer,qmath: avoid useless pointer dereferences and let the compiler vectorize matrix copy

- src/engine/renderer/tr_init.cpp
I find annoying that the shortest `screenshot` command writes TGA, a format no one uses anymore to take screenshots.
I find it annoying to type `screenshotJPEG` anytime I want to take a screenshot using the command line, and the suffix prevent autocompletion to fully autocomplete it.
So, `screenshot` is now meant to use a “default format” I just decided to be jpeg, while `screenshotFORMAT` with explicit FORMAT suffix will always write screenshot in the said FORMAT.
In the future we may add a cvar to select the default format of the `screenshot` command.
> renderer: make screenshot command write jpeg

- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_shader.cpp
Something is wrong as the light is too dim, but it works.
About the wrongness, here with both map dynamic light, and weapon projectile dynamic light:
It should look like this:
> Make the legacy dynamic light renderer work again

- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_shader.cpp
Use default value from `shader_t` and `shaderStage_t`.
The clearing of the global shader may be a bit slower, but being able to rely on default values makes the code easier to write.
> renderer: use default value from shader_t and shaderStage_t

- src/engine/renderer/tr_bsp.cpp
Stops tess.vertexes from overflowing by adding all the sky surfaces to world VBO instead of doing Tess_SurfaceVertsAndTris() on them.
This essentialy moves them from RAM to VRAM. It might be better to just always draw the skybox rather than have those sky surfaces in memory.
Fixes #1096.
> Add sky surfaces to world VBO

- src/engine/renderer/tr_sky.cpp
Two commits extracted from #1099:
- https://github.com/DaemonEngine/Daemon/pull/1099
They are in fact the continuation of (already merged)  #1075:
- https://github.com/DaemonEngine/Daemon/pull/1075
> tr_sky: delete now useless tests and use pStage

- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_shader.cpp
This is not critical since it's used in debug command print functions, but why not. Those `unordered_map` are never modified so there is no need to rebuild them on every function call.
> renderer: set unordered_map static and const

- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_shader.cpp
Disable heat haze stage at load time, instead of iterating it and skipping it at render time.
> renderer: disable heat haze stage at load time

- src/engine/renderer/tr_image.cpp
I noticed it while working on #1099:
- https://github.com/DaemonEngine/Daemon/pull/1099
On other parts of the code like `tr_cmds.cpp` we already have:
```c++
image = shader->stages[ 0 ]->bundle[ 0 ].image[ 0 ];
```
And every image access are done everywhere else as `bundle[ i ].image`.
So doing `shader->stages[ 0 ]->bundle->image[ 0 ]` looks wrong and likely worked by luck.
> tr_image: correct bundle image pointer

- src/engine/renderer/glsl_source/computeLight_fp.glsl
- src/engine/renderer/glsl_source/lighttile_fp.glsl
Sets a minimum radius for light culling to avoid blocky artifacts. Still sort of a hack, but it works better than what we had.
Also made attenuation quadratic rather than linear for dynamic lights since that is more correct without broken gamma (previous incorrect lighting was essentially doing distance ^ 4.2 due to gamma correction). In the same pr because without the correct attenuation the blockiness is still there.
Before and after for light culling:
I've chosen the 2.0 * 32.0 value for the minimum radius because it fixes the blockiness issues with the smallest scale lights that we have. Simply always increasing radius results in too many tiles getting the light source.
This also fixes the same issue with https://users.unvanquished.net/~modi/res-psaw_dev%2Bishq1.dpk, however it's more …
> Fix dynamic light blockiness and strength

- README.md
I noticed the engine's README was still mentionning a C++11 compiler was needed while the Unvanquished game's README is mentionning the requirement of a C++14 compiler.
While it may be possible that the game requires an higher version than the engine, I verified and no the engine cannot run anymore if I request C++11:
```
Unvanquished/daemon/src/engine/renderer/tr_model_md5.cpp: In function ‘bool R_LoadMD5(model_t*, const char*, const char*)’:
Unvanquished/daemon/src/engine/renderer/tr_model_md5.cpp:361:39: error: ‘make_unique’ is not a member of ‘std’
361 |                 auto texCoords = std::make_unique<vec2_t[]>( surf->numVerts );
|                                       ^~~~~~~~~~~
Unvanquished/daemon/src/engine/renderer/tr_model_md5.cpp:361:39: note: ‘std::make_unique’ is only …
```
> readme: update compiler section

- README.md
Sync the recommended MinGW compiler wording with Unvanquished.
There is probably no need to mention standalone MinGW as long as we have a working recommendation.
Do we need to also recommend `base-devel`? Unvanquished was missing it.
> readme: sync the recommended MinGW compiler wording with Unvanquished

- src/engine/renderer/tr_image.cpp
- src/shared/client/cg_api.cpp
May be a better fix for:
- https://github.com/Unvanquished/Unvanquished/issues/2682
than:
- https://github.com/Unvanquished/Unvanquished/pull/2976
Being implemented in engine shared code means the crash would be prevented for any custom game.
I now wonder if we should not add such check for any other trap calls allocating a `vector` of `polyVert_t`.
> cg_api: do nothing in trap_R_AddPolysToScene if array size is zero

- src/common/System.cpp
Instead of defining custom new and delete to ensure that an allocation failure results in a fatal error with the "Out of memory", use std::set_new_handler to accomplish the same. This std lib facility allows setting a custom behavior (instead of throwing std::bad_alloc) on failure of operator new.
This is preferable since we don't have to worry about proliferation of `new` variants or messing up the sanitizers.
I tested on MSVC and Linux. The former works, while the latter gets hit by the OOM killer instead of throwing an exception as before.
> Use std::set_new_handler to send OOM message

- src/shared/client/cg_api.cpp
Fixup for:
- https://github.com/DaemonEngine/Daemon/pull/1106
Fixes this warning:
```
src/shared/client/cg_api.cpp: In function ‘qhandle_t trap_R_GenerateTexture(const byte*, int, int)’:
src/shared/client/cg_api.cpp:578:19: warning: ‘*’ in boolean context, suggest ‘&&’ instead [-Wint-in-bool-context]
578 |         ASSERT( x * y );
```
> cg_api: use && in boolean context

- src/common/cm/cm_load.cpp
- src/common/cm/cm_local.h
- src/common/cm/cm_polylib.cpp
- src/engine/client/cl_main.cpp
- src/engine/client/hunk_allocator.cpp
- src/engine/qcommon/net_chan.cpp
- src/engine/qcommon/q_shared.cpp
- src/engine/qcommon/qcommon.h
- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_curve.cpp
- src/engine/renderer/tr_font.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_image_crn.cpp
- src/engine/renderer/tr_image_dds.cpp
- src/engine/renderer/tr_image_jpg.cpp
- src/engine/renderer/tr_image_ktx.cpp
- src/engine/renderer/tr_image_png.cpp
- src/engine/renderer/tr_image_tga.cpp
- src/engine/renderer/tr_image_webp.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_public.h
- src/engine/renderer/tr_shader.cpp
- src/engine/server/server.h
- src/engine/server/sv_init.cpp
- src/engine/server/sv_main.cpp
In all malloc-wrapping functions, check the result and call Sys::Error if it is null. Replace all calls to raw malloc with the checked versions. Also git rid of some redundant `memset`s.
> Clean up malloc usage

- src/common/Compiler.h
- src/common/System.cpp
Also detect MemorySanitizer and ThreadSanitizer.
Without this, the linker complains about `new` and `delete` being redefined when linking with `-fsanitize=leak`, `-fsanitize=memory` or `-fsanitize=thread`.
Previously we were only caring about linking with `-fsanitize=address`.
> common: also do pedantic shutdown when running Clang sanitizers

- src/engine/renderer/tr_shader.cpp
I made a typo in:
- https://github.com/DaemonEngine/Daemon/pull/1098
> tr_shader: fix again the legacy dynamic light renderer

- src/common/cm/cm_local.h
- src/common/cm/cm_patch.cpp
- src/common/cm/cm_plane.cpp
- src/common/cm/cm_polylib.cpp
- src/common/cm/cm_polylib.h
- src/common/cm/cm_trace.cpp
- src/engine/qcommon/q_math.cpp
- src/engine/qcommon/q_shared.h
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_decals.cpp
- src/engine/renderer/tr_light.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_main.cpp
Previously the plane was stored in a `vec4_t`,
with the three first components being the normal,
and the last one being the distance.
A lot of code was running the `vec3_t` specific
macros on the `vec4_t`, it only worked because
we use unsafe types.
This change is a step on the road of making safe
types like `vec2_t`, `vec3_t`, `vec4_t` and turne
macros like `VectorCopy` into type-safe functions.
This also makes the code more explicit.
Instead of doing:
```c++
vec3_t normal = { 0, 0, 0 };
vec4_t plane;
VectorCopy( normal, plane );
```
We can now do:
```c++
vec3_t in = { 0, 0, 0 };
plane_t plane;
VectorCopy( normal, plane.normal );
```
The day `VectorCopy` is a type-safe function
instead of a macro, it will work.
There already exist a `cplane_t` struct
that carries `normal` and `dist` but …
> introduce `plane_t` struct with `normal` and `dist` members

- src/engine/renderer/tr_backend.cpp
Bind tr.blackImage for gl_screenShader when rendering bloom, to avoid having undefined texture data:
We've been getting lucky that we didn't have any bad texture reads, but with #1105 those sometimes happen here, likely because of bindless textures working slightly differently.
> Fix screen shader texture

- src/engine/client/cg_api.h
- src/engine/client/cg_msgdef.h
- src/engine/client/cl_cgame.cpp
- src/shared/client/cg_api.cpp
Engine counterpart of:
- https://github.com/Unvanquished/Unvanquished/pull/2981
> cg_api: implement `trap_CM_BatchMarkFragments` to process all impact marks in one call

- src/common/Cvar.cpp
- src/shared/CommonProxies.cpp
For improving the performance of Cvar::GetValue.
Also I uncovered another funny performance bug where setting a VM cvar was O(N) in the number of cvars.
> VM-side cache for cvars registered there

- src/common/Command.cpp
- src/common/System.cpp
- src/engine/qcommon/common.cpp
- src/engine/qcommon/qcommon.h
- src/shared/VMMain.cpp
Stacked (hehe) on #1063.
In #716 I removed the code for NaCl exception messages in favor of letting it crash with an nice stack trace. But we can have our cake and eat it too. Here's an example of an NaCl crash dump including the custom terminate handler (which logs the exception message), as well as the stack leading to the error below
```
Thread 0 (crashed)
0  main.nexe!abort [abort.c : 21 + 0x0]
rax = 0x0000000000000000   rdx = 0x0000000000000000
rcx = 0x000000000ffc13e0   rbx = 0x0000000000000000
rsi = 0x0000000000000000   rdi = 0x00000000fffe6d68
rbp = 0x00000000fffeff80   rsp = 0x00000000fffe6d90
r8 = 0x0000000000000000    r9 = 0x0000000000000000
r10 = 0x0000000000000000   r11 = 0x000006e700582760
r12 = 0x00000000fd3c4738   r13 = 0x00000000fffe6fa0
r14 = 0x00000000fd3d97b0   r15 = …
```
> Print NaCl exception message + fault injection command

- src/engine/qcommon/q_math.cpp
- src/engine/qcommon/q_shared.h
- https://github.com/DaemonEngine/Daemon/pull/1125
This function is heavily used in CPU culling and milking the maximum of performance from it is welcome.
Patches are meant to be squashed.
> qmath: micro-optimize the `BoxOnPlaneSide` function

- src/engine/qcommon/q_shared.h
Drop the old PowerPC `frsqrte` (Floating Reciprocal Square Root Estimate) code.
The `idppc` definition was never set and was a relic from ioq3.
PowerPC isn't supported by the engine and will probably never be.
The Apple GCC implementation of `__frsqrte` was just the same as the one that was used for GCC:
- https://opensource.apple.com/source/gcc/gcc-5363/more-hdrs/ppc_intrinsics.h.auto.html
There is no plan to support Apple 32-bit PowerPC.
The non-GCC `__frsqte` code was likely the one from XL C++ for AIX:
- https://www.ibm.com/docs/en/xl-c-and-cpp-aix/13.1.0?topic=functions-frsqrte-frsqrtes
There is no plan to support AIX.
PPC64 may be supported in the future, interest in it has been expressed as some Talos people have expressed their desire to see someone port the game to their …
> q_shared: drop the old PPC `frsqrte` code.

- src/engine/renderer/tr_bsp.cpp
Noticed in a CI log while looking for something else:
```
src/engine/renderer/tr_bsp.cpp: In function ‘std::vector<std::__cxx11::basic_string<char> > R_LoadExternalLightmaps(const char*)’:
src/engine/renderer/tr_bsp.cpp:472:22: warning: comparison of integer expressions of different signedness: ‘int’ and ‘long long unsigned int’ [-Wsign-compare]
472 |   for ( int i = 0; i < ARRAY_LEN( extensions ); i++ )
```
> tr_bsp: fix a signedness comparison problem

- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_public.h
Query the actual max amount of texture units with GL_MAX_COMBINED_TEXTURE_UNITS instead of a magic number, and use an std::vector with this capacity.
> Use the correct amount of texture units

- src/common/cm/unittest.cpp
- src/engine/framework/System.cpp
Fixes CM unit tests breaking with SSE disabled, as reported by @illwieckz.
> Fix trace tests with x87 floating point

- src/engine/qcommon/common.cpp
Let the framerate flirt with the limits.
Basically the idea is to not sleep the remaining time to fill the expected frametime, but to let enough time after sleeping to process events in a loop until the expected frametime is reached.
It makes the framerate less jaggy, and actually provides to the user what they expect.
> qcommon: let the framerate flirt with the limits

- cmake/DaemonFlags.cmake
Never use strict aliasing, do the same with nexe than with exe and dll.
Alternative to:
- https://github.com/DaemonEngine/Daemon/pull/1159
Instead of trying to always do strict aliasing, never do strict aliasing.
What matters is to have consistent behaviour, #1159 will require more testing than this one.
See:
- https://github.com/DaemonEngine/Daemon/issues/1158
> cmake: never use strict aliasing

- src/engine/renderer/tr_cmds.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_shader.cpp
- src/engine/renderer/tr_sky.cpp
Iterate shader stages directly, avoid array of pointers.
> Iterate shader stages directly, avoid array of pointers

- src/engine/renderer/tr_shader.cpp
Fix #1126:
- https://github.com/DaemonEngine/Daemon/issues/1126
While we may assume decals should not cancel overbright (the color is added to a surface that is already lit), one may investigate if other surfaces using `blendFunc GL_ZERO GL_ONE_MINUS_SRC_COLOR` while not being decals should also not cancel overbright in a more generic way.
But this is good enough for now.
> tr_shader: do not cancel overbright on decals (impact marks)

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/glsl_source/computeLight_fp.glsl
- src/engine/renderer/glsl_source/lightMapping_fp.glsl
When the legacy dynamic light renderer is enabled, this code is unused, and is likely running for nothing with some dummy texture.
This code also breaks rendering on old hardware by making the compiled shader too big for the GPU ALU, while the extra code making the compiled shader too large is not meant to be used at all.
> renderer: skip the blending of tiled dynamic lights when the legacy dynamic light renderer is enabled

- .github/workflows/codeql.yml
Sync submodule branches if branch name ends with `/sync`, like we do with azure pipelines and appveyor.
> codeql: sync submodules branches

- src/common/IPC/Primitives.cpp
Something I found while unifying compiler flags between native builds and nacl builds.
```
Unvanquished/daemon/src/common/IPC/Primitives.cpp:85:18: warning: 
unused variable 'NACL_DESC_TYPE_END_TAG' [-Wunused-const-variable]
static const int NACL_DESC_TYPE_END_TAG  = (0xff);
^
Unvanquished/daemon/src/common/IPC/Primitives.cpp:98:23: warning: 
unused variable 'NACL_HANDLE_TRANSFER_PROTOCOL' [-Wunused-const-variable]
static const uint32_t NACL_HANDLE_TRANSFER_PROTOCOL = 0xd3c0de01;
^
2 warnings generated.
```
> common/ipc: skip variables for native code on nacl

- src/engine/client/cg_api.h
- src/engine/client/cg_msgdef.h
- src/engine/client/cl_cgame.cpp
- src/shared/client/cg_api.cpp
Implement `trap_R_inPVSArray` to test array of entities in PVS in one call.
Engine sidecar of:
- https://github.com/Unvanquished/Unvanquished/pull/2679
> cg_api: implement `trap_R_BatchInPVS` to test if a bunch of entities are in PVS in one call

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/glsl_source/computeLight_fp.glsl
- src/engine/renderer/glsl_source/lighttile_fp.glsl
- src/engine/renderer/tr_image.cpp
Rework the enablement of high-precision/float texture formats according to available features and enabled options.
> renderer: rework the enablement of high-precision/float texture formats

- src/engine/client/cl_serverlist.cpp
For a server without a successful serverinfo reply, the engine would report a garbage infostring left over from the last ping query to have used the same space in the array.
> Stop reporting garbage serverinfos to cgame

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/glsl_source/generic_fp.glsl
- src/engine/renderer/glsl_source/skybox_fp.glsl
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_sky.cpp
There is no need to set the `USE_ALPHA_TESTING` macro if `GLS_ATEST_NONE` is set when there is no alpha testing to do, the alpha testing computation will just know there is nothing to do.
This reduces:
- GLSL shader permutation to build.
- GLSL shader changes between textures.
The cost of doing that addition and that test in all case in GLSL should be faster than switching back and forth to a GLSL shader permutation.
This also obviously simplifies code.
I noticed this when investigating this (it will _NOT_ fix it):
- https://github.com/DaemonEngine/Daemon/issues/1172
I noticed there was a difference between `generic` and `lightMapping` where `lightMapping` did not used on that `USE_ALPHA_TESTING` macro already.
> renderer: remove the `USE_ALPHA_TESTING` macro and build less shader permutations

- src/engine/client/cg_api.h
- src/engine/client/cl_cgame.cpp
- src/engine/null/null_renderer.cpp
- src/engine/renderer/InternalImage.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_public.h
- src/engine/renderer/tr_shader.cpp
- src/engine/renderer/tr_types.h
- src/shared/client/cg_api.cpp
Introduce `IF_FITSCREEN` to rescale image to the smaller size larger than screen.
The idea behind this feature is that we have images that should not be rescaled smaller than screen to look good:
- minimaps,
- UI background,
- levelshot,
- etc.
So for them we use `IF_PICMIP`, either directly in code, either with material keyword `nopicmip`.
But then this stupid thing happen, let's imagine someone playing on a low end device with not a lot of GPU memory and a 800×600 screen:
```
]/listImages
------------------------------------------------------------------
num   width heigth layers mm  type format   wrap.t   wrap.s   name
------------------------------------------------------------------
63      100   2230      1 no  2D   DXT5     t.clmp   s.clmp   ui/assets/background/bg
64       20 …
```
> renderer: introduce `IF_FITSCREEN` and `RSF_2D`

- src/engine/qcommon/q_math.cpp
- src/engine/qcommon/q_shared.h
- src/shared/client/cg_api.cpp
The point of this is to prevent the arguments from being evaluated multiple times. In the commit message I give an example of this happening in cgame.
Also it can be useful for assigning a temporary GLM vector to a vec3_t. This is one more GLM/vec3_t adaptor we need in addition to [GLM4READ and GLM4RW](https://github.com/Unvanquished/Unvanquished/pull/3021). I was motivated to make this branch upon seeing, in a GLM conversion branch, VectorCopy used to assign a function's GLM return value to a vec3_t (heretofore a bad idea as the function is called 3 times).
> Convert vector macros to template functions

- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_public.h
- src/engine/renderer/tr_shade.cpp
- src/engine/sys/sdl_glimp.cpp
Use `GL_DEPTH_CLAMP` only if `GL_ARB_depth_clamp` is available.
The `GL_ARB_depth_clamp` extension was only made required in OpenGL 3.2.
> renderer: use `GL_DEPTH_CLAMP` only if `GL_ARB_depth_clamp` is available

- src/engine/renderer/tr_shader.cpp
Fixes #1185:
- https://github.com/DaemonEngine/Daemon/issues/1185
Alongside fixing #1185, this is something I wanted to do anyway, in order to move the next `for` loop after the first `GroupActiveStages` call to a dedicated function (this is a code validating shader stages and disabling invalid ones).
The bug is that we are now more agressive at disabling unsupported stages as soon as possible, and the stage validation code was stoping iterating the stages on first disabled stage found.
The material looks like this:
```
tremor/54ECD65C96E1201DEABD3DDB5B656605
{
{
map $lightmap
rgbGen identity
}
// Q3Map2 custom lightstyle stage(s)
{
map $lightmap
blendFunc GL_SRC_ALPHA GL_ONE
rgbGen wave sawtooth 0 1 0 0.5 // style 1
tcGen lightmap
tcMod transform 1 0 0 1 0.45410 0.18457
}
{
map …
```
> tr_shader: always iterate grouped stages

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/glsl_source/computeLight_fp.glsl
- src/engine/renderer/glsl_source/debugShadowMap_fp.glsl
- src/engine/renderer/glsl_source/forwardLighting_fp.glsl
- src/engine/renderer/glsl_source/lighttile_fp.glsl
- src/engine/renderer/glsl_source/shadowFill_fp.glsl
- src/engine/renderer/tr_public.h
- src/engine/sys/sdl_glimp.cpp
- trust `GLimp_InitExtensions` and deduplicate the code
- unify the way to tell an extension is available
> renderer: rewrite the GLSL extension enablement

- src/engine/qcommon/q_shared.h
Delete unused `IS_NAN`.
One should prefer using `!Math::IsFinite` instead.
> q_shared: delete unused IS_NAN

- src/engine/renderer/gl_shader.cpp
Picked from #1105.
Adds the ability to insert text from a specified glsl shader file into an arbitrary place in another shader.
> Add #insert directive for glsl shaders

- cmake/DaemonArchitecture.cmake
- cmake/DaemonFlags.cmake
- src/common/Compiler.h
- src/common/Platform.h
- src/engine/qcommon/q_math.cpp
- src/engine/qcommon/q_shared.h
This introduces the `USE_ARCH_INTRINSICS` CMake option. It is enabled by default.
Disabling it is meant to disable custom asm code and usage of intrinsincs functions for the target platform in the Dæmon code base, it may also be used by games built with the Dæmon common code base.
It is not meant to disable asm or intrinsincs usage in third-party libraries.
It is not meant to prevent the compiler to use such intrinsics in its optimization passes.
It is not meant to disable the compiler flags we set to tell the compiler to try to use such intrinsics in its optimization passes. For this, one should disable `USE_CPU_RECOMMENDED_FEATURES` instead.
For obvious reason the asm code in the `BREAKPOINT()` implementation is not meant to be disabled by `USE_ARCH_INTRINSICS`, the alternate code is to …
> cmake: add `USE_ARCH_INTRINSICS` and `USE_COMPILER_INTRINSICS` CMake options

- cmake/DaemonFlags.cmake
When `-pie` isn't supported, `FLAG_LINKER_PIE` isn't set and this line errors out because `if(AND MINGW)` is a syntax error.
This is a fix similar to #1157:
- https://github.com/DaemonEngine/Daemon/pull/1157
> cmake: empty string is not missing token (2)

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_public.h
- src/engine/sys/sdl_glimp.cpp
Requires #1124.
Cherry-picked from #1137 to split a large pr up a bit.
Adds some code to allow using compute shaders. Shaders can now have either of vertex, fragment, or compute shaders enabled/disabled.
> Implement compute shaders support, make fragment shader non-mandatory

- src/engine/renderer/tr_model_iqm.cpp
A regression in 3b2dda7bb71d5bb4716a745fd44415dba7a9a6f4, which affected IQMs without a weights section,
caused alien missiles to be invisible.
> Fix regression with IQM without weights

- src/engine/renderer/tr_shade.cpp
It is not implemented yet and the shader permutation is disabled.
It now makes possible to run `buildcubemaps` command even when there are PBR materials in the scene, to not crash while attempting to render those PBR materials with a shader permutation that doesn't exist.
To test the reflective specular code, one should:
- load a map with specular maps
- have `r_smp` disabled (there are some crashes when generating cubemaps otherwise)
- type `/buildcubemaps` in console
The rendering is assumed to be wrong (it blinks to black), but the `buildcubemaps` command runs.
> tr_shade: do not use reflective specular code on PBR material

- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_scene.cpp
This will ensure that only the main view computes dynamic lights. Fixes dynamic light disappearing near portals.
This does mean that dynamic lights won't render in portals, but that was already the case anyway, and fixing that would require more complex changes, which would be unlikely to be noticeable.
> Only do RB_RenderPostDepthLightTile() for the main view

- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_public.h
- src/engine/sys/sdl_glimp.cpp
Port GL extension cvars to new style format.
@slipher I have no idea is the `Cvar::Unlatch` implementation is correct.
> renderer: port GL extension cvars to new style format

- src/engine/qcommon/q_shared.h
MinGW was using _vsnprintf and _snprintf, which are broken in all versions of the Windows standard library (even ones that have a fixed snprintf and vsprintf).
> Fix bad (v)snprintf on MinGW

- src/engine/renderer/glsl_source/computeLight_fp.glsl
Looking at
https://github.com/Nadrin/PBR/blob/master/data/shaders/glsl/pbr_fs.glsl, this repo does PBR slightly differently. In general, the calculations are similar until they come to adding it to the color. This change ported from this renderer appears to help remove black artifacts.
> pbr: Maybe fix weird dark artifacts in PBR

- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_main.cpp
- src/engine/renderer/tr_scene.cpp
Do `RenderPostDepthTile()` once after depth pre-pass of the first view that doesn't have any nested views. Fixes the issue in #1212.
> Fix post-deph lighttile

- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_model_md3.cpp
- src/engine/renderer/tr_model_skel.cpp
- src/engine/renderer/tr_surface.cpp
- src/engine/renderer/tr_vbo.cpp
Fixes #1196.
Also adds a check to detect requesting vertex attributes which are not provided by a VBO.
> Fix generic quad verts being added to other surfaces

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/glsl_source/ssao_fp.glsl
- src/engine/renderer/glsl_source/ssao_vp.glsl
- src/engine/renderer/tr_backend.cpp
Change unprojectionParams to be a uniform, take map inverse light factor into account when setting the buffer clear colour for `r_ssao < 0`, minor formatting fixes. Removed unused variables and the preprocessor check for GLSL version > 1.20, since there's already a preceding check for `GL_ARB_texture_gather`, which requires version 1.30.
> Minor fixes and improvements to ssao

- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_sky.cpp
Clear color buffer but nothing else, even if `r_clear` is disabled, there can be issues when enabling complete clearing by default
with Nvidia proprietary drivers. So clearing the color buffer there prevents void effect in skipped sky without needing to enable `r_clear`.
Anyway, we may want to do it (and even force a color) on purpose, this would mean clearing is the explicit way to draw the fast sky.
This makes possible to workaround #472 by keeping `r_clear` disabled while clearing the color buffer when `r_fastsky` is enabled but not clearing other buffers (because disabled `r_clear`).
This **DOES NOT** fix #472. We still have to figure out why we get what looks like precision loss on Nvidia proprietary driver.
> tr_sky: clear color buffer when fastsky is enabled, do not clear screen by default

- src/common/Cvar.h
- src/common/FileSystem.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/tr_shader.cpp
hOw DiD wE mIsSeD tHaT fOr So lOnG? 🤔️
> use explicit wording for reading cvar value

- src/engine/renderer/TextureManager.cpp
- src/engine/renderer/TextureManager.h
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_local.h
This `glew.h` include without the `GLEW_NO_GLU` define broke the docker-based release script:
```
In file included from /Unvanquished/daemon/src/engine/renderer/TextureManager.h:40,
from /Unvanquished/daemon/src/engine/renderer/tr_local.h:34,
from /Unvanquished/daemon/src/engine/renderer/gl_shader.h:26,
from /Unvanquished/daemon/src/engine/renderer/gl_shader.cpp:25:
/Unvanquished/daemon/external_deps/linux-amd64-default_10/include/GL/glew.h:1219:14: fatal error: GL/glu.h: No such file or directory
^~~~~~~~~~
compilation terminated.
```
> renderer: our usage of GLEW doesn't require GLU

- src/engine/renderer/tr_init.cpp
Fixes an issue that was preventing `r_ssao < 0` from working correctly when switching maps.
> Properly reset glState

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/glsl_source/portal_fp.glsl
- src/engine/renderer/glsl_source/portal_vp.glsl
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_main.cpp
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_shader.cpp
I don't claim it is working, but we need this to make it work.
We can notice the current code computes the distance to portal in fragment shader, but ioq3 does it in vertex shader, and it's probably faster to do it once per vertex than once per pixel, but this is a good start.
I'm not sure the existing GLSL code is correct, but the GLSL code will not run without those patches anyway.
The ioq3 code also does the range compute in the `generic` shader and at some point we may want to do the same as there may be other needs for doing blend operations according to distance, but yet again, we can look small and do small steps after small steps.
> Implement alphaGen portal

- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_shade.cpp
Skip compiling GLSL shaders that are unused, it not only speeds-up game loading, but also enables the engine to run on lower device not supporting some GLSL shaders when the related functions are disabled (bloom, etc.).
> tr_shade: do not compile unused GLSL shaders

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_public.h
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_shader.cpp
- src/engine/sys/sdl_glimp.cpp
Query some hardware limits like tex indirections and tex ALU instructions when possible.
The mechanism is only available on non-Core OpenGL profile, and hardware having low limits and requiring those checks don't support Core profile so it's fine if we don't check the limits on hardware with Core profile.
For reference an ATI R300 prints:
```
GL_MAX_PROGRAM_NATIVE_TEX_INDIRECTIONS_ARB: 16
GL_MAX_PROGRAM_NATIVE_ALU_INSTRUCTIONS_ARB: 64
```
An Intel GMA 3 prints:
```
GL_MAX_PROGRAM_NATIVE_TEX_INDIRECTIONS_ARB: 4
GL_MAX_PROGRAM_NATIVE_ALU_INSTRUCTIONS_ARB: 64
```
And an AMD RDNA3  (Radeon PRO W7600) prints (once GL 3 compatible context is forced):
```
GL_MAX_PROGRAM_NATIVE_TEX_INDIRECTIONS_ARB: 16384 
GL_MAX_PROGRAM_NATIVE_ALU_INSTRUCTIONS_ARB: 16384 
```
The idea is to automatically disable …
> renderer: query tex indirections and ALU instructions when possible

- src.cmake
- src/engine/renderer/Material.cpp
- src/engine/renderer/Material.h
- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/glsl_source/cull_cp.glsl
- src/engine/renderer/glsl_source/depthReduction_cp.glsl
- src/engine/renderer/glsl_source/lightMapping_fp.glsl
- src/engine/renderer/glsl_source/processSurfaces_cp.glsl
- src/engine/renderer/shaders.cpp
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_main.cpp
- src/engine/renderer/tr_public.h
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_vbo.cpp
- src/engine/sys/sdl_glimp.cpp
Implement occlusion culling in compute shaders using a Hierarchical Depth-Buffer.
The depth buffer is processed before the post-processing pass, reducing it to the next mip level until a 1x1 resolution is reached.
Then it's used to find out if a surface that passed frustum culling is behind some opaque surfaces. This is done by getting the screen-space AABB from the bounding sphere of the surface, and then comparing its depth to the depth in the appropriate level of the depth-reduction image. The level of the depth image is chosen based on how much of the screen space it's taking up.
> Material system: Implement GPU occlusion culling

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/glsl_source/fogQuake3_vp.glsl
- src/engine/renderer/glsl_source/forwardLighting_fp.glsl
- src/engine/renderer/glsl_source/forwardLighting_vp.glsl
- src/engine/renderer/glsl_source/fxaa_fp.glsl
- src/engine/renderer/glsl_source/heatHaze_fp.glsl
- src/engine/renderer/glsl_source/heatHaze_vp.glsl
- src/engine/renderer/glsl_source/lightMapping_fp.glsl
- src/engine/renderer/glsl_source/lightMapping_vp.glsl
- src/engine/renderer/glsl_source/liquid_fp.glsl
- src/engine/renderer/glsl_source/reflection_CB_fp.glsl
- src/engine/renderer/glsl_source/reflection_CB_vp.glsl
- src/engine/renderer/glsl_source/shadowFill_vp.glsl
Switch ones that can be easily changed. Other shaders might require some extra effort to switch, before vertex/fragment libs can be removed completely.
This is part of a change to move all shaders to use #insert instead of vertex/fragment libs, since that would allow to simplify code and because #insert is a more powerful tool.
> Switch most vertex/fragment libs to use #insert instead

- src/engine/null/null_renderer.cpp
On master ttyclient crashes due to dummy renderer functions for 'set matrix transfom' not being provided.
> Fix crashing ttyclient (missing null renderer bits)

- src/engine/framework/System.cpp
Some context: the flatpack uses a patch to suppress the warning, this commit upstreams the patch.
Slipher seems to be ok with this patch: https://github.com/Unvanquished/updater/issues/95#issuecomment-2223449484.
This patch is currently [added manually in the flatpack](https://github.com/flathub/net.unvanquished.Unvanquished/blob/0217843/0001-Suppress-a-warning.patch), and can be dropped after this is merged.
> Suppress a warning with -connect when no argument are provided

- src/engine/renderer/Material.cpp
- src/engine/renderer/Material.h
- src/engine/renderer/gl_shader.h
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_main.cpp
- src/engine/renderer/tr_shader.cpp
Builds on #1180
Avoid culling the same surface twice, which is especially important for occlusion culling since it reduces the amount of texture accesses by half. Also changed material generation a bit to make it easier to add non-world surfaces later.
> Material System: Make depth pre-pass surfaces into stages of the main surface

- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_cmds.cpp
Make the in-game videos show up again. Regression in f960177aba3c68e17e8ebfc865e8e8682268667a related to bindless texture changes.
Videos still don't work if bindless textures are enabled.
> Fix videoMap regression

- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/sys/sdl_glimp.cpp
Use the core extension, which is more widely supported, switch the cvars to new-style. Also removed the cheat flag as it made no sense there.
> Some improvements to r_glDebugProfile/r_glDebugMode

- src/engine/renderer/tr_shade.cpp
- src/engine/sys/sdl_glimp.cpp
- make r_debugSort work instead of crashing
- severity-level filtering for GL debug messages
> Renderer debugging: fix r_debugSort; filter r_glDebugProfile messages

- src/engine/renderer/tr_main.cpp
This bug was revealed by the map https://users.unvanquished.net/~kai/map-test-portals-moving_0.1.dpk.
Current behaviour on `for-0.55.0`:
With this pr:
I've also cleaned up both `PortalOffScreenOrOutOfRange()` and `R_GetPortalOrientations()` a bit, and added some comments for the rotation code.
> Fix moving portal surfaces, cleanup portal code a bit

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/glsl_source/computeLight_fp.glsl
- src/engine/renderer/glsl_source/lightMapping_fp.glsl
- src/engine/renderer/tr_shade.cpp
- use `glConfig.*` instead of `r_*` when exists as the features can now be disabled when the hardware doesn't support it,
this is a fixup for: https://github.com/DaemonEngine/Daemon/pull/1228
- more unused GLSL permutation detection,
- disable normal, specular and physical mapping when deluxe mapping is disabled,
- do not sample dummy material map when feature is disabled,
some low-end hardware have a low amount of texture fetches, so we better avoid that if possible,
- produce smaller GLSL files, do not allocate unused structures,
- also reorganize a bit the code.
> Some fixes and optimizations in the renderer

- src/engine/renderer/Material.cpp
- src/engine/renderer/Material.h
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shader.cpp
That part of the Material code seems to be stable enough to start mutualizing some logic with the non-Material code.
The various `ProcessMaterial*`, `BindShader*` and `UpdateSurfaceData*` functions are selected at the same time the `Render_*` functions are, at q3shader parsing time.
This deduplicates many `switch` boilerplate and reduce risks to introduce discrepancies in the future when modifying some parts of the code and forgetting to report the same change everywhere else.
> Deduplicate Material renderer function selection

- src/engine/renderer/Material.cpp
- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/glsl_source/computeLight_fp.glsl
- src/engine/renderer/glsl_source/lightMapping_fp.glsl
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_fbo.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_main.cpp
- src/engine/renderer/tr_public.h
- src/engine/renderer/tr_scene.cpp
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_shader.cpp
- src/engine/renderer/tr_vbo.cpp
renderer: make `r_dynamicLight` only enable a kind of light and `r_realtimeLighting` enable the renderer
With that change,
- `r_realtimeLighting` enables the rendering of dynamic lights
- `r_realtimeLightingRenderer` selects the dynamic light renderer
- `r_dynamicLight` enables the non-static kind of dynamic lights (weapons, particles…)
- `r_staticLight` enables the static kind of dynamic lights (static map lights)
---
_Original post (obsolete):_
Make r_dynamicLight only enable the related renderer, not a kind of light.
With that change,
- r_dynamicLight enables the dynamic light renderer
- r_animatedLight enables the “animated” kind of dynamic lights (weapons, particles…)
- r_staticLight enables the “static” kind of dynamic lights (static map lights)
The animated/static light naming …
> renderer: make r_dynamicLight only enable the related renderer, not a kind of light

- src/engine/renderer/Material.cpp
- src/engine/renderer/Material.h
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_main.cpp
Fixes bug (1) described on https://github.com/DaemonEngine/Daemon/issues/1259: in many maps some of the surfaces are at times absent from the material system's buffer of world surfaces.
Plus a couple of small cleanup commits.
> Fix material system missing surfaces bug

- src/engine/server/sv_snapshot.cpp
Disables PVS checking when transmitting entities to clients.
sv_novis was documented at
https://wiki.unvanquished.net/wiki/Testing/Maps, but it turns out such a cvar has never existed. I wanted to use it, so I made it real.
> Add sv_novis to disable server PVS checks

- src/engine/renderer/Material.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shade_calc.cpp
- src/engine/renderer/tr_shader.cpp
As far as I know,
- `expression_t` is always allocated as part of structs (`texModInfo_t`, `shaderStage_t`),
- `ext->numOps` is always `0` if `ext` is invalid.
> renderer: expression_t is always allocated as part of structs, ext->numOps always 0 if ext is invalid

- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_public.h
- src/engine/sys/sdl_glimp.cpp
Use `GL_ARB_internalformat_query` to check if the hardware cannot blend `GL_RGBA16` framebuffers.
Hardware like ATI R300 support RGBA16 framebuffers but can't blend them. The check should detect them.
Unfortunately the Mesa r300 driver has a bug and wrongly reports such blending to be possible despite the hardware not supporting it, but since we already detect R300 hardware we can also workaround that so a workaround was also implemented.
A fix is on the way on Mesa side.
See this thread for details:
- https://gitlab.freedesktop.org/mesa/mesa/-/issues/11669
See also this is work-in-progress merge-request on Mesa side:
- https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/30612
The extension to check for the feature availability is much more recent than the feature itself:
- …
> renderer: detect if hardware cannot blend RGBA16 framebuffers

- src/engine/renderer/Material.cpp
- src/engine/renderer/ShadeCommon.h
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shade.cpp
Another effort to mutualize code between the non-Material renderer and the Material one.
- Mutualize `SetLightDeluxeMode`, `SetLightMap`, and `SetDeluxeMap`.
- Rewrite `SetRgbaGen` as `SetRgbGen` and `SetAlphaGen`.
> Mutualize SetLightDeluxeMode, SetLightMap, and SetDeluxeMap

- src/engine/renderer/tr_bsp.cpp
Do not load deluxe maps if deluxe mapping was disabled because of hardware being incompatible.
Fixup for #1229:
- https://github.com/DaemonEngine/Daemon/pull/1229
The engine now knows how to disable deluxe mapping when the r_deluxeMapping cvar is enabled while the hardware is known to not be able to support the feature.
The renderer always loaded the deluxe maps when that cvar was enabled and told the renderer the feature was available, meaning it would select the deluxe mapping shader while it has never been built if the hardware doesn't support the feature.
> tr_bsp: do not load deluxe maps if deluxe mapping was disabled because of hardware being incompatible

- src/engine/renderer/Material.cpp
- src/engine/renderer/Material.h
- src/engine/renderer/glsl_source/cull_cp.glsl
- src/engine/renderer/glsl_source/processSurfaces_cp.glsl
Since we always set `instanceCount = 1` and `baseVertex = 0`, we don't need to put those into the `surfaceCommands` buffer.
Use a macro to get the correct uvec2 part of the uvec4 array to avoid adding padding.
This slightly improves performace since there's less memory to fetch/write.
> Optimize material compute

- src/engine/renderer/Material.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_shader.cpp
In #1162 I made sure decals are not cancelling overbright, this was to fix impact marks being too faint:
- https://github.com/DaemonEngine/Daemon/pull/1162
In fact only blended decals should not cancel overbright, opaque decals are like any fullbright surface and should then cancel overbright.
The commit also rewrites a bit the code in a better way.
In the future I may rewrite that with a more theoretical operation (based on which blending is an addition, which one is a multiplication, etc. as it's basically a commutativity/associativity problem), but for now listing the various known use cases makes easier to know what is expected. This is good enough for now.
> renderer: cancel overbright on opaque decal

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/glsl_source/processSurfaces_cp.glsl
- src/engine/renderer/tr_public.h
- src/engine/sys/sdl_glimp.cpp
Builds on #1284.
Replace per-lane atomic increment with a subgroup scan + one atomic add per subgroup, if they're available. This slightly increases performance.
> Use shader subgroup operations if available

- src.cmake
- src/engine/renderer/Material.cpp
- src/engine/renderer/Material.h
- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/glsl_source/clearSurfaces_cp.glsl
- src/engine/renderer/glsl_source/common_cp.glsl
- src/engine/renderer/glsl_source/cull_cp.glsl
- src/engine/renderer/glsl_source/depthReduction_cp.glsl
- src/engine/renderer/glsl_source/processSurfaces_cp.glsl
- src/engine/renderer/shaders.cpp
Builds on #1285.
Add `common_cp` shader. This shader is for use with #insert in other compute shaders, and contains a few #define's and structs that are shared between shaders, as well as #define's for workgroup and invocation ID's.
Don't actually add `surfaceCommand` 0, just do `-1` when adding the command. Simplify some code a bit, remove `culledCommandsOffset`.
Replace `MAX_FRAMES * MAX_VIEWS` with `MAX_VIEWFRAMES`.
> Some more material cleanup

- src/engine/renderer/tr_main.cpp
It looks like merge commit 2ea20a9f29ac4f0b886d001accadc8eadad19a47 was wrong and left this change aside.
Hopefully fixes #1297:
- https://github.com/DaemonEngine/Daemon/issues/1297
----
Fix portal scissor test
Width and height in glScissor() must not be negative, so if surfRect has lower x2 or y2 than x1 or y1, then flip the scissor parameters.
> Reimport a mismerged fix

- src/engine/renderer/tr_init.cpp
Most of our heightmaps come from Xonotic which are supposed to use DarkPlaces 0.02 default relief depth scale. It's easier for use to align with that default than to convert any height map with import from Xonotic. Our heightmaps are actually wrong without this.
I haven't seen any relief mapping code after a quick search in ioq3, so we're not breaking any usage but we may actually be defining the standard instead. If we are in position to set the standard for idtech3 games, better align with friendly projects like Xonotic/DarkPlaces.
> tr_init: set default r_reliefDepthScale to 0.02 like DarkPlaces

- src/engine/renderer/tr_image.cpp
Fixes a regression introduced in 7e7cb4f43e4fabdf54b7b3830e01ee362665fe3f.
Fixes #1258.
Before:
After:
Reference (0.51.2):
> Fix fog image

- src/engine/renderer/glsl_source/computeLight_fp.glsl
- src/engine/renderer/glsl_source/lightMapping_fp.glsl
Fix compilation when `r_highPrecisionRendering` is disabled.
I don't know if the fix is right, but it fixes building the `lightMapping` GLSL and I see no visual bugs.
What makes me doubt is that I replace a `sampler3D` with an `usampler3D` but I don't know the difference.
This fixes a bug introduced in f960177aba3c68e17e8ebfc865e8e8682268667a from #1105:
- https://github.com/DaemonEngine/Daemon/pull/1105
> computeLight_fp: fix compilation when r_highPrecisionRendering is disabled

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_sky.cpp
Skybox is rendered with a mesh that has only position, so it can't be used with generic shader. Fixes the log spam and correctly shows where the skybox tris are.
Also remove GLDeformStage from skybox.
> Fix skybox debug draw

- src/engine/renderer/tr_fbo.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shade.cpp
- Delete some images/FBO that are never used.
- Only generate some images/FBO when they are used.
- Also latch `r_noFog` since the GLSL shader since shader is built conditionally after https://github.com/DaemonEngine/Daemon/pull/1228
> Only generate some images/FBO when they are used

- src/engine/client/cl_main.cpp
Previously, it only restarted if you were in a game. So if you were in the main menu, the music would stop playing. Pretty unhelpful if you are trying to fix your sound...
> snd_restart: always restart the cgame

- src.cmake
- src/engine/renderer/DetectGLVendors.cpp
- src/engine/renderer/DetectGLVendors.h
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_public.h
- src/engine/sys/sdl_glimp.cpp
Detect OpenGL hardware and driver vendor.
Start to reuse this information.
I wanted to do that for a long time, thought about it some days ago yet again, and @VReaperV is facing the same need for #1241:
- https://github.com/DaemonEngine/Daemon/pull/1241
It may reused for more stuff in the future, especially in #1224:
- https://github.com/DaemonEngine/Daemon/pull/1224
We may also implement specific workarounds for when the OpenGL driver is a software rasterizer (not rare when virtualizing), for example our own CPU model animation code may be faster than Mesa emulating the features. That's why I make a difference between slow emulation (`SOFTWARE`) and fast one (`TRANSLATION`).
I used this as a reference:
- https://opengl.gpuinfo.org/displaycapability.php?name=GL_VENDOR
I may add more in …
> renderer: detect OpenGL hardware and driver vendor

- src/common/System.cpp
- src/common/System.h
- src/engine/framework/System.cpp
- src/engine/sys/sdl_glimp.cpp
So, I'm thinking about it for years now, probably since the current implementation of the nvidia 340 workaround:
- https://github.com/DaemonEngine/Daemon/pull/370
I even discussed it there:
- https://github.com/DaemonEngine/Daemon/issues/360
The idea is to selectively disable a workaround we implement, to be able to test the code without it.
This is especially useful when bisecting a bug in some underlying tech like a driver, to make sure we actually test the feature in the way we expect it to fail if the third-party bug is still there.
For now I go with a dot-based hierarchy (there is no legacy cvar to mimic), and I currently use the `renderer.workaround.<whatIsDone>.<whenItIsRequired>` naming scheme.
For example `renderer.workaround.noTexturGather.nvidia340` disables …
> sys: add `workaround.*` cvars to disable workarounds

- CMakeLists.txt
Add `USE_EXTERNAL_DEPS` option to prevent the download of `external_deps` packages at build time.
It's up to the user to know what he is doing and to provide everything he needs when he disables this option.
> cmake: add USE_EXTERNAL_DEPS option to prevent the download of external_deps packages at build time

- src/engine/renderer/glsl_source/reliefMapping_fp.glsl
This can slightly increase performance if the shader compiler isn't optimising out the rest of the loop already.
> Add missing `break;` to reliefMaping_fp

- src/engine/sys/sdl_glimp.cpp
Rename `r_ext_half_float_pixel` as `r_arb_half_float_pixel`
ARB is actually part of the name.
> sdl_glimp: rename `r_ext_half_float_pixel` as `r_arb_half_float_pixel`

- src/engine/renderer/tr_shader.cpp
When the game code requests the engine to load a texture and sets the `RSF_FITSCREEN` or the `RSF_NOMIP` flag, it was only used on images without shaders.
> tr_shader: transmit `RSF_FITSCREEN` and `RSF_NOMIP` flag from gamecode to shaders

- src/engine/renderer/Material.cpp
- src/engine/renderer/Material.h
- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/glsl_source/cull_cp.glsl
- src/engine/renderer/glsl_source/generic_fp.glsl
- src/engine/renderer/glsl_source/lightMapping_fp.glsl
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_vbo.cpp
Add an `r_showGlobalMaterials` cvar that allows visualising material system materials by color-coding surfaces, in 3 different modes: depth, opaque, opaque + transparent.
Add `r_showTris` to `gl_genericShaderMaterial`.
Add `r_materialDebug` cvar to allow to quickly add debug output to shaders. This is intended for use with compute shaders and Nsight Graphics (due to formatting interface).
> Material debug improvements

- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_local.h
- src/engine/sys/sdl_glimp.cpp
Some renderer debug logs I needed to debug things:
- sdl_glimp: tell if used extension is required or optional
When it is suspected an extension may be buggy, it is useful to know which ones are optional so one can disable them to verify the assumption.
- renderer: add more debug log about image creation
When the OpenGL driver reports errors when creating or uploading an image, it's useful to have such debug logs to know exactly which image failed, just by reading the immediate previous line. It is useful to identify which image format may be broken in an OpenGL driver.
> More renderer debug logs

- src/engine/framework/System.cpp
The noreturn made std::thread(SignalHandler) not compile
> Fix compilation with gcc 8.3

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
Parse info logs on shader compilation failure in an implementation-dependent way, which poduces an output like this:
```
136: 	vec4 color;
137: 	vec2 texCoord, lmCoord;a
138: 
139: 	VertexFetch( position, LB, color, texCoord, lmCoord );
------	-----------^-------------------------------------------------------
0(139) : error C0000: syntax error, unexpected '(', expecting "::" at token "("
140: 	color = color * u_ColorModulate + u_Color;
```
If the exact character is not known, the line will just be like "^^^^^^^^^^".
Also reorganised some code a bit due to changes. Removed `BuildGPUShaderText()` since it was just unnecesserily fragmenting the code at this point.
> Improve shader logging

- src/engine/sys/sdl_glimp.cpp
Add `r_arb_framebuffer_object` cvar, I noticed it was missing when debugging something. Having it makes easy to test the workaround.
> sdl_glimp: add r_arb_framebuffer_object cvar

- src/engine/framework/VirtualMachine.cpp
Add workaround cvars that can be set to `off` to not disable platform qualification on armhf or FreeBSD.
It makes possible to check if the platform qualification works on a specific arm CPU, or to test if Linuxulator has improved enough to support what's required to run platform qualification though the Linux compatibility layer.
Also add a commit to run `nacl_loader` on FreeBSD Linuxulator the same way it runs on Linux (using the helper).
I don't know why the helper is needed on Linux:
- https://github.com/DaemonEngine/Daemon/issues/1327
but we better do the same as Linux on Linuxulator for consistency.
> VirtualMachine: add workaround cvars for not disabling platform qualification on arm64 or FreeBSD, and more

- src/common/System.cpp
- src/common/System.h
- src/engine/sys/sdl_glimp.cpp
Rewrite a bit some GL extension and workaround detection. This basically unify the wording of both logs and the way it is implemented.
> sdl_glimp: rewrite a bit some GL extension and workaround detection

- src/engine/renderer/tr_shader.cpp
All of the heat haze shaders in our weapon assets suffer from having a wrong sort order value (SS_OPAQUE). Only some more or less worked, due to the luck of being drawn later than most other opaque surfaces. It would seem the first properly working heat haze shader in our project was https://github.com/UnvanquishedAssets/map-plat23_src.dpkdir/pull/1: this shader received a SS_BLEND0 sort due to other stages.
Targeting 0.55 since some suddenly-visible assets probably need to be fixed. The Lucifer Cannon secondary fire impact looks stupid: the impacted surface suddenly assumes a distorted aspect, then 3 seconds later snaps back to normal.
> Fix heat haze shaders not rendered due to bad sorting

- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_model_iqm.cpp
- src/engine/renderer/tr_model_md3.cpp
- src/engine/renderer/tr_model_md5.cpp
- src/engine/renderer/tr_model_skel.cpp
- src/engine/renderer/tr_public.h
- src/engine/renderer/tr_surface.cpp
- src/engine/renderer/tr_vbo.cpp
- src/engine/sys/sdl_glimp.cpp
Choose vertex attribute layouts at runtime. For attributes designated as wanting half float, use half float if GL_ARB_half_float_vertex is available or full-sized float otherwise,  #1179 explains the situation in detail.
TODO: grab the commit adding a *workaround* for the cards that support the half float vertex extension, but with poor quality of implementation.
The first 4 commits are from #1341.
> Runtime VBO layout: make half float usage optional

- src/engine/renderer/tr_shader.cpp
The stahl map have those materials:
```
textures/stahl/sfx_05_blue
{
qer_editorimage textures/stahl/sfx_05b_blue
cull none
surfaceparm nodlight
surfaceparm nolightmap
surfaceparm nonsolid
surfaceparm trans
qer_trans 0.75
{
map textures/stahl/sfx_05b_blue
blendFunc add
}
glowmap textures/stahl/sfx_05b_blue
}
textures/stahl/sfx_05_red
{
qer_editorimage textures/stahl/sfx_05b_red
cull none
surfaceparm nodlight
surfaceparm nolightmap
surfaceparm nonsolid
surfaceparm trans
qer_trans 0.75
{
map textures/stahl/sfx_05b_red
blendFunc add
}
glowmap textures/stahl/sfx_05b_red
}
```
You see they both use a legacy doom3-like glow map stage after a legacy quake3-like color map.
For some unknown reasons we fail to collapse the glow map with the color map.
Collapsing this glow map with the color map may …
> tr_shader: use dummy stage renderer if stage cannot be rendered, fix crash with stahl map

- src/engine/renderer/Material.cpp
- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/glsl_source/computeLight_fp.glsl
- src/engine/renderer/glsl_source/lightMapping_fp.glsl
- src/engine/renderer/glsl_source/lighttile_fp.glsl
- src/engine/renderer/glsl_source/material_fp.glsl
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_vbo.cpp
- Removed the non-UBO and non-integer texture code paths. The non-UBO and non-integer texture code was supposed to be used when those extensions are not available, however:
1. These extensions are available on nearly all hardware nowadays. These extensions became core in 3.1 as well.
2. Hardware that doesn't support those extensions probably won't be using `r_realtimeighting on` anyway due to performance reasons.
3. These old code paths were broken.
- Made the way light IDs are stored in the lighttile texture sane: this was a mess of bitwise operations and strange ways of storing the ID by putting different bits into different parts of a uvec4. Now this will just store each 8-bit ID consecutively.
- Cleaned up the code in `lighttile_fp` and `computeLight_fp`.
> Tiled renderer improvements

- src/engine/renderer/tr_init.cpp
- src/engine/sys/sdl_glimp.cpp
Import from:
- https://github.com/DaemonEngine/Daemon/pull/1179
> Detect RV300 and VC4 hardware and disable slow half float vertex on them

- src/engine/client/cl_keys.cpp
Decide whether to process binds based on the key catcher state before the key down event(s) are processed, not after. This is important to avoid double-processing a key if the UI turns off its key catcher in response to a key press.
Fixes https://github.com/Unvanquished/Unvanquished/issues/3113.
> Don't process binds if KEYCATCH_UI was just disabled

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_main.cpp
- src/engine/renderer/tr_public.h
- src/engine/renderer/tr_scene.cpp
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_shader.cpp
- src/engine/renderer/tr_vbo.cpp
- src/engine/sys/sdl_glimp.cpp
- Disable GPU occlusion culling by default. @VReaperV and I agreed in an IRC chat a while back that it is not ready yet.
- Make it so that material system can be toggled with a single cvar, and updates on map change like all other latched renderer cvars. Right now it requires setting 2 cvars and only updates on a full renderer reload with `vid_restart`.
> Tweak material system cvars

- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_sky.cpp
We usually do end-users options the positive way, and this would be more consistent in option window where people ticks the boxes for enabling things.
> renderer: reverse r_fastSky as r_drawSky

- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
Same as #1350 but overbright clamping is NOT disabled by default. So this version would go ahead and change how all Unvanquished and most Tremulous maps are displayed
> Make overbright settings fully configurable (default no clamping version)

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_cmds.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_public.h
- src/engine/renderer/tr_shade.cpp
- src/engine/sys/sdl_glimp.cpp
3D texture support is not optional in OpenGL _but_ some low-end OpenGL ES devices may lack hardware support for it and Linux systems may still implement OpenGL for them.
Mesa is likely to provide such incomplete OpenGL drivers in a “better than nothing” way, this to unlock out-of-the-box OpenGL compatibility with mainstream OpenGL software that don't use any 3D textures. This includes window managers, media players, visualisation software and some production software not using 3D textures, etc. For example I guess NetRadiant would work out of the box on such incomplete OpenGL driver. 
This can happen with some Arm boards, especially since some Arm platforms may have targeted first Android phones before being integrated in computer boards. A good example of device with no hardware support …
> Report more texture size and handle case when there is no 3D texture support

- src/engine/framework/CvarSystem.cpp
Fixes https://github.com/Unvanquished/Unvanquished/issues/3120.
I suspect this is only now showing up due to removing useless cvar sets on cgame load with
https://github.com/Unvanquished/Unvanquished/pull/3099.
> Fix latch cvars not being archived

- src/engine/qcommon/common.cpp
This is something I totally forgot to submit, it was one of the purpose of me tracking many divisions by zero and other bugs related so small `minMsec` 20 months ago:
- https://github.com/DaemonEngine/Daemon/pull/812
The purpose is to not cap `timedemo` benchmarks at ~999fps (in fact more around 970fps because of time precision).
It goes against the idea of providing a benchmark feature if all hardware and driver would only report ~970fps if they can reach at least reach that.
> common: do not cap timedemo at 999fps

- src/engine/renderer/Material.cpp
- src/engine/renderer/Material.h
- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/glsl_source/heatHaze_fp.glsl
- src/engine/renderer/glsl_source/material_fp.glsl
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_shader.cpp
Do a second rendering for heatHaze materials. This is done instead of making heatHaze into to stages to avoid duplicating the memory (+possible extra material padding).
Added a `u_DeformEnable` uniform to the material heaHaze shader variant, which is global, because `u_DeformMagnitude` is set to 0.0 for the second rendering of the surface/surfaces, but it must be put into SSBO because it can differ between stages/surfaces.
Fixes #1365.
> Fix heatHaze with material system

- src/engine/framework/VirtualMachine.cpp
The "cgame"/"sgame" string to substitute was missing.
> Fix incompatible VM ABI error message

- src/engine/renderer/tr_image.cpp
Fixes a crash resulting from `va()` overflow. Fixes #1020.
> Fix R_CreateImage() crash with r_logFile

- src/engine/renderer/tr_init.cpp
The default of never build makes it unusable without setting 2 cvars. Always seems like a good conservative default so that it won't consume a bunch of disk space.
> Set default of r_autobuildcubemaps to always build

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/glsl_source/computeLight_fp.glsl
- src/engine/renderer/glsl_source/lighttile_fp.glsl
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_public.h
- src/engine/renderer/tr_shade.cpp
Add `r_realtimeLightLayers`, which allows setting the amount of layers in lighttile texture instead of the hardcoded 4, therefore allowing more dynamic lights per tile. This lets one set the cvar to balance between performance and dome dynamic lights not appearing.
> Allow changing the amount of dynamic light layers

- src.cmake
- src/engine/renderer/Material.cpp
- src/engine/renderer/ShadeCommon.h
- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/glsl_source/generic_fp.glsl
- src/engine/renderer/glsl_source/generic_vp.glsl
- src/engine/renderer/glsl_source/lightMapping_fp.glsl
- src/engine/renderer/glsl_source/lightMapping_vp.glsl
- src/engine/renderer/glsl_source/shaderProfiler_fp.glsl
- src/engine/renderer/glsl_source/shaderProfiler_vp.glsl
- src/engine/renderer/shaders.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shade.cpp
Add `r_profilerRenderSubGroups` and `r_profilerRenderSubGroupsMode`.
If `r_profilerRenderSubGroups` is enabled and the required subgroup extensions are suported, lightMapping and generic shaders will change their output colour to `dim red->bright red->dim green->bright green` based on how many active lanes in either the VS or FS there are.
Modes:
0: VS opaque
1: VS transparent
2: VS all
3: FS opaque
4: FS transparent
5: FS all
Also improved shader post-processing to leave global uniforms in-place to make this work, and made it consider comments on the same line.
More red = ~more scary~ worse (less active lanes), more green = better (more active lanes)
This is an example of using mode 0 on plat23:
Mode 2:
The surfaces resulting from rendering commands with few triangles are the more red …
> Implement GPU lane usage profiling

- CMakeLists.txt
- cmake/DaemonArchitecture.cmake
- src/engine/framework/VirtualMachine.cpp
You can get it going with arm64 engine + amd64 NaCl like this
```
brew install <bunch of stuff>
cmake <dir> -DCMAKE_OSX_ARCHITECTURES=arm64 -DOpenAL_ROOT=$(brew --prefix openal-soft)
cp <daemon>/external_deps/macos-amd64-default_10/{nacl_loader,irt_core-amd64.nexe} .
```
> Let it build on arm64 Mac

- src/engine/framework/VirtualMachine.cpp
This could give us some data to work with for detecting server incompatibility.
The cvar is named in accordance with the proposal
https://github.com/DaemonEngine/Daemon/issues/985.
> Advertise IPC ABI version in serverinfo

- src/engine/renderer/Material.cpp
Don't overwrite `tess.svars.color` by `Tess_ComputeColor()` after setting it with `SetVertexLightingSettings()`. Fixes some surfaces being whitened out, like crates, bricks and boxes on `terminus`.
> Fix vertex-lit surfaces with material system

- src/engine/sys/sdl_glimp.cpp
Update the error message when OpenGL is too old.
Also fixes the version printing.
That was part of #1179 but wasn't merged as the other implementation was merged instead:
- https://github.com/DaemonEngine/Daemon/pull/1179
> sdl_glimp: update the error message when OpenGL is too old

- src/common/System.cpp
Sometime with less common compilers I get an error about `getrandom` syscall failures, but we already have an alternate implementation. It happens that the checks is currently done at build time, but then even if the headers are there, it may fail at run time. So we technically can try the syscall then the urandom read if the syscall fails.
What I don't know though, is that if doing that is reducing security or not.
> system: use getrandom() and fallback on urandom if syscall doesn't work

- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_shader.cpp
- `renderer: cancel overbright on added lightmap`
It fixes the perseus glass_02 door.
The code was slightly rewritten too.
- `renderer: disable GLSL overbright on fullbright lightmode globally instead of doing it per-texture`
It fixes rendering fullbright lightmap stages when light mode is not fullbright,
like the starchart512 hologram in procyon map.
Fix Unvanquished/Unvanquished#3161 and #1405:
- https://github.com/Unvanquished/Unvanquished/issues/3161
- https://github.com/DaemonEngine/Daemon/issues/1405
> Fix overbright bugs

- src/engine/renderer/glsl_source/computeLight_fp.glsl
- src/engine/renderer/tr_backend.cpp
Avoid the overhead of fetching all or most of the lighttile texture and running shaders that do nothing when there are no dynamic lights.
> Don't do dynamic light computations if there are no dynamic lights

- src/engine/server/sv_init.cpp
Entity baselines are supposed to make netcode more efficient, but it's dubious (see #1321). Let server owners disable entity baselines with `set sv_useBaseline 0` as a workaround to https://github.com/Unvanquished/Unvanquished/issues/2124. This is compatible with vanilla clients. Probably no one will notice a difference wrt bandwith efficiency.
> Allow disabling entity baselines (can load big layouts)

- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shader.cpp
Deep rewrite of image loading code.
- do not walk .shader files in tr_image.cpp
- do not use R_FindImageLoader with cube maps
- only use home read for KTX with IF_HOMEPATH
- load home KTX with IF_HOMEPATH before doing any lookup
- do not do any other home loading
- test multifile cubemaps before singlefile ones (or preview may be loaded as cubemap instead)
- fix a crash when singlefile cubemap is freed because it was loaded but not created
- look for cubemap file with explicit extension
- add many debug logs and factorize them
Fixes #1393:
- https://github.com/DaemonEngine/Daemon/issues/1393
> tr_image: do not use R_FindImageLoader with cube maps, test multifile cubemaps first (or preview may be loaded as cubemap instead)

- src/engine/renderer/Material.cpp
- src/engine/renderer/Material.h
- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/glsl_source/material_fp.glsl
Don't put data that doesn't change into the material buffer.
> Make some uniforms global

- src/engine/renderer/Material.cpp
- src/engine/renderer/Material.h
- src/engine/renderer/ShadeCommon.h
- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/glsl_source/fogQuake3_fp.glsl
- src/engine/renderer/glsl_source/material_fp.glsl
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_main.cpp
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_shader.cpp
Changes fog from being done based on an if statement in `Tess_StageIteratorColor()` to being added as a surface with one of two new defaut fog shaders - similar to how we add depth pre-pass surfaces. The 2 new default shaders are for fogs with FP_EQUAL and FP_LE fog passes.
- Adds fog to material system. Fog surfaces are added as stages to the main surface, like it's already done with depth pre-pass surfaces.
- Slightly reworked how depth and fog surfaces are linked to the main surface, now `R_AddDrawSurf()` returns the index of the surface, to get the correct one.
- Moved some early-return fog checks to shader parsing/`R_AddDrawSurf()`.
- Added `u_FogMap` since all fogs use the same image, so it can be made global, and cleaned up `Render_fog()` and fog processing a bit.
- Fixes #537 by …
> Make fog into a stage, fix some issues with it

- src/engine/client/cl_scrn.cpp
The logic was this: if the user is not in-game and the window's aspect ratio is greater than 4:3, clear the screen. Otherwise do nothing.
> Remove random aspect-based screen clearing

- src/engine/renderer/glsl_source/computeLight_fp.glsl
- src/engine/renderer/glsl_source/lightMapping_fp.glsl
- src/engine/renderer/glsl_source/liquid_fp.glsl
It's wrong because in the reflection cubemaps,
the world geometry is already pre-multiplied with the world lighting. For example if the location were completely dark but you added a static light, the specular reflection of the light should appear (but wouldn't previously).
Fixes #1358.
> Don't use reflective specular for dynamic lights

- src/engine/renderer/tr_shader.cpp
This cvar can be used to demonstrate that #119 is caused by a faulty depth shader. Or to quantify the performance benefits of depth shaders.
AFAIK disabling them shouldn't affect the final result of rendering, so it does not need to be a cheat var. But I could be wrong. So in case the performance benefits turn out to be negative on some system, depth shaders could be turned off.
> Allow disabling depth prepass with r_depthShaders

- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_surface.cpp
This happens when I load plat23 with the dummy gamelogic. The surface rendering function calls Tess_CheckVBOAndIBO, which calls Tess_EndBegin, which is unhappy that there is no stage iterator set.
> Fix instant quad 'stageIteratorFunc == NULL' error

- src/engine/renderer/Material.cpp
- src/engine/renderer/Material.h
Cherry-picked from #1406.
Before:
After:
I think this is still not complete actually, as there are also implicitly vertex lit surfaces that don't have `CGEN_VERTEX` set. Vertex lighting can be automatically selected when there is no lightmap. The computer console in Vega is an example. It uses an image loaded as shader.
> Set vertex colour attr correctly with material system

- src/engine/renderer/tr_shader.cpp
Skip standalone lightmaps, they are assumed to be buggy, fixes #322:
- https://github.com/DaemonEngine/Daemon/issues/322
- https://github.com/DaemonEngine/Daemon/pull/1406
> tr_shader: skip standalone lightmaps, they are assumed to be buggy

- src/engine/renderer/Material.cpp
- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/glsl_source/cameraEffects_fp.glsl
- src/engine/renderer/glsl_source/computeLight_fp.glsl
- src/engine/renderer/glsl_source/contrast_fp.glsl
- src/engine/renderer/glsl_source/fogGlobal_fp.glsl
- src/engine/renderer/glsl_source/fogQuake3_fp.glsl
- src/engine/renderer/glsl_source/forwardLighting_fp.glsl
- src/engine/renderer/glsl_source/generic_fp.glsl
- src/engine/renderer/glsl_source/lightMapping_fp.glsl
- src/engine/renderer/glsl_source/reflection_CB_fp.glsl
- src/engine/renderer/glsl_source/shaderProfiler_fp.glsl
- src/engine/renderer/glsl_source/skybox_fp.glsl
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_scene.cpp
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_shader.cpp
- src/engine/renderer/tr_sky.cpp
AIUI overbright simply means that the lightmaps and light grid should be scaled from 0 to 4, instead of 0 to 1, so we can represent a larger range of brightness. But image colors are only allowed to go from 0 to 1. This is a big problem... if we are using GL 1 (hence, perhaps, the mysterious "hardware implementations"). But we have shaders, so all we have to do is multiply by 4 whenever we read one of those special light textures. Problem solved?
I tried this approach and it looks the same to me, consistent with the complex cancellng system that we had before. Also fixes the Perseus glass and Procyon star chart issues addressed in #1404.
An explanation for the canceling approach is given in #1050:
> We cannot overBright separate stage as stage are clamped within [0.0, 1.0] when blending …
> Simplify overbright implementation

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/glsl_source/generic_fp.glsl
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_public.h
- src/engine/renderer/tr_shade.cpp
- src/engine/sys/sdl_glimp.cpp
Disable depth fade, depth testing, depth writing for 2D rendering. Don't create a depth or stencil channel in the default framebuffer.
Instead of using the "depth clamp" GL extension (which disables clipping based on the z-coordinate), set the projection matrix to make z always 0. This is relevant if we use 3d CSS transformations like [these](https://polypane.app/css-3d-transform-examples/).
> Remove useless depth-related stuff from 2D rendering

- src/engine/renderer/Material.cpp
> Fix specular with material system

- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_main.cpp
- src/engine/renderer/tr_world.cpp
Save portal AABBs when loading the map, then use them to cull portals instead of using the vertex buffer. I've considered using a rect instead since portals only really work on flat surfaces, but it wasn't important enough for me to bother given that the surface can be rotated. It might also be worth just using `R_CullBox()` instead of the projection into window coordinates and clipping.
Also fixes the issue mentioned in a comment that said that portal distance should be between the portal surface and view origin, instead of between the closest vertex and view origin.
This also improves performance since the vertex buffer is no longer read from on the CPU.
Fixes #1216 and #1199.
> Fix portals with r_smp 1

- src/engine/framework/VirtualMachine.cpp
Make receive timeout configurable.
I used this to make sure the Saigo-compiled code was stuck in an infinite loop and not just slower.
It may also help when loading the game from a very slow file system (like network file system over Internet), because the time waiting for the first receive is waiting for the nexe to be actually loaded (downloaded if a network file system).
> VirtualMachine: make receive timeout configurable

- external_deps/build.sh
- src/engine/framework/System.cpp
> Fix daemonded not starting on Mac

- cmake/DaemonFlags.cmake
Apparently it doesn't do anything, and triggers a warning about an unused command line argument. When USE_HARDENING is enabled, this warning breaks a bunch of other try_compile's, causing flags to be rejected that should have been accepted.
> Don't set -pie flag with AppleClang

- cmake/DaemonGame.cmake
Re-add the generic `nacl-vms` target, it is used by the dockerized build script.
> cmake: re-add the generic `nacl-vms` target, it is used by the dockerized build script

- src/engine/qcommon/q_math_test.cpp
Add a unit test so we can verify that magic square root algorithms meet the claimed tolerances. If #1458 adds a second version of the function, we can copy and paste the test and just change the `relativeTolerance`.
> Unit test for Q_rsqrt

- src/engine/qcommon/q_math_test.cpp
- src/engine/qcommon/q_shared.h
- src/engine/renderer/tr_main.cpp
- Add `Q_sqrt_fast()` that skips the second iteration, it is believed to be useless:
https://github.com/DaemonEngine/Daemon/issues/1457
- Use better magic constants for the `Q_rsqrt` trick,
the values come from: http://rrrola.wz.cz/inv_sqrt.html
- Use `Q_sqrt_fast()` in `R_TBNtoQtangents()` and `VectorNormalizeFast()`.
> Some improvements around `Q_rsqrt()`

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/tr_shade.cpp
Based on #1479.
The only difference is in a compile macro that's used to skip UI for subgroup profiling, which doesn't require a whole new shader.
> Merge generic2D shader into generic

- src/engine/renderer/Material.cpp
- src/engine/renderer/gl_shader.h
> Don't set global uniforms in UpdateSurfaceData*

- CMakeLists.txt
- cmake/DaemonCompiler.cmake
- cmake/DaemonCompiler/DaemonCompiler.c
- cmake/DaemonCompiler/DaemonCompiler.cpp
- cmake/DaemonCompiler/DaemonCompiler.sh
- cmake/DaemonFlags.cmake
- cmake/DaemonGame.cmake
- src/engine/framework/System.cpp
Those are old commits that were sitting on my hard drive for a long time. I believe I wrote them when we were investigating the console bug that only happened on clang and clang-based compilers. I assume that enabling PCH with Saigo would now just require to replace the test for `NACL` with a test for the PNaCl compiler.
The first need I wanted to fulfill was to write in `daemon.log` the compiler that was used to build the game, in order to give useful information to people dealing with bug reports.
The second need I wanted to fulfill was to know at build time by reading the build log what CMake was really using when I set some options.
While I was at it, I added custom code to recognize custom compilers like PNaCl and Saigo (in fact at the time I had added Wasi recognition but I removed …
> Report what compiler is used to build the game

- CMakeLists.txt
- cmake/DaemonGame.cmake
Remove this warning:
```
CMake Warning (dev) at CMakeLists.txt:136 (set):
Cannot set "NACL_TARGETS": current scope has no parent.
This warning is for project developers.  Use -Wno-dev to suppress it.
CMake Warning (dev) at /usr/share/cmake-3.28/Modules/CMakeDependentOption.cmake:89 (message):
Policy CMP0127 is not set: cmake_dependent_option() supports full Condition
Syntax.  Run "cmake --help-policy CMP0127" for policy details.  Use the
cmake_policy command to set the policy and suppress this warning.
Call Stack (most recent call first):
CMakeLists.txt:167 (cmake_dependent_option)
This warning is for project developers.  Use -Wno-dev to suppress it.
```
That lines look like a mistake, everything is either in the same scope, either passed through command line to the child cmake, there is …
> cmake: remove a warning about scope

- cmake/DaemonGame.cmake
Fixup for:
- https://github.com/DaemonEngine/Daemon/pull/1468
I missed this mistake.
`DaemonPlatform` should always be included for now because of some other chicken-and-egg problem (not in the scope of that PR).
> fixup: cmake: set variables before using them

- src/engine/qcommon/common.cpp
- src/engine/server/sv_init.cpp
- sv_init: add the `contact` cvar and server info string to contain contact information to reach out the server admin when needed
- common: disable logging suppression in `Info_Print()` (used by commands like `/systeminfo` and `/serverinfo`)
> Add the `contact` cvar and server info string to contain contact information to reach out the server admin when needed

- src/engine/framework/System.cpp
By default Daemon forwards commands passed on the command line if there is one, or otherwise starts a new instance. The new command-line arguments can be used to only allow one or the other of the behaviors.
Fixes #942.
> Add -noforward/-forward-only command line args

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/glsl_source/shaderProfiler_fp.glsl
- src/engine/renderer/glsl_source/shaderProfiler_vp.glsl
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shade.cpp
NUKE the GENERIC_2D macro and add `trGlobals_t::skipSubgroupProfiler` to skip the subgroup profiler instead.
Alternative to #1486.
> FIx unnecessary generic shader permutations

- src/engine/renderer/gl_shader.cpp
This can sometimes happen, leading to missing log entries when printing the log. Fixes that by sorting them first.
> Fix out of order shader log messages

- src/engine/qcommon/msg.cpp
- src/engine/qcommon/q_shared.h
- src/engine/qcommon/qcommon.h
- src/engine/server/server.h
- src/engine/server/sg_msgdef.h
- src/engine/server/sv_ccmds.cpp
- src/engine/server/sv_main.cpp
- src/engine/server/sv_sgame.cpp
- src/engine/server/sv_snapshot.cpp
- src/shared/server/sg_api.cpp
- src/shared/server/sg_api.h
Have sgame retrieve pings by using a syscall, instead of the engine writing the ping into shared memory.
This is an attempt to simplify the interface between the engine and the VM, which could benefit future sandboxing technology migrations. The player state portion of the shared memory will now be readonly for the engine, rather than a two-way communication channel. Hopefully I can do the same for the entity state next, so that all of the shared memory is read-only for the engine.
Companion: https://github.com/Unvanquished/Unvanquished/pull/3207
> Add trap_GetPings, so that engine does not mutate playerstate

- src/engine/renderer/Material.cpp
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_main.cpp
Picked from #1473.
This makes debugging issues that are present on material system but not core renderer (or vice versa), as well as comparing performance, much faster, since it can be changed without any sort of restart.
> Add r_materialSystemSkip

- src/engine/server/sv_client.cpp
This stops leakage from colours in player names in the server console.
> server: sanitise colours when logging download information

- src/engine/client/ClientApplication.cpp
The comment in the code is pretty self explanatory. This has been tested on KDE only. 
Screenshots demonstrating what this fixes are below. I do not believe this has any effect on macOS or Windows, documentation suggests this relates to dbus. Hopefully I have done this correctly.
Documentation here:
https://discourse.libsdl.org/t/sdl-add-sdl-hint-app-name-and-dbus-inhibition-hint/32698
https://wiki.libsdl.org/SDL2/SDL_HINT_APP_NAME
OLD:
NEW:
> identify the game by its name in SDL

- src/engine/client/cl_main.cpp
- src/engine/renderer/tr_animation.cpp
- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_fbo.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_model.cpp
- src/engine/renderer/tr_public.h
- src/engine/renderer/tr_shader.cpp
- src/engine/renderer/tr_skin.cpp
- src/engine/server/sv_ccmds.cpp
- src/engine/sys/sdl_glimp.cpp
Migrate commands to the new interface. That has the benefit of show descriptions for the commands, and using `Print` so that the output is not affected by log suppression.
Most of the diffs are indentation changes, so you might like to review it as follows:
```
git fetch origin pull/1494/head
git show -4 FETCH_HEAD --ignore-space-change
```
> Migrate render commands to C++ interface

- cmake/DaemonCompiler/DaemonCompiler.c
Do not omit main parameter name in C.
Fixes #1505:
- https://github.com/DaemonEngine/Daemon/issues/1505
This produced those errors:
```
../../daemon/cmake/DaemonCompiler/DaemonCompiler.c:163:13: error: parameter name omitted
int main(int, char**) {
^
../../daemon/cmake/DaemonCompiler/DaemonCompiler.c:163:21: error: parameter name omitted
int main(int, char**) {
^
7 warnings and 2 errors generated.
```
Actually my first implementation of parsing the output of `cc -dM -E` could not be subject to that (no compilation was involved at all).
> DaemonCompiler: do not omit main parameter name in C

- CMakeLists.txt
- cmake/DaemonCompiler.cmake
- cmake/DaemonFlags.cmake
Do not use space in compiler string definition, it is not compatible with the standalone MinGW for Windows.
Fix #1497:
- https://github.com/DaemonEngine/Daemon/pull/1497
> cmake: do not use space in compiler string definition, it is not compatible with the standalone MinGW for Windows

- src/common/Command.cpp
- src/common/Command.h
- src/engine/client/cl_main.cpp
- src/engine/framework/BaseCommands.cpp
- src/engine/framework/CommandSystem.cpp
- src/engine/qcommon/files.cpp
- src/engine/renderer/tr_animation.cpp
- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_fbo.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_model.cpp
- src/engine/renderer/tr_shader.cpp
- src/engine/renderer/tr_skin.cpp
- src/engine/server/sv_ccmds.cpp
- src/engine/sys/sdl_glimp.cpp
As @VReaperV discovered while reviewing #1494, `listCmds` can't list a command if it has no flags defined. Fix this by defining flags for all the engine commands and disabling the constructor that doesn't define flags.
> Set engine command flags

- src/engine/qcommon/net_ip.cpp
- src/engine/qcommon/qcommon.h
- src/engine/server/sv_init.cpp
Note: nothing release-critical here
> Networking bug fixes and cleanup

- src/engine/renderer/tr_init.cpp
This was previously getting reset in `R_Init()`, so it was always 0 after a map was loaded. This also meant that the call to `glDeleteVertexArrays()`  in `RE_Shutdown()` was silently erroring out if a map was loaded (or `vid_restart` used).
> Fix backEnd.currentVAO

- cmake/DaemonFlags.cmake
Fixes Unvanquished/Unvanquished#3297:
- https://github.com/Unvanquished/Unvanquished/issues/3297
In the future we may either enable some optimizations from `-O2` or enable `-O2` and disable some specific optimizations to avoid doing a _not-optimized-at-all_ build, but this is enough to make the arm nexe run and then unblock the migration to Saigo.
> cmake: build Saigo arm nexe with -O0 to avoid a bug

- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_shade.cpp
The drawing state can get messed up if you call CG_FillRect right before RmlUi draws anything, and almost everything looks wrong with wrong colors and text being drawn as solid boxes.
Regression in 7b210353ce0b73117baeec32521746c0990bd68c.
> Fix bug with 2d drawing GL state

- src/engine/qcommon/q_shared.h
Missed that one when converting the vector macros, as noticed by freem
> Make Square() a template function instead of macro

- src/engine/renderer/Material.cpp
If the cgame sends some 2D rendering commands in the first frame before calling RenderScene as described in
https://github.com/Unvanquished/Unvanquished/pull/3305, it could cause a crash. Fix this by not setting generatingWorldCommandBuffer prematurely while those commands are executing.
> Fix crash in GenerateWorldMaterials()

- src/engine/client/cg_msgdef.h
- src/engine/client/cl_cgame.cpp
- src/engine/null/null_renderer.cpp
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_public.h
- src/engine/renderer/tr_scene.cpp
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_types.h
- src/shared/client/cg_api.cpp
- src/shared/client/cg_api.h
Cgame-side pr: https://github.com/Unvanquished/Unvanquished/pull/3184
Dynamic light config update for weapon flash colours: https://github.com/UnvanquishedAssets/res-weapons_src.dpkdir/pull/32
- NUKED the weird 4x dynamic light scaling
- NUKED the weird `r_lightScale` cvar, which is used for dynamic lights, but it's a cheat cvar and always set to 2.0, and essentially only used for dynamic lights spawned from movers
- NUKED `RE_AddDynamicLightToSceneQ3A()` and renamed `RE_AddDynamicLightToSceneET()` to `RE_AddDynamicLightToScene()` because they're essentially the same
- NUKED now unused `trap_R_AddAdditiveLightToScene()`
- NUKED light intensity/scale, which was only used to scale the light's colour, just multiply the colour earlier on instead
- Fixed some incorrect memory read before …
> Fix dynamic lights intensity, cleanup

- src/engine/qcommon/q_shared.h
It didn't take into account promotion to integer for types smaller than int.
Fixes #1533.
> Fix bad return type for Square() template

- src/engine/renderer/tr_init.cpp
Normally, to use the dGPU on Windows 10/11, you need to manually set it for the executable in Windows settings. This will set some registry values to tell the NVidia/AMD drivers to use the dGPU here.
I've confirmed that this works on Win10 with an NVidia dGPU, now just waiting for someone to test it with AMD.
> Use dGPU if both dGPU and iGPU are available on Windows

- src/engine/renderer/Material.cpp
- src/engine/renderer/Material.h
- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/glsl_source/clearSurfaces_cp.glsl
- src/engine/renderer/glsl_source/cull_cp.glsl
- src/engine/renderer/glsl_source/processSurfaces_cp.glsl
- src/engine/renderer/tr_public.h
- src/engine/renderer/tr_vbo.cpp
- src/engine/sys/sdl_glimp.cpp
The `GLBuffer` has started to become unwieldy when setting up buffers, so I cleaned up its interface and made it use Direct State Access versions of the buffer commands where possible instead. These commands allow modyfing buffers without actually binding them, which makes it much easier. I've also removed a lot of duplicate code from `GLBuffer` itself, as well as the derivative buffers.
`glBufferData` has been moved to `GLBuffer`, in line with the other buffer functions.
Cleaned up buffer binding points as well, now they use an enum, and the shaders use defines for it.
Moved buffer init/free to a more appropriate location as well.
Also NUKED the unused `GLIndirectBuffer` and moved `GLIndirectCommand` to `MaterialSystem.h`.
> Clean-up GLBuffer interface, use DSA

- src/engine/client/cg_api.h
- src/engine/client/cg_msgdef.h
- src/engine/client/cl_cgame.cpp
- src/shared/client/cg_api.cpp
- src/shared/client/cg_api.h
A shared header defined snapshot_t which was used in both the client and cgame, but with different definitions of the player state struct. For the cgame definition of playerState_t it included the file shared/bg_public.h from the gamelogic.
Instead of this define an ipcSnapshot_t type which has a consistent definition and is used for IPC messages. Now snapshot_t will be defined and used only in the cgame.
Companion: https://github.com/Unvanquished/Unvanquished/pull/3182
> Clean up snapshot mess with #including gamelogic

- CMakeLists.txt
- cmake/DaemonGame.cmake
- src.cmake
- src/dummygame/CMakeLists.txt
- src/dummygame/cgame.cpp
Stacked on #1421.
Add a cgame module that simply loads and displays a map, with no entities. It can be useful to quickly test how a map renders or to make sure a simple gamelogic builds correctly in the CI. `loadmap` is the command to enter a map. The only way to change position for now is `setviewpos`.
Future directions:
- Add controls for moving
- Draw some help text when not in a map
- Move commands like `testmodel` to Daemon and build them in
- Load and draw stationary entities
> Add a trivial cgame module which can view a map

- src/engine/renderer/tr_image.cpp
Fix loading `dds/` prefixed `.dds` images.
> tr_image: fix loading dds/ prefixed .dds images

- cmake/DaemonFlags.cmake
Extracted from #1451 which is stuck in review:
- https://github.com/DaemonEngine/Daemon/pull/1451
This just add the CMake option `USE_FAST_MATH` to disable it (when setting `OFF`).
> cmake: add USE_FAST_MATH to enable or disable fast math

- src/engine/renderer/Material.cpp
- src/engine/renderer/Material.h
- src/engine/renderer/tr_init.cpp
Fixes `glsl_restart` with material system by resetting the shaders for each material.
> Fix glsl_restart with material system

- src/engine/renderer/tr_animation.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_mesh.cpp
- src/engine/renderer/tr_model_iqm.cpp
- src/engine/renderer/tr_model_md3.cpp
- src/engine/renderer/tr_model_md5.cpp
- src/engine/renderer/tr_vbo.cpp
- src/engine/sys/sdl_glimp.cpp
- NUKED useless GL_ARB_buffer_storage and GL_ARB_sync macro checks.
- Fix bogus checks for SHADER_MAX_VERTEXES and SHADER_MAX_INDEXES for cases where the dynamic buffers are not being used by adding a check for `r_vboModels`. Also changed it to a new-style cvar.
- Some small clean-up of Ringbuffer functions and more stuff in logs.
> Some dynamic buffer-related clean-up and fixes

- src.cmake
- src/engine/renderer/GeometryCache.cpp
- src/engine/renderer/GeometryCache.h
- src/engine/renderer/Material.cpp
- src/engine/renderer/Material.h
- src/engine/renderer/gl_shader.h
- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_public.h
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_vbo.cpp
- src/engine/sys/sdl_glimp.cpp
Requires #1511, #1513, and #1514.
The geometry cache represents 3 buffers: a VBO, IBO, and inputVBO. These buffers will replace the old separate input VBOs and IBOs when enabled. This allows binding only a VAO before rendering, rather than setting up vertex pointers with the correct offset and formats every time. Additionally, it means that there's no need to switch between different VBOs/IBOs. The `inputVBO` is currently unused, but it will be needed to make models work with the geometry cache (model animations and world transform will be processed in a compute shader).
This further improves performance and removes the VBO/IBO check for materials.
Currently this is only used by the material system, but it should be possible to make the core renderer use it as well.
This will also be …
> Implement geometry cache

- src/engine/renderer/glsl_source/generic_fp.glsl
Fixes an issue creating a void effect, where vertex + color/diffuse map produces different results in depth pre-pass `generic` and `lightMapping` shaders, due to different check/multiplication order.
Fixes #119. I've also tried moving the multiplication before the check in `generic` shader, but it ended up making surfaces disappear based on distance to them.
> Multiply with var_Color in lightMapping after u_AlphaThreshold check

- src/engine/qcommon/q_shared.cpp
Fixes a shader stage parsing error on https://users.unvanquished.net/~sweet/pkg/map-monk_0%2B0.dpk.
> Fix shader parse error with `\r` new-lines

- cmake/DaemonFlags.cmake
- src/common/Command.cpp
- src/engine/framework/System.cpp
- src/engine/qcommon/q_shared.h
- Add `USE_FLOAT_EXCEPTIONS` to enable floating point exceptions  (disabled by default)
- Add `USE_FAST_MATH` to enable or disable fast math (enabled by default)
When `USE_FLOAT_EXCEPTIONS` is used, nothing is done unless some of those cvars are enabled:
- `common.floatExceptions.invalid`
- `common.floatExceptions.divByZero`
- `common.floatExceptions.overflow`
The `USE_FLOAT_EXCEPTIONS` option is required to specialize the build to make it possible to enable them.
The `common.floatExceptions.test` cvar enables some code doing bad floating point operations on purpose to test how they are handled.
Status:
Platform|Implemented|Tested
-|-|-
Linux GCC amd64|✅️|✅️
Linux GCC i686|✅️|✅️
Linux Clang amd64|✅️|✅️
Windows MinGW amd64|✅️|✅️
Windows MinGW i686|✅️|✅️
Windows MSVC amd64|✅️|
Windows MSVC …
> Add `USE_FLOAT_EXCEPTIONS` to enable floating point exceptions

- src/engine/renderer/tr_model_iqm.cpp
Rewrite `NaN` in model IQM input.
The `prifle_view.iqm` model has some `NaN` in the input data:
- https://github.com/Unvanquished/Unvanquished/issues/3252
When such model file is used, it is impossible to get anything useful when trapping for invalid operations because the first call of `R_TBNtoQtangents()` when loading the model will stop the execution.
There are other floats in the IQM file, we may want to not hack `BuildTangents()` and sanitize all the floats in the future with a generic function, but this works for now.
Here is the IQE text equivalent of the IQM format, there are many float fields like that:
```
pq 0 0 0 0.707107008 0.000172803004 0.707107008 -0
vp -7.02030039 -5.93917179 -10.5407791
vn -0.373933047 -0.803014815 -0.464048833
vx 0.618980289 0.156532541 -0.769649923 -1 …
```
> tr_model_iqm: detect and rewrite NaN in IQM model

- CMakeLists.txt
- cmake/DaemonArchitecture.cmake
- cmake/DaemonBuildInfo.cmake
- cmake/DaemonCompiler.cmake
- cmake/DaemonGame.cmake
- src/common/Defs.h
- src/engine/framework/System.cpp
- src/engine/framework/VirtualMachine.cpp
- src/engine/qcommon/common.cpp
- src/engine/sys/sdl_glimp.cpp
Generate a builtin.cpp file instead of using compiler definitions.
It produces those kind of files:
- `builtin/builtin.cpp`
```c++
// Automatically generated, do not modify!
const char* DAEMON_ARCH_STRING="amd64";
const char* DAEMON_NACL_ARCH_STRING="amd64";
const char* DAEMON_C_COMPILER_STRING="GCC_13.3.0:x86_64-linux-gnu-gcc";
const char* DAEMON_CXX_COMPILER_STRING="GCC_13.3.0:x86_64-linux-gnu-g++";
const char* DAEMON_OPENGL_ABI_STRING="LEGACY";
```
- `builtin/builtin.h`
```c++
// Automatically generated, do not modify!
extern const char* DAEMON_ARCH_STRING;
extern const char* DAEMON_NACL_ARCH_STRING;
extern const char* DAEMON_C_COMPILER_STRING;
extern const char* DAEMON_CXX_COMPILER_STRING;
extern const char* DAEMON_OPENGL_ABI_STRING;
```
Needed by:
- …
> generate a DaemonBuildInfo.cpp file instead of using compiler definitions

- src/engine/renderer/gl_shader.cpp
Fixes one of the issues in #1535.
Adrenaline/OGLP drivers erroneously disregard the ARB extension functionality (which has different naming than the core one) with `#version 460 core`, which is the one we end up using on such drivers, because it's the context version that the driver provides.
> Workaround for atomic ops on AMD

- CMakeLists.txt
- cmake/DaemonBuildTypeGeneratorExpression.cmake
- cmake/DaemonFlags.cmake
- cmake/toolchain-pnacl.cmake
- NaCl builds didn't work due to a mistake with USE_RECOMMENDED_CXX_STANDARD
- #398
> Fix 2 build system issues with Visual Studio

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/glsl_source/cameraEffects_fp.glsl
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
Ever since #1050, we've had some major changes to lighting thanks to fixing the bug that was affecting how strong the lights were on any map (see #1050 and related pr for the explanation).
#1050 added the option of using int16 render targets. This was done in order to avoid clamping shader output to the `[0.0, 1.0]` range before blending it. And then later #1406 changed it to an fp16 framebuffer to avoid colour clamping in multi-stage shaders. This all requires `r_highPrecisionRendering on`.
One of the side-effects of the whole overbright fix is that some lights became brighter than what the 8-bit framebuffer could hold. Coincidentally, the change to 16-bit framebuffers - in particular the fp16 ones, because int framebuffers still get clamped to `[0.0, 1.0]` - is part of the solution to …
> Implement Lottes HDR->LDR tonemapper

- src/engine/renderer/tr_shade.cpp
`r_noportals` is non-latch, so loading a map with `r_noportals 1` that uses alphaGen portals, then setting `r_noportals 0` will result in a crash. This can be observed on e. g. map `pulse` with the camera screens.
Fix this by always loading the portal shader.
> Fix a crash with r_noportals

- src/engine/renderer/tr_shade_calc.cpp
Fixes #1278.
The previous code assumed that a texture with a scroll textureMod would always wrap around when `scroll * backEnd.refdef.floatTime == floor( scroll * backEnd.refdef.floatTime )`. This is incorrect if the texture matrix had already been modified by another texMod, so the relevant values are no longer 1.0f and 0.0f. Fix this by using `scrollPeriod[0] / ( matrix[0] + matrix[4] )` and `scrollPeriod[0] / ( matrix[0] + matrix[4] )` to get the actual time at which wrap-around for `x` and `y` will occur, and use `fmodf( backEnd.refdef.floatTime, period )` to get the part that is equivalent to just using `backEnd.refdef.floatTime`, but without the value getting continuously larger.
Also NUKED some useless matrix computations from texMod scroll, and added some functions to only …
> Fix texture scroll, optimise texture matrix operations a bit

- src/common/IPC/CommonSyscalls.h
- src/engine/framework/CommonVMServices.cpp
- src/shared/CommonProxies.cpp
- src/shared/CommonProxies.h
This is needed to get the local time since an NaCl VM can't read the time zone database.
Returns an offset instead of directly returning the local date, in the interests of not doing a trap call every frame.
Companion: https://github.com/Unvanquished/Unvanquished/pull/3328
> Add VM syscall for getting local time offset

- src.cmake
- src/engine/renderer/Material.cpp
- src/engine/renderer/glsl_source/cull_cp.glsl
- src/engine/renderer/glsl_source/material_cp.glsl
- src/engine/renderer/glsl_source/processSurfaces_cp.glsl
- src/engine/renderer/shaders.cpp
- src/engine/renderer/tr_bsp.cpp
These are mostly changes that I picked from #1559.
Previously only the material system used compute shaders at all, but now that other systems will be using them, all this stuff needs to be moved to another shader. Otherwise the other shaders would fail to compile, or all of them would require a bunch of macros to check for it.
Also moved the material system per-frame compute dispatches to `StartFrame()` since they work there now.
> Some more material system clean-up

- cmake/DaemonFlags.cmake
Use -flto=auto compiler flag when supported, this silence this GCC warning:
> lto-wrapper: warning: using serial compilation of # LTRANS jobs
This also greatly speeds-up the linkage time as it enables LTO multithreading in GCC (either by using Make jobserver if detected, either by detecting CPU cores).
> cmake: use -flto=auto compiler flag when supported

- src/engine/renderer/glsl_source/fogQuake3_vp.glsl
NUKE some dead code.
- https://github.com/DaemonEngine/Daemon/pull/1570
> renderer: NUKE some dead code

- src/engine/sys/sdl_glimp.cpp
Disable ARB_shader_draw_parameters on GLSL 1.20.
- https://github.com/DaemonEngine/Daemon/pull/1570
Fixes #1575:
- https://github.com/DaemonEngine/Daemon/issues/1575
> renderer: disable ARB_shader_draw_parameters on GLSL 1.20

- cmake/DaemonFlags.cmake
There was a stupid mistake inverting between executable-linker-flags and everythng-linker-flags.
Fixes #1573:
- https://github.com/DaemonEngine/Daemon/issues/1573
I verified that even after fixing this maCOS still complains about `-pie` not being used on executables so I kept the macOS test to disable `-pie`:
```
[100%] Linking CXX executable daemonded
clang++: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
```
> Fix mistake when setting linker flags

- src/engine/client/cl_keys.cpp
The keyboard shortcut (Command+F) for toggling fullscreen mode unnecessarily issued vid_restart. It works fine without that as can be seen by just setting the cvar r_fullscreen.
> Mac: don't vid_restart when toggling full-screen

- src/engine/sys/sdl_glimp.cpp
Could be useful in scripting automatic testing and stuff. I can put it at, say, (-2000 -2000) to make the window not visible. (Tested on Windows; not sure if that works on all systems.)
> Add setWindowOrigin command

- src/engine/renderer/Material.cpp
- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/glsl_source/cameraEffects_fp.glsl
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_shader.cpp
Fixes #1542. Adds `r_overbrightBits` which works similar to the one in Quake 3. With the default value of 1, there is one "clamped" bit and one "unclamped" bit of overbright. With map overbright bits = 2 and tr.overbrightBits = 1, A lightmap value of x is treated like `min(x * 4, 2)` except that if some color channel exceeded 2, all the channels are scaled down together.
Comparison of map mxl-school viewpos 1983 -838 353 130 24:
`r_overbrightBits 0` (like old Q3 in non-fullscreen mode, Tremfusion, most versions of Unvanquished until recently): A sickly light. Needs more brightness.
`r_overbrightBits 2` (like Unvanquished 0.55+): Too much! Now it's saturated.
`r_overbrightBits 1` (like full-screen Windows 9x Q3, ioq3 with GL2 renderer, Tremulous 1.1.0): Just right.
Here's a screenshot with …
> Implement partial overbright clamping like Q3

- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shader.cpp
- src/engine/renderer/tr_types.h
Cgame-side pr: https://github.com/Unvanquished/Unvanquished/pull/3306
Replaces RSF_NOLIGHTSCALE.
If this flag is used when registering a shader, all `ST_COLORMAP` stages will be changed to `ST_DIFFUSEMAP`. This is intended for use with particles and trails, to make them use the lightGrid in the GLSL code.
Improves performance with particle systems and trails, e. g. with firebombs, and a massive performance improvement on map https://users.unvanquished.net/~sweet/pkg/map-jota_3.0.dpk in the outside area.
There's for the most part no difference in how the particles/trails look, the only differences are due to the GLSL lightGrid being more precise.
> Add RSF_FORCE_LIGHTMAP

- src/engine/sys/sdl_glimp.cpp
Disable EXT_gpu_shader4 on GLSL 1.2.
`EXT_gpu_shader4` behaves slightly differently on GLSL 1.20.
See: https://gitlab.freedesktop.org/mesa/mesa/-/issues/12803#note_2819461
The patch is similar to: 
- https://github.com/DaemonEngine/Daemon/pull/1576
Also does a bit of rewording of #1576.
> renderer: disable EXT_gpu_shader4 on GLSL 1.20

- src/engine/renderer/glsl_source/cameraEffects_fp.glsl
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_public.h
- src/engine/renderer/tr_shade.cpp
Rework tone mapper and ssao enablement.
- https://github.com/DaemonEngine/Daemon/pull/1570
> renderer: rework tone mapper and SSAO enablement

- src/engine/framework/System.cpp
On *nix using a pipe makes the output fully buffered, as opposed to a TTY where the default is line buffering. We did a fast shutdown without flushing so the output could be lost.
Fixes #631.
> Fix --help output not appearing through a pipe

- cmake/DaemonArchitecture/DaemonArchitecture.cpp
Always assume i686, instead of trying to use the numeric value of Q_PROCESSOR_X86, which isn't accurate in our build.
For architecture detection the compiler is invoked without any of the flags that we usually pass. So the -march=XXX, etc. flags are not there. This means the architecture revision that the compiler advertises during architecture detection may not be the same as in the real build. You may react, "just do the architecture detection with all flags on", but this would probably lead to chicken-and-egg problems as architecture is used to choose flags. In principle it could be done with two passes of architecture detection but implementing that would obviously be a waste of time.
Fixes #1596.
> DaemonArchitecture: NUKE x86 revision detection

- src/engine/client/cl_cgame.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_local.h
> Clean up RE_GenerateTexture

- cmake/DaemonGame.cmake
Refactor game build configuration to reuse the same code in parent build or subproject build and mutualize code between vm type build.
- https://github.com/DaemonEngine/Daemon/pull/1484
This one brings nothing new, it just refactors the code in a better way so it makes future changes easier.
Amont various things,
- it makes building vm subproject independent from NaCl
- it deduplicates and mutualises the code to avoid maintaining multiple copy-paste
> cmake: refactor game build configuration to reuse the same code in parent build or subproject build and mutualize code between vm type build

- cmake/DaemonGame.cmake
Make sure the dll game is built as module, not as static library.
Fixup for:
- https://github.com/DaemonEngine/Daemon/pull/1555
This wasn't caught by the CI, but a bug in #1555 made the dll game being compiled to `cgame-native-dll.a` instead of `cgame-native-dll.so`. Also, this hid another bug where CMake would overwrite `COMPILE_DEFINITIONS` and then lose the `BUILD_VM_IN_PROCESS` definition.
> cmake: make sure the dll game is built as module, not as static library

- src/engine/client/cl_main.cpp
- src/engine/qcommon/net_ip.cpp
- src/engine/qcommon/sys.h
Don't print the hostname and network addresses that may make people worry about posting logs with confidential information. Instead the `showip` command can be used. Make the command available for all engines.
Fixes https://github.com/Unvanquished/Unvanquished/issues/1573.
> Don't print some network information on startup

- src/engine/renderer/Material.cpp
- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_cmds.cpp
- src/engine/renderer/tr_fbo.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_light.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_scene.cpp
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_sky.cpp
- src/engine/renderer/tr_surface.cpp
- src/engine/renderer/tr_vbo.cpp
- src/engine/sys/sdl_glimp.cpp
Rewrite `GLimp_LogComment()` calls.
Also don't require an ending `\n` on every call.
Also only call `GLimp_LogComment()` when the function doesn't return early.
No more noisy:
```c++
if ( r_logFile->integer )
{
GLimp_LogComment( va( "bla: %d\n", bla ) );
}
if ( condition )
{
return;
}
```
Just this:
```c++
if ( condition )
{
return;
}
GLIMP_LOGCOMMENT( "bla: %d", bla );
```
_Edit:_ `GLIMP_LOGCOMMENT()` is a macro wrapping both the `if ( r_logFile->integer )` test and a `Str::Format()` call.
> renderer: rewrite `GLimp_LogComment()` calls

- src/common/System.cpp
Purely useless change, but the parenthesis pair being broken by some ifdef make unhappy the syntax coloring of vim and that annoys me every time I open this file. 😏️
I guess the compiler can optimize out the extra variable.
> bikeshedding: make syntax coloring happier

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/glsl_source/computeLight_fp.glsl
- src/engine/renderer/glsl_source/lighttile_fp.glsl
Do explicit `uint` casting in GLSL operations.
Fixes #1611:
- https://github.com/DaemonEngine/Daemon/issues/1611
> Do explicit `uint` casting in GLSL operations

- CMakeLists.txt
- cmake/DaemonFlags.cmake
- freetype.cmake
Make possible to build both game and engine against the engine Freetype submodule.
Extracted from #1585:
- https://github.com/DaemonEngine/Daemon/pull/1585
Without the controversial change about default building.
See also:
- https://github.com/Unvanquished/Unvanquished/pull/3353
> cmake: make possible to build both game and engine against the engine Freetype submodule

- cmake/DaemonGame.cmake
FORK=1 is needed to know whether the nacl-vms target has been created already.
> Fix NaCl build breakage

- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_light.cpp
- src/engine/server/sv_init.cpp
The out-of-bounds light grid read one led to visibly different lighting on Nano. This map tends to read on the edges of the grid due to its very large cell size: the light grid is only 3x4x2 for the whole map.
> Fix some bugs from address sanitizer 

- CMakeLists.txt
cmake_dependent_option, as implemented in the GUI/TUI, is a pointless misfeature. It could be useful if it, say, showed the option as grayed out and then enabled itself as soon as the dependee changed. But what it actually does is hide the dependent option completely, and not show it until you reconfigure. So it's just a nuisance when you want to use the option: you have to configure multiple times. The goal of hiding options that are not relevant is hopeless anyway since there are always zillions of options that don't affect the current build.
We had just 2 cmake_depend_option's, USE_SMP and USE_SLIM_LTO.
Fixes https://github.com/Unvanquished/Unvanquished/issues/1921.
> NUKE CMake dependent options

- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_main.cpp
- src/engine/renderer/tr_marks.cpp
- src/engine/renderer/tr_surface.cpp
- src/engine/renderer/tr_world.cpp
I've run into a bunch of duplicate code while making some improvements to map processing, any improvements to which required to add more such duplication, while the code underneath is the exact same.
This pr NUKES `srfTriangles_t` and `srfSurface_t`, and moves all the common information between them, `srfGridMesh_t`, and `srfVBOMesh_t `, into `srfGeneric_t`.
The common parts of `ParseFace()` and `ParseTriSurf()` are moved into a new `ParseTriangleSurface()`, which is all of it except the plane calculation. The comment about `.lwo` models in `ParseTriSurf()` is irrelevant, because we don't support those.
`ParseTriangleSurface()` and `ParseMesh()` now use `SphereFromBounds()` instead of `FinishGenericSurface()`, because the only difference between the 2 was just duplicated code.
> Get rid of a bunch of duplicate code in map loading and srf*_t

- src/engine/qcommon/q_shared.cpp
- src/engine/qcommon/q_shared.h
Gamelogic-side pr: https://github.com/Unvanquished/Unvanquished/pull/3359
Patch shared by freem, this moves `entityType_t` to gamelogic, since the engine doesn't need to know about it.
This should be fine to merge into master, since the ABI is still the same and merge conflicts from this change are unlikely.
> Move entityType_t in gamelogic

- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_surface.cpp
- src/engine/renderer/tr_vbo.cpp
NUKE unused `shader` and `fogIndex`, use `srfGeneric_t::numTriangles` instead of `srfVBOMesh_t::numIndexes`, to avoid duplication.
> NUKE some unused stuff from srfVBOMesh_t

- src.cmake
- src/engine/renderer/GeometryOptimiser.cpp
- src/engine/renderer/GeometryOptimiser.h
- src/engine/renderer/Material.h
- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_local.h
Requires #1635
This moves some surface merging stuff into GeometryOptimiser.cpp, and adds a function that removes duplicate vertices there. Also removes some more duplicate code, and puts all renderer surfaces into temp memory at the start of `R_CreateWorldVBO()`, to avoid going over more of them (i. e. it excludes portals, autosprite surfaces, `SF_SKIP` etc. at the start, rather than every time when iterating through all of the surfaces.
Adds some functionality that will be needed for further improvements to geometry processing with material system (I've done some tests around that, which already show good results, but I need to make it use surfaces of up to a specific limit of triangles to make it work well in all cases).
> Add GeometryOptimiser, move some stuff there from tr_bsp

- src/engine/client/cl_parse.cpp
- src/engine/client/client.h
- src/engine/qcommon/qcommon.h
- src/engine/server/sv_client.cpp
Split net messages if there are too many baselines. I don't like the solution too much because it only works for this exact issue, but I guess it'll do.
The layouts in https://users.unvanquished.net/~reaper/maps/layouts/spacetracks/ can be used to test this with map `spacetracks`.
Fixes https://github.com/Unvanquished/Unvanquished/issues/2124.
> Fix entity baseline overflow

- src/engine/renderer/GeometryOptimiser.cpp
- src/engine/renderer/GeometryOptimiser.h
- src/engine/renderer/Material.cpp
- src/engine/renderer/Material.h
- src/engine/renderer/ShadeCommon.h
- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_main.cpp
- src/engine/renderer/tr_scene.cpp
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_world.cpp
Some more changes to allow entities to be added to the material system. This entirely removes the `GenerateWorldMaterials()` function, instead materials are generated for each `MaterialSurface`. This also removes a bunch of things from `drawSurf_t`, `tess`, `Render_*()` etc. that were only used to pass information through to the material system.
Also fixed a memory leak in material system portal surface processing.
> Rework material system material and surface generation

- src/engine/renderer/GeometryOptimiser.cpp
- src/engine/renderer/GeometryOptimiser.h
- src/engine/renderer/Material.cpp
- src/engine/renderer/Material.h
- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_local.h
Fixes #1651
I opted for making the hash not use uv's instead, as it didn't seem to have much of any effect on the loading time, but resulted in merging a few more vertices. 
Also fixed sky brushes being added as surfaces to the material system.
> Fix geometry optimiser

- src/engine/renderer/GeometryOptimiser.cpp
- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_local.h
Requires #1652 because it has some other fixes in this area, I didn't test this pr without those.
Apparently, q3map2 sometimes produces garbage values for lightmap uvs in vertices, like nan or just garbage like -1e38 which later turns into inf in patch meshes. Most of these don't use the lightmapping shader, however from my testing some do.
This fixes a crash in `MergeDuplicateVertices()`, which was happening because of these garbages values, since they always compare as false.
> Validate BSP vertex input

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
Commenting out the code that does this was a regression in ab59550f23b41ea80b2443c72c9ce35fce1a7cb4.
> Check that driver matches when loading GLSL cache

- src/engine/renderer/GeometryOptimiser.cpp
- src/engine/renderer/GeometryOptimiser.h
- src/engine/renderer/Material.cpp
- src/engine/renderer/Material.h
- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/tr_animation.cpp
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_mesh.cpp
- src/engine/renderer/tr_model_iqm.cpp
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_shader.cpp
Implements #1294
Previously, when `r_lazyShaders 1` was used, it would simply load all of the possible shaders with the current graphics settings, and without deform shaders.
With this change, it will instead mark shaders that are used for BSP and model surfaces for building, which will be done in `RE_EndRegistration()`. Skins are also loaded (the variants with skeletal animation are always loaded because we don't know if an MD5 model will need them later).
This *greatly* reduces the amount of shaders built, and allows building deform shaders at map load. For example, on plat23 with pretty much all shader stuff enabled (except liquid shaders and static reflections), including material system, it went down from 433 shaders built at map load to just 28. I did know that a bunch of the …
> Improve lazy shader loading

- src/engine/renderer/GeometryOptimiser.cpp
- src/engine/renderer/GeometryOptimiser.h
> Fix missing tess.surfaceShader set in MarkShaderBuild()

- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_scene.cpp
- src/engine/renderer/tr_world.cpp
This is half of a feature from Wolf:ET, but we don't have the sgame/cgame counterpart, and none of the maps made for Unvanquished/Tremulous appear to use it. This was done in Wolf:ET by using a `misc_skyportal` entity on the map, parsing it in sgame and sending the result through configstrings. Daemon/Unvanquished never actually sets `RDF_SKYBOXPORTAL`.
We have maps that use background-in-a-box (`freeway`, `covid` etc.), but they use a different mechanism and keep working correctly with this change.
> NUKE RDF_SKYBOXPORTAL usages

- src/engine/renderer/tr_animation.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_model.cpp
- src/engine/renderer/tr_skin.cpp
`skinModel_t` was only used by Wolf:ET and XreaL, for some stupid back and forth of shader handles through IPC, which we thankfully do not have.
Also fixed some comments on `srfGeneric_t`.
> NUKE some unused stuff

- src/engine/renderer/tr_animation.cpp
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_mesh.cpp
- src/engine/renderer/tr_model_iqm.cpp
- src/engine/renderer/tr_world.cpp
Rename r_showEntityTransforms to r_showEntityBounds and add a new option (2) for showing the culling bounding boxes as a solid translucent surface, in addition to the old wireframe option. This makes it easier to see when the model is poking out of the box.
> Add translucent solid option for showing culling bbox

- src.cmake
- src/engine/renderer/GLMemory.cpp
- src/engine/renderer/GLMemory.h
- src/engine/renderer/GeometryCache.cpp
- src/engine/renderer/GeometryCache.h
- src/engine/renderer/Material.cpp
- src/engine/renderer/Material.h
- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/glsl_source/cull_cp.glsl
- src/engine/renderer/shaders.cpp
- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_vbo.cpp
Adds `GLStagingBuffer` and `GLBufferCopy()`. `GLStagingBuffer` allows setting buffer storage and map flags to 0 on the destination buffers, which pretty much guarantees that they will go into VRAM. The data is uploaded through mapping `stagingBuffer` and doing a copy of the data on the GPU.
The `stagingBuffer` itself should (still depends on the driver) go into the BAR memory (on Nvidia this shows up as `DMA_CACHED` when using `r_glDebugProfile on; r_glDebugMode 7`).
Slightly improves material system performance. Currently this is used for all material system buffers except the portal one (since it requires reading from the GPU), and for the 2 geometry cache buffers that are currently used.
Also fixed `GLBuffer.mapped` state being retained on map change/load.
> Implement staging buffer and use it for the material system

- src/engine/renderer/glsl_source/generic_fp.glsl
- src/engine/renderer/glsl_source/generic_vp.glsl
Divide out the w coordinate in the vertex shader instead of the fragment shader.
Also add comment about hacky depth fraction calc.
> GLSL cleanup: make var_FadeDepth a scalar

- src/engine/client/cl_console.cpp
- src/engine/client/client.h
If enabled, the current console input will be kept on map change the first time the console is opened after the new map is loaded.
> Implement con_persistOnMapChange

- src/engine/sys/sdl_glimp.cpp
Require VAO explicitly, because of #1690:
- https://github.com/DaemonEngine/Daemon/pull/1690
Also, because I like explicit logs, I added a log line for VBO as well, this way we have explicit log lines for VAO, VBO and FBO.
I also reworded things a bit.
> sdl_glimp: require VAO explicitly

- src/common/FileSystem.cpp
- src/engine/server/sv_ccmds.cpp
1. fix `listmaps` commands not respecting `fs_pakprefixes`
2. fix the server dropping in https://github.com/Unvanquished/Unvanquished/issues/3080
> Fix /listmaps with pak prefix + /map bug with invalid names

- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_local.h
E.g. different nopicmip or imageMaxDimension.
Fixes https://github.com/Unvanquished/Unvanquished/issues/2801
This could be useful if an image needs to be loaded with and without sRGB conversion (`IF_` flags are part of the image params).
We have a handful of images in game assets that will be loaded multiple times:
```
image params mismatch for gfx/weapons/tracer/spark: 0x2 0 0/0 128 0 vs. 0x0 0 0/0 0 0
image params mismatch for models/buildables/arm/screen_s: 0x0 0 0/0 128 0 vs. 0x0 0 0/0 16 0
image params mismatch for models/players/human_male/base: 0x0 0 0/0 0 0 vs. 0x0 0 0/0 128 0
```
> Allow loading an image multiple times with different params

- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_public.h
- src/engine/renderer/tr_types.h
- src/engine/sys/sdl_glimp.cpp
Remove unused extensions, workarounds related to them, and useless log messages.
> Clean up some OpenGL feature detection cruft

- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_model_iqm.cpp
- src/engine/renderer/tr_model_md3.cpp
- src/engine/renderer/tr_model_md5.cpp
- src/engine/renderer/tr_shader.cpp
- src/engine/renderer/tr_skin.cpp
There was no difference in behavior between them.
> Collapse shaderType_t::3D_DYNAMIC and 3D_STATIC into one

- src/common/Defs.h
- src/engine/sys/sdl_glimp.cpp
Let X11 and Wayland desktops (Linux, FreeBSD…) display the game name on the game windows instead of the engine binary name. This also makes possible to display the correct icon if that `WMCLASS` is also set in the `net.unvanquished.Unvanquished.desktop` file.
> sdl_glimp: set `APPID` as `WMCLASS` on Linux

- src/engine/renderer/tr_bsp.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_model_iqm.cpp
- src/engine/renderer/tr_model_md3.cpp
- src/engine/renderer/tr_model_md5.cpp
- src/engine/renderer/tr_shader.cpp
- src/engine/renderer/tr_skin.cpp
- src/engine/renderer/tr_types.h
Same idea as #1695 but for q3shaders instead of images.
Stacked on #1699.
It's a draft in case we want to make changes related to distinguishing "2D" vs. "3D" shaders when deciding whether to use sRGB.
> Allow registering shaders multiple times with different RSF_ flags

- src/engine/renderer/GLMemory.h
- src/engine/renderer/tr_local.h
@illwieckz Here's the thing to prevent the GLU dependency.
> Fix GLEW->GLU dependency regression

- src/engine/sys/sdl_glimp.cpp
Uniform buffer objects are required by the staging buffer. Obviously UBO is a very basic feature that we would have  anyway on a system supporting material system.
> Require UBO for material system

- src/engine/renderer/Material.cpp
Fix a maybe uninitialized vec3 use in Material code.
Reported by GCC 14:
```
src/engine/renderer/Material.cpp: In member function ‘void MaterialSystem::RenderMaterial(Material&, uint32_t)’:
src/engine/renderer/Material.cpp:2011:24: warning: ‘color[0]’ may be used uninitialized [-Wmaybe-uninitialized]
2011 |                 vec3_t color;
|                        ^~~~~
src/engine/renderer/Material.cpp:2011:24: warning: ‘color[1]’ may be used uninitialized [-Wmaybe-uninitialized]
In file included from src/common/Common.h:35:
In function ‘int VectorCompare(const vec_t*, const vec_t*)’,
inlined from ‘void GLUniform3f::SetValue(const vec_t*)’ at src/engine/renderer/gl_shader.h:860:21,
inlined from ‘void u_MaterialColour::SetUniform_MaterialColour(const vec_t*)’ at …
```
> material: fix a maybe uninitialized vec3 use

- azure-pipelines.yml
- src.cmake
- src/common/FileSystem.h
- src/common/Serialize.h
- src/common/Type.h
- src/common/Util.h
- src/engine/audio/Audio.cpp
- src/engine/audio/Emitter.cpp
- src/engine/framework/Resource.h
Some fixes for deprecated stuff I did in daemon-vulkan, backported here. These ones don't require any C++ version upgrade.
> Fix some deprecated std stuff

- src/engine/framework/CommonVMServices.cpp
- src/engine/qcommon/files.cpp
Use `shrink_to_fit()` after clearing strings holding a pak file after it is closed. This was a source of ever-growing memory usage, since `handleTable[handle].fileData.clear()` doesn't actually deallocate, so eventually all the storage in `handleTable` grows to some stupid size. Which was made worse by the fact that the same large dpk would get loaded into different slots.
Also removed some useless allocations + copies in `QVM_COMMON_FS_*`.
All in all, this reduced the memory usage by 2-3x when running `daemonded` and loading different maps.
> Fix some FS allocations/copies

- src/engine/renderer/GLMemory.h
- src/engine/renderer/tr_vbo.cpp
Use the old method to bind the IBO to the VAO instead of glVertexArrayElementBuffer. Fixes #1729.
> Renderer: Avoid a DSA function with VAOs

- src/engine/renderer/tr_bsp.cpp
Fixes log spam on some maps, like `thunder` and `perseus`.
We may also consider replacing [some of] the textures from `shared_colors_src` with the corresponding internal images in engine.
> Don't log bad uvs for white/black lightmaps

- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
This was caught by CI in #1741
Fixes `ShaderProgramDescriptor` definition order since `GLShader` requires the complete type, not sure how it was working previously.
Also fixed a missed `std::is_pod` by converting it to `IsPod`.
> Minor gl_shader fixes

- src/engine/renderer/glsl_source/depthtile1_fp.glsl
- src/engine/renderer/glsl_source/depthtile2_fp.glsl
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shade.cpp
- src/engine/renderer/tr_shader.cpp
- src/engine/renderer/tr_vbo.cpp
Remove the unused green and and alpha channel calculations in the depth tiles. Make dynamic lights renderable with `r_depthShaders 0`.
> Depth tile cleanup/debugability

- src/common/CPPStandard.h
- src/common/math/Vector.h
Add `CPPStandard.h` for checking C++ features support by version, replace deprecated `std::result_of` on >= C++17. Use the `/Zc:__cplusplus` for MSVC CI so it will get the correct version in `CPPStandard`.
> Add some support for C++17-23

- src/engine/renderer/gl_shader.cpp
Do not require GL_ARB_texture_float in vertex shader, this is a vertex-only extension.
This is only for convenience, I get this error on both Mesa `radeonsi` and `llvmpipe` drivers when I downgrade the GL/GLSL version to test GLSL 1.20, using `MESA_GL_VERSION_OVERRIDE=2.1 MESA_GLSL_VERSION_OVERRIDE=120` environment variables:
```
Warn: Source for shader program deformVertexes_0:
0: #version 120 
1: 
2: #extension GL_ARB_gpu_shader5 : require
3: #define HAVE_ARB_gpu_shader5 1
4: #extension GL_ARB_shading_language_420pack : require
5: #define HAVE_ARB_shading_language_420pack 1
6: #extension GL_ARB_texture_float : require
7: #define HAVE_ARB_texture_float 1
------------------^-------------------
0:7(12): error: extension `GL_ARB_texture_float' unsupported in vertex shader
```
I haven't got …
> gl_shader: do not require GL_ARB_texture_float in shader

- src/engine/client/cg_msgdef.h
- src/engine/client/cl_cgame.cpp
- src/engine/renderer/tr_public.h
- src/engine/renderer/tr_types.h
Cgame-side pr: https://github.com/Unvanquished/Unvanquished/pull/3405
Fixes #517
Move the stuff actually used by cgame (window and display sizes and display aspect) to `WindowConfig`. Merge the rest with `glconfig2_t` into `GLConfig`.
I've noticed this issue earlier when adding things to `glconfig2` and when working on daemon-vulkan: `RE_BeginRegistration()` uses `glconfig_t* glConfigOut, glconfig2_t glConfig2Out` as its parameters, even though it only needs the window and display sizes from the first one and nothing else.
> NUKE glconfig_t, use WindowConfig instead

- src/engine/renderer/Material.cpp
- src/engine/renderer/Material.h
- src/engine/renderer/tr_init.cpp
This can reveal bugs caused by merging materials that are not really the same.
> Add r_materialSeparatePerShader to debug material merging

- src/engine/audio/ALObjects.cpp
- src/engine/audio/Audio.cpp
- src/engine/audio/AudioData.h
- src/engine/audio/OggCodec.cpp
- src/engine/audio/OpusCodec.cpp
- src/engine/audio/Sample.cpp
- src/engine/audio/WavCodec.cpp
Removes most of the reallocations that happen because the file size is not known in advance.
This decreases the load time at start-up by easily 2x, and slightly improves load time for maps.
> Fix badly architectured audio file reads

- src/engine/renderer/Material.cpp
- src/engine/renderer/Material.h
Adds `/listMaterials` and `/listMaterialSystemStages`, which list some of the info for materials and shader stages used by the material system, like stateBits, GL program ID, buffer offsets and sizes etc.
> Add more material system debug commands

- CMakeLists.txt
- src.cmake
- src/common/Assert.h
- src/common/Math.h
- src/engine/framework/Resource.h
- src/engine/renderer/GLMemory.h
- src/engine/renderer/Material.cpp
- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/gl_shader_test.cpp
- src/engine/renderer/tr_local.h
- src/engine/sys/sys_events.h
Fix the code for laying out the std430 struct containing the uniforms for material system GLSL shaders. There is no functional change given the exact sets of uniforms we have on our GLSL shaders right now, but adding a new one could cause things to blow up as demonstrated at https://github.com/DaemonEngine/Daemon/issues/1696#issuecomment-3236089118.
I'm not attempting to run the added unit tests on CI for now as the client test does full client initialization including opening a window. So it wouldn't easily run in a headless environment.
> Fix material system uniform SSBO struct packing

- src/engine/qcommon/crypto.h
Only include gmp.h on MSVC to disable the warning, add a comment explaining why.
----
_Former comment:_
Do not include `gmp.h`, It is unused.
We need to link against GMP because we link against Nettle that requires it, but it looks like ourselves never use any symbol from GMP directly.
Imported from #1433:
- https://github.com/DaemonEngine/Daemon/pull/1433
When testing #1433 I was able to rebuild every engine binaries and NaCl VMs in Docker with this commit, I also built dll VM locally fine.
> crypto: only include gmp.h on MSVC to disable the warning, add a comment explaining why

- src/engine/client/ClientApplication.cpp
- src/engine/sys/sdl_glimp.cpp
- `sdl_glimp: properly set the APPID the SDL3 way, drop the SDL2 setting`
* Drop the SDL2 way of doing things.
* The SDL3 environment variable wasn't `SDL_HINT_APP_ID` but `SDL_APP_ID`.
* For some reasons `SetEnv()` doesn't work (SDL3 bug?)
* We can use `SDL_SetAppMetadataProperty()` instead, and it works.
* We can probably don't have to care about being on X11/Wayland or not.
* Use `SDL_SetAppMetadataProperty()` for other things too.
- `sdl_glimp: disable DPI scaling`
> Set APPID the SDL3 way, disable DPI scaling

- external_deps/build.sh
Some Quality of Life changes for `external_deps/build.sh`
Extracted from #1433 before merging:
- https://github.com/DaemonEngine/Daemon/pull/1433
The only new commit that was never made public before is `external_deps: improve extract logging`.
> Some Quality of Life changes for `external_deps/build.sh`

- src/engine/renderer/GeometryOptimiser.cpp
- src/engine/renderer/Material.cpp
- src/engine/renderer/Material.h
- src/engine/renderer/gl_shader.cpp
- src/engine/renderer/gl_shader.h
- src/engine/renderer/glsl_source/fogGlobal_fp.glsl
- src/engine/renderer/glsl_source/fogQuake3_fp.glsl
- src/engine/renderer/glsl_source/fogQuake3_vp.glsl
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_shade.cpp
- Don't draw global fog twice in material system (like #1740 but for material system)
- Make fog distance for global fog be the real distance from viewer to vertex, not the distance dotted with the view axis. Non-global fog has this issue too but I will fix it in a later PR. Here's two screenshots from master using increased FOV to exaggerate the effect:
- Fix wrong fog for models that use `nonNormalizedAxes` scaling. The issue is pretty subtle with our player models, so here's a before/after with a 3x scaled repeater.
> Fix some fog bugs

- src/engine/renderer/tr_bsp.cpp
Cherry-pick from #1730:
- https://github.com/DaemonEngine/Daemon/pull/1730
This one shouldn't be controversial.
One discussion possible is that we can do this conversion either in `tr_shader.cpp`, either in `tr_bsp.cpp`.
Fog shaders should be parsed when requested by the BSP code, there is no meaning outside of that, so the behavior should be the same.
> tr_shader: linearize fog colors

- src/engine/renderer/Material.cpp
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shade.cpp
Fixes this issue for me which can happen when SSAO + realtime lights + bindless textures are used:
It's a weird bug since what seems to matter is whether realtime lights were rendered on the first frame after loading. Turning on or off `r_drawDynamicLights` afterward has no effect.
Although #1684 as a whole triggers the SSAO noise bug to occur all the time for me (not just on certain maps), one of the commits from it turned out to fix the bug. If I cherry-pick `Add 2 missing glTextureBarrier()` to master, the SSAO noise is gone. So this PR is an expanded version of that commit.
In the light tile case, I don't think there is normally a texture feedback loop because we are not writing to the main rendering FBO, only the depth tile one. But I found a comment saying that with bindless …
> Add more texture barriers to prevent depth sampling issues

- src/engine/renderer/GeometryOptimiser.cpp
Regression in de2fb50511f8c08feca30a6787a3fd613b61a661. I guess this shader marking can happen while there are triangles waiting in the buffer. Though I don't understand the connection with backEnd.currentEntity.
> Fix crash on dummygame load with r_lazyShaders = 1

- src/engine/renderer/tr_shader.cpp
- tr_shader: do not ignore shaders without a stage, it's a valid use case for a transparent surface
- tr_shader: do not assume shaders without a stage is fog
It makes possible to do this:
```c
// The transparent texture that is also transparent in editor too.
// It should not be listed and selectable in editor. It can be used
// on model surfaces to hide them.
gfx/shared_colors/transparent
{
qer_editorImage textures/shared_colors_src/transparent_d
qer_trans 0
surfaceparm nolightmap
surfaceparm nomarks
surfaceparm trans
}
gfx/shared_colors/transparent_nonsolid
{
qer_editorImage textures/shared_colors_src/transparent_d
qer_trans 0
surfaceparm nolightmap
surfaceparm nomarks
surfaceparm nonsolid
surfaceparm trans
}
```
> Do not assume shaders without a stage is fog

- src/engine/renderer/tr_fbo.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_public.h
- src/engine/sys/sdl_glimp.cpp
- Clean up unused code
- Fix an instance where GL_fboShim was not used
- Add optional target argument for R_BindFBO (lifted from #1480)
- Add BlitFramebuffer function to FBO shim
The last 2 things are needed for FBO blitting. I need FBO blitting to fix  #1783, while it is also used in #1480 so I'm trying to reuse the code from there. But I've tried to make R_BindFBO more robust by making GL_DRAW_FRAMEBUFFER the default instead of GL_FRAMEBUFFER because with the latter, you get issues that it matters what order you do the bindings in because it overwrites both READ and DRAW framebuffers.
> Remove unused FBO code and add groundwork for FBO blit functions

- src/engine/renderer/Material.cpp
This marks shaders correctly for materials that have specular w. r. t. reflection mapping settings.
> Mark lightMappingMaterial shaders for building correctly

- cmake/DaemonFlags.cmake
I'm not saying the GDB stacktrace will work with CPP23, but at least it works without CPP23.
Works around #1800:
- https://github.com/DaemonEngine/Daemon/issues/1800
> cmake: add STRIP_SOURCE_PATHS=OFF to fix GDB stacktrace and Linux profiles like Orbit

- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_shader.cpp
- tr_image: extend internal image detection
- tr_image: do not rely on previously set data for cinematic, numberize and rename as `*name`
- tr_image: resize builtin images as `1×1`
- renderer: simplify builtin color image name parsing, rename as `$name`, forget about unused aliases
- tr_image: rename framebuffer images as `*name`
- tr_image: rename remaining builtin images as `$name`
- tr_image: rename generated textures as `*name`
- tr_image: make the `$black` builtin image opaque
- tr_image: NUKE the $red, $green and $blue builtin images
___
Original message:
- make `_black` opaque
- add `_null` for zeroed image (instead of `_black`)
- explicitly set `_cinematic` color instead of relying on previously set values
imported from https://github.com/DaemonEngine/Daemon/pull/1793
- make …
> tr_image: rework some builtin images

- src/engine/renderer/Material.cpp
- src/engine/renderer/tr_backend.cpp
- src/engine/renderer/tr_fbo.cpp
- src/engine/renderer/tr_image.cpp
- src/engine/renderer/tr_init.cpp
- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_public.h
- src/engine/renderer/tr_shade.cpp
- src/engine/sys/sdl_glimp.cpp
Depends on #1813.
Implement a code path for sampling `u_DepthMap` in shaders from a separate copy of the depth texture, instead of the same one that is attached to the rendering FBO. By default, this will be enabled if the driver does not implement `TextureBarrier`, in order to prevent texture feedback loops. Behavior is controlled by `r_copyDepthBuffer`. This is meant to fix #1783. Seems to work on my Mac system.
Also I keep having some issues with SSAO + bindless textures on a Mesa + AMD setup. In a game with map `survival-pit` I got the SSAO artifacts as shown below. (Same ones I used to get with dummygame. I still got those even after #1731 which I though would fix them but didn't, but they may have gone away after a Mesa update.) I can't reproduce the artifacts in a local game but if …
> Copy depth texture to avoid texture feedback loops

- src/engine/renderer/tr_local.h
- src/engine/renderer/tr_main.cpp
- src/engine/renderer/tr_surface.cpp
- renderer: introduce `R_TBNtoQtangentsFast()` and `floatToSnorm16_fast()`
- renderer: faster `Tess_SurfaceIQM()` and `Tess_SurfaceMD5()` with `R_TBNtoQtangentsFast()`
I noticed that the the `Tess_SurfaceIQM()` function (used in CPU model code) was spending significant time in `R_QtangentsToTBN()` and this was spending significant time in `floatToSnorm16()`. Then I discovered that this function was doing a rounding to the closest int on every component of the vector, calling `lrintf()` on every component one by one. But, this is model rendering code, we may not need that much exactitude, and a basic truncate can likely do the job as well and the result is likely good enough. Also, this CPU code is a fallback for when low-end devices can't process the current model on GPU, so the player is …
> Fast `R_QtangentsToTBN()` variant to speed-up `Tess_SurfaceIQM()` and `Tess_SurfaceMD5()`

- src/common/StackTrace.h
This will at least prevent the crash described in #1828 from happening when the stack trace feature is disabled. The message was annoying anyway.
> Remove "StackTrace unavailable" message

- src/engine/client/cl_main.cpp
- src/engine/null/null_input.cpp
- src/engine/qcommon/qcommon.h
- src/engine/sys/sdl_input.cpp
Also improve game controller logging and fix a 'gamepad leaked' message from SDL.
> Migrate `in_` cvars

- src/common/Log.cpp
- src/common/Log.h
- src/engine/framework/LogSystem.cpp
In the engine, access the `logs.suppression.*` cvars through their objects, instead of looking them up in the cvar map via their names. Looking them up via name is seriously unsafe on a non-main thread. Simply reading the int or bool is still technically thread-unsafe, but should be fine in practice.
Fix `logs.writeSrcLocation.*` access in gamelogic. These cvars will no longer emit warnings due to duplicate registration, and be obeyed by the gamelogic.
> Logging: improve suppression thread safety; fix file/line logging in gamelogic
